- src/generic/Matrix.jl
The function was constructing generic matrices over FlintZZ.
> Fix regression in det_polynomials.jl benchmark

- src/generic/Matrix.jl
This only becomes useful once "Make generic matrices view-able" (previously among the Nemo pull requests) is merged, but the commits do not overlap.
> fix typo in matrix view

- src/generic/GenericTypes.jl
- test/generic/Perm-test.jl
otherwise we cannot iterate over `elements(PermGroup(Int8(6))`
this is consistent with `Base.factorial(::Int8)` which returns `Int`
This won't work for `n>20`, but If You need to iterate over `S₂₀` then the fix should be elsewhere ;-)
> change type of AllPerms.all to Int

- src/AbstractAlgebra.jl
These have to be handled differently than ordinary functions, i.e. functions have to be defined in Oscar.jl and then exported to the user. They will call the appropriate functions in the different libraries.
> Remove IdealSet and FiniteField empty functions.

- src/generic/GenericTypes.jl
- src/generic/PermGroups.jl
- test/generic/Perm-test.jl
benchmark:
```julia
function generate(itr)
k = 0
for p in itr
@assert p isa perm
k += p[1]
end
return k
end
```
```julia
julia> @time generate(elements(PermGroup(10));
3.818291 seconds (36.29 M allocations: 1.352 GiB, 5.59% gc time)
julia> @time generate(UInt(10));
3.478949 seconds (36.29 M allocations: 1.352 GiB, 6.14% gc time)
```
```julia
julia> @time K1 = generate(elements(PermGroup(10)));
0.307158 seconds (7.26 M allocations: 664.454 MiB, 22.96% gc time)
julia> @time K2 = generate(Generic.elements!(PermGroup(10)));
0.035850 seconds (12 allocations: 640 bytes)
julia> K1 == K2
true
```
In `generate(elements(PermGroup(10)))`:
* `p = randperm(10); perm(copy(p), false)` allocates `192` bytes and `192*factorial(10)/1024/1024 = 664.453125` (MiB of memory). I don't think You can get any …
> non-allocating version of AllPerms

- src/generic/GenericTypes.jl
- src/generic/YoungTabs.jl
Benchmark:
```julia
function bench(AP)
k = 0
for p in AP
k += p[1]
end
return k
end
```
master:
```julia
julia> @time bench(AllParts(80));
7.281104 seconds (78.98 M allocations: 8.638 GiB, 32.01% gc time)
```
this branch:
```julia
julia> @time bench(AllParts(80));
3.321162 seconds (47.39 M allocations: 4.554 GiB, 29.93% gc time)
```
There are three allocations per generated `Partition`: the partition `Vector` of `Int`s, the `Partition` object itself (`32 bytes`) and mysterious something worth another 32 bytes (no idea where it comes from).
There might be a slightly (at most 25%) faster method in 
> Mircea Merca, "Fast algorithms for generating ascending compositions", J Math Model Algor (2012)
but its `nextperm` function (see Algorithm 7 therein) would be way more complicated, not sure it …
> More performant version of AllParts

- docs/src/mpolynomial_rings.md
- src/AbstractAlgebra.jl
- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
In #106 @thofma proposed a function `change_ring`. Here I implemented such a function, which I rather called `change_base_ring`. I do not consider it to be nice, but it works. If there is a low level constructor using the internal data structures `coeffs` and `exps`, this could probably be implemented more efficiently by simply applying `g` to coeffs. But I did not find such a constructor.
> add function "change_base_ring" for MPoly

- docs/src/mpolynomial_rings.md
- src/AbstractAlgebra.jl
- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
Implementation of a function `vars` that returns the variables occurring in a multivariate polynomial of type `MPoly`.
The downside is that for a polynomial p the return type of `vars(p)` is 
Array{AbstractAlgebra.Generic.MPoly{T},1}
while the return type of `vars(parent(p))` is
Array{Symbol,1}
How about changing `vars(a::MPolyRing)` to something like `symbols(a::MPolyRing)`?
> vars for MPoly

- src/generic/PermGroups.jl
this is circular shift
benchmark:
```julia
using AbstractAlgebra
using BenchmarkTools
function perm_sample(N::Integer=255; samplesize=1000, seed=1234)
srand(seed)
G = PermutationGroup(N)
return [rand(G) for i in 1:samplesize]
end
function bench(sample; power = 50, pow_function=^)
T = eltype(sample[1])
n = T(0)
for p in sample
n += pow_function(p,power)[1]
end
return n
end
sample = perm_sample(500, samplesize=10000);
bench(sample, 50) # pre-computes cycle decompositions
@benchmark  bench(sample, 50)
```
old:
```
BenchmarkTools.Trial: 
memory estimate:  45.31 MiB
allocs estimate:  165828
--------------
minimum time:     43.933 ms (9.23% GC)
median time:      44.832 ms (9.27% GC)
mean time:        45.522 ms (9.60% GC)
maximum time:     52.169 ms (8.36% GC)
--------------
samples: …
```
> change % into - in ^(::perm, ::Integer)

- test/generic/Fraction-test.jl
The line test `b * a == q` made no sense to me. The number of iterations was small and the probability of `b` to divide `a` was small. Therefore this test was only rarely executed. Therefore I increased the number of iterations.
> fixed test_gen_frac_divides()

- src/generic/PermGroups.jl
```julia
function generate(itr)
k = 0
for p in itr
@assert p isa perm
k += p[1]
end
return k
end
```
old:
```
@btime generate(Generic.elements!(PermGroup(10)))
39.698 ms (6 allocations: 432 bytes)
19958400
```
new:
```
@btime generate(Generic.elements!(PermGroup(10)))
23.465 ms (6 allocations: 432 bytes)
19958400
```
> add @inbounds in nextperm

- src/generic/MPoly.jl
`addmul!` was not in the list of unsafe operations in the documentation, but it is used for example for elements in the base ring in the multiplication of `MPoly`. Thus I added it.
> Add missing unsafe operations for Generic.MPoly

- src/AbstractAlgebra.jl
- src/generic/MPoly.jl
@saschatimme was teasing me about our polynomial ring constructors. They are a bit clumsy in the REPL. I threw together a simple macro to make life easier. It will just overwrite whatever there was before with the same name. There are a bit fragile, but they should be good enough for interactive use. I would like to get some feedback from @wbhart, @fieker. In particular I don't know if this should support different monomial orders.
```julia
julia> @PolynomialRing ZZ x y z
Multivariate Polynomial Ring in x, y, z over Integers
julia> x + y * z
x+y*z
julia> @PolynomialRing ZZ x[1:10]
Multivariate Polynomial Ring in 10 variables x1, x2, x3, x4, ..., x10 over Integers
julia> @PolynomialRing ZZ x[1:2:10]
Multivariate Polynomial Ring in x1, x3, x5, x7, x9 over Integers
julia> @PolynomialRing ZZ …
```
> Fancy macros for multivariates

- src/AbstractAlgebra.jl
- src/Generic.jl
- src/generic/Fraction.jl
- src/julia/Rational.jl
* Speeds up generic Fraction module by not canonicalising every time num or den is accessed
* This requires a patch to Nemo and Hecke beforehand (see the import_fix PR for Nemo), however, if this patch is applied there, no further such patches will be required in the future as AbstractAlgebra now controls its own import exclusion list
> Speed up internal use of numerator/denominator

- src/generic/MPoly.jl
This PR does the following:
1. Sorting of already sorted polys is made fast (I was sorting starting from reverse order!)
2. Sorting is no longer used for lex in inflate/deflate (it is needed for other orderings)
3. Deflation now short circuits the gcds once they reach 1
4. Inflate/deflate now have special versions for MPolys which don't read and write exponent vectors
5. Change_base_ring is sped up for MPoly type
> Mpoly speedups

- src/generic/MPoly.jl
This makes the printing helper functions more general so that generic multivariate polys over flint multivariates (needed for general evaluation) print correctly. It also fixes a bug in show_minus_one.
> Make some printing helper functions more general and fix a bug.

- src/generic/LaurentSeries.jl
- test/generic/LaurentSeries-test.jl
Fix #229.
In the example of @martinra, the first argument of `mul!` had coefficients that were not zero. But the function was assuming that this is the case. Could you please double check the fix @wbhart?
I think additionially we were violating our aliasing/mutation rules. For the same reason `add!` is also wrong, right? It is not allowed to do what iit s currently doing. If you agree, I will also fix `add!`.
> Fix Laurent series inplace multiplication

- docs/Project.toml
- docs/make.jl
This addresses the following warning:
Warning: `format = :html` is deprecated, use `format = Documenter.HTML()` instead.
> use Documenter.HTML() instead of :html

- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
The documentation of the `change_base_ring(p::AbstractAlgebra.MPolyElem{T}, g)` promises that the function `g` is applied to the coefficients. 
Even though not documented, I guess `change_base_ring(p::MPoly{T}, g)` is supposed to behave similarly.
This pull request ensures that this actually happens instead of coercing the coefficients into `new_base_ring`.
> apply g to coefficients instead of coercing into new base ring

- src/generic/Matrix.jl
- src/generic/ResidueField.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
* Fixes fflu! to work for residue rings
* Otherwise require matrices to be over an integral domain type in fflu!
* Make randmat_with_mat require a residue ring or integral domain type
* Fixes a documentation error
* Fixes test code for Matrix/MatrixAlgebra to not use poly's over residue rings that aren't integral domains
Fixes Nemo's ticket 351.
For some reason, the fraction free LU that uses divexact instead of inv doesn't work over non-integral domains. This includes polynomials over a residue ring for example. I have not been able to modify the algorithm to work in this case, so I simply have to demand an integral domain type. Much of this PR is to ensure this.
> Solve interpolation fix

- src/generic/AbsSeries.jl
Note: zero(R) itself is in RelSeries.jl and covers both models.
> Add zero! for AbsSeries.

- src/generic/PermGroups.jl
Apparently `full` is not defined anymore in this sense in julia 1.1.0 and `Array` is used to convert sparse to dense arrays.
> replace "full" by "Array" in a docstring

- docs/src/mpolynomial.md
- docs/src/mpolynomial_rings.md
- src/generic/MPoly.jl
Just makes ideal divrem optional and clarifies that gcd is not provided automatically for all multivariate types (yet).
Also fixes a bug in vars function.
> Clarify MPoly interface for gcd and divrem for ideal division and fix bug in vars.

- src/generic/RelSeries.jl
This fixes two problems: one is that despite this file being in RelSeries, the function is for all SeriesElems including AbsSeriesElem's, which have no pol_length, so printing polynomials over abs series breaks.
I also argue that the current definition as pol_length > 1 is ambiguous for anything non-zero right now, consider:
```
julia> R,x= PowerSeriesRing(QQ, 5,"x",model=:capped_relative)
(Univariate power series ring in x over Rational Field, x+O(x^6))
julia> T,t = PolynomialRing(R, "t")
(Univariate Polynomial Ring in t over Univariate power series ring in x over Rational Field, t)
julia> (x+ 1)*t
(1+x+O(x^5))*t
julia> (x)*t
x+O(x^6)*t
julia> (x)*t  + x^4
x+O(x^6)*t+x^4+O(x^5)
```
If you think about it you can work out what it means, but parens would help, and make it easier to copy …
> fix for needs parentheses

- src/generic/AbsSeries.jl
- src/generic/Poly.jl
They break Revise (https://github.com/timholy/Revise.jl/issues/253) and are not legal according to https://docs.julialang.org/en/v1/manual/documentation/index.html.
> Remove comments following a docstring

- src/Rings.jl
- src/generic/AbsSeries.jl
- src/generic/Fraction.jl
- src/generic/LaurentSeries.jl
- src/generic/MPoly.jl
- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- src/generic/NCPoly.jl
- src/generic/Poly.jl
- src/generic/PuiseuxSeries.jl
- src/generic/RelSeries.jl
- src/generic/Residue.jl
- src/generic/ResidueField.jl
- test/generic/AbsSeries-test.jl
- test/generic/Fraction-test.jl
- test/generic/LaurentSeries-test.jl
- test/generic/MPoly-test.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
- test/generic/Poly-test.jl
- test/generic/PuiseuxSeries-test.jl
- test/generic/RelSeries-test.jl
- test/generic/Residue-test.jl
- test/generic/ResidueField-test.jl
This fixes the following bug:
```julia
julia> a = zero_matrix(ZZ, 2, 3)
[0 0 0]
[0 0 0]
julia> b = zero_matrix(ZZ, 3, 3)
[0 0 0]
[0 0 0]
[0 0 0]
julia> a in [b, a]
ERROR: Incompatible matrix spaces in matrix operation
Stacktrace:
[1] error(::String) at ./error.jl:33
[2] check_parent at /home/thofmann/.julia/dev/AbstractAlgebra/src/generic/Matrix.jl:108 [inlined]
[3] ==(::AbstractAlgebra.Generic.Mat{BigInt}, ::AbstractAlgebra.Generic.Mat{BigInt}) at /home/thofmann/.julia/dev/AbstractAlgebra/src/generic/Matrix.jl:680
[4] in(::AbstractAlgebra.Generic.Mat{BigInt}, ::Array{AbstractAlgebra.Generic.Mat{BigInt},1}) at ./operators.jl:950
[5] top-level scope at none:0
julia> a in [a, b]
true
```
> Do not throw an error when comparing two objects with different parents

- src/generic/MPoly.jl
- src/generic/Matrix.jl
We sometimes deepcopy matrices so that we can apply in-place functions to them (e.g. rref!, fflu!, etc.). These in-place functions require all entries of the copy to be distinct (otherwise modifying an entry will modify more than one entry), but Julia has the unusual behaviour of preserving identity of objects under deepcopy, meaning that if the matrix started with elements that were identical objects, the deepcopy will have the same property.
This patch stops that from happening. But perhaps @thofma can confirm that this won't cause some other problem for us, e.g. with sets or whatever it was that we wrote the code this way for in the first place?
> Fix deepcopy to not preserve identity between elements of a matrix.

- src/generic/AbsSeries.jl
- src/generic/Fraction.jl
- src/generic/FreeModule.jl
- src/generic/LaurentSeries.jl
- src/generic/MPoly.jl
- src/generic/Map.jl
- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- src/generic/ModuleHomomorphism.jl
- src/generic/NCPoly.jl
- src/generic/Poly.jl
- src/generic/PuiseuxSeries.jl
- src/generic/QuotientModule.jl
- src/generic/RelSeries.jl
- src/generic/Residue.jl
- src/generic/ResidueField.jl
- src/generic/Submodule.jl
Julia usually prints nested structures (like arrays or dictionaries) with `:compact => true`, for example:
```julia
julia> print(1im)
0 + 1im
julia> print(IOContext(stdout, :compact => true), 1im)
0+1im
julia> print([1im])
Complex{Int64}[0+1im]
```
This PR enables the same for all "derived" structures in AbstractAlgebra. Here is an example from Hecke:
```julia
julia> Ax, x = A["x"]
(Univariate Polynomial Ring in x over Group algebra of dimension 8 over Rational Field, x)
julia> A(2)
Element of Group algebra of group
GrpAb: Z/2^3
over
Rational Field with coefficients fmpq[2, 0, 0, 0, 0, 0, 0, 0]
julia> coeff(2*x, 1)
Element of Group algebra of group
GrpAb: Z/2^3
over
Rational Field with coefficients fmpq[2, 0, 0, 0, 0, 0, 0, 0]
julia> 2*x
(fmpq[2, 0, 0, 0, 0, 0, 0, 0])*x
```
> Print nested structures with :compact => true

- src/generic/AbsSeries.jl
Calling DomainError without an error message results in: `ERROR: MethodError: no method matching DomainError()` so add an error message here.
> Another error message for DomainError

- src/AbstractAlgebra.jl
- src/AbstractTypes.jl
We need some better supertypes for `AnticNumberField`. This change here will enable us to do `AnticNumberField <: SimpleNumField{fmpq} <: NumField{fmpq}` in Nemo. This will simplify our work in Hecke tremendously.
> Add some types for number fields

- src/generic/PermGroups.jl
- test/generic/Perm-test.jl
It would be good to discuss the possible group interface during the next week;
I can definitely see the obvious things like
* `parent[_type]`, `elem_type`, `hash`, `deepcopy_internal`, `==`, `isequal`
* `(G::Group)()`, `(G::Group)(g::GroupElem)`
* `one(::Group)`, `isone(g)`
* `show`;  what do we actually need for `needs_parentheses`, etc?
* rand(::Group)
* `*(g::GroupElem, h::GroupElem)`, `inv(g::GroupElem)`
the unsafes reduce to (with fallbacks):
* `one!(g::GroupElem) = parent(g)()`
* `mul!(out::GroupElem, g::GroupElem, h::GroupElem) = g*h`
* inv!(g::GroupElem) = inv(g)`
I'm not quite sure we should be providing `promotion_rules`?
> add mul!(::perm, ::perm, ::perm)

- src/Rings.jl
- src/generic/Poly.jl
It must be defined outside of generic. This fixes the following bug:
```julia
julia> using Nemo;
julia> Zx, x = PolynomialRing(FlintZZ, "x")
(Univariate Polynomial Ring in x over Integer Ring, x)
julia> F = GF(2)
Galois field with characteristic 2
julia> change_base_ring(x, F)
x
julia> typeof(ans)
AbstractAlgebra.Generic.Poly{Nemo.gfp_elem}
```
It should be `gfp_poly`.
I also added a version where one can supply the target parent. For non-trivial examples one ends up with polynomials with different parents otherwise.
> Fix change_base_ring

- src/generic/DirectSum.jl
- src/generic/FreeModule.jl
- src/generic/GenericTypes.jl
- test/generic/Poly-test.jl
* Speed up application of canonical injections/projections of direct sums
* Change the constructor for free_module_elems to be in conformance with the other module element types
* Fix a random printing issue in one of the tests
> Fast homomorphisms

- src/Generic.jl
@chethega suggests we have been doing our imports from supermodule incorrectly. The syntax we were using refers to the AbstractAlgebra package on the system, not the supermodule, which is what we want here.
Although this doesn't affect us, it may make it harder for people to reproduce bugs we report.
> Add some missing sigils. 

- src/generic/MPoly.jl
The source of the failure on julia 1.3 is an ambiguity error (it won't error on 1.1 or 1.2):
```julia
julia> using AbstractAlgebra;
julia> S, (x, y, z) = PolynomialRing(ZZ, ["x", "y", "z"]; ordering=:lex);
julia> f = -8*x^5*y^3*z^5+9*x^5*y^2*z^3-8*x^4*y^5*z^4-10*x^4*y^3*z^2+8*x^3*y^2*z-10*x*y^3*z^4-4*x*y-10*x*z^2+8*y^2*z^5-9*y^2*z^3;
julia> coeff(f, [2, 3], [3, 2])
ERROR: MethodError: setcoeff!(::AbstractAlgebra.Generic.MPoly{BigInt}, ::Int64, ::BigInt) is ambiguous. Candidates:
setcoeff!(a::AbstractAlgebra.Generic.MPoly{T}, i::Int64, c::T) where T<:Union{RingElem, AbstractFloat, Integer, Rational} in AbstractAlgebra.Generic at /home/thofmann/.julia/dev/AbstractAlgebra/src/generic/MPoly.jl:4142
setcoeff!(a::AbstractAlgebra.Generic.MPoly{T}, i::Int64, c::U) where {T<:Union{RingElem, …
```
> Fix ambiguity in setcoeff!(::MPoly, ...)

- test/generic/Fraction-test.jl
This test is not run by default so the bug could not be catched by running the test suite.
> fix test with fraction valuation

- src/Generic.jl
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
This is an expected method (much more common than `deepcopy` in Julia in general), and is by definition faster. For example even for the following small 3x3 matrix over `Univariate Polynomial Ring in t over Rationals`, it's about 6 times faster:
```
[t+1//1 t 1//1]
[t^2 t t]
[-2//1 t+2//1 t^2+t+1//1]
```
For a similar 30x30 matrix, it's 18 times faster.
>  implement copy(::MatrixElem)

- docs/src/matrix_spaces.md
- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
This is similar to how `similar` works for arrays:
`similar(array, [element_type=eltype(array)], [dims=size(array)])`
Here we specify the ring instead of `element_type`:
```
similar(x::Mat, [R::Ring=base_ring(x)]
similar(x::Mat, [R::Ring=base_ring(x)], r::Int, c::Int)
```
> allow to specify a Ring in similar for matrices

- src/generic/Matrix.jl
Before:
```julia
julia> matrix(ZZ, 4, 4, [10^i for i=0:15])
[1 10 100 1000]
[10000 100000 1000000 10000000]
[100000000 1000000000 10000000000 100000000000]
[1000000000000 10000000000000 100000000000000 1000000000000000]
```
After:
```julia
julia> matrix(ZZ, 4, 4, [10^i for i=0:15])
[            1              10              100              1000]
[        10000          100000          1000000          10000000]
[    100000000      1000000000      10000000000      100000000000]
[1000000000000  10000000000000  100000000000000  1000000000000000]
```
Also, as can be seen on the last line, I added one more space between entries (so there are at least 2 spaces between entries of adjacent columns) as I find it easier on the eyes, but I can revert that bit.
> align entries when printing matrices

- docs/src/matrix_spaces.md
- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
This means that Generic.MatSpaceElem is the default fall-back type
when similar(matrix, ...) is not specifically implemented for matrix.
In particular, this implements the similar interface for Nemo
matrices. In other words, similar becomes an optional functionality
for custom matrices.
> widen similar signature to MatrixElem

- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
One could not push a polynomial with more then 4^2 = 16 terms. This fixes it.
```julia
julia> AbstractAlgebra
[ Info: Recompiling stale cache file /home/thofmann/.julia/compiled/v1.1/AbstractAlgebra/b8V2b.ji for AbstractAlgebra [c3fe647b-3220-5bb0-a1ea-a7954cac585d]
julia> R = ResidueRing(ZZ, 2)
Residue ring of Integers modulo 2
julia> R, (x1, x2) = PolynomialRing(R, ["x1", "x2"])
(Multivariate Polynomial Ring in x1, x2 over Residue ring of Integers modulo 2, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Res{BigInt}}[x1, x2])
julia> C = AbstractAlgebra.Generic.geobucket(R)
AbstractAlgebra.Generic.geobucket{AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Res{BigInt}}}(1, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.Generic.Res{BigInt}}[0, 0])
julia> push!(C, sum(x1^i for i …
```
> Fix the geobuckets

- src/generic/Poly.jl
Adds two comfort functions to `Poly.jl`:
- `nvars(R::AbstractAlgebra.PolyRing)`, which just returns `1`
- `gens(R::AbstractAlgebra.PolyRing)`, which returns `[gen(R)]`
This makes it easier to write generic code that works both on `PolyRing` and `MPolyRing` objects.
> Adding gens and nvars to Poly.jl

- src/generic/MPoly.jl
At the moment `push_term!` does not check for zero coefficients, yielding invalid polynomials (this breaks hashing). For example:
```julia
julia> R = GF(5)
Finite field F_5
julia> Rx, (x1, x2) = PolynomialRing(R, ["x1", "x2"])
(Multivariate Polynomial Ring in x1, x2 over Finite field F_5, AbstractAlgebra.Generic.MPoly{AbstractAlgebra.gfelem{Int64}}[x1, x2])
julia> derivative(x1^5 + x1^10, 1).coeffs
2-element Array{AbstractAlgebra.gfelem{Int64},1}:
0
0
julia> derivative(x1^5 + x1^10, 1) == 0 * x1
true
julia> hash(derivative(x1^5 + x1^10, 1))
0x76045bbcf704c72a
julia> hash(0*x1)
0x094d42ed2df5809f
```
This fixes it by ignoring the term if the coefficient is zero.
> Fix push_term!

- docs/src/mpolynomial.md
- src/generic/MPoly.jl
Modified change base ring, such that it keeps the type of the ring if possible.
To be precise, changing the base ring of a Nemo polynomial ring returns a Nemo polynomial ring.
> Change base ring

- .travis.yml
Builds are taking forever on appveyor (only one concurrent job). So enable the Windows build on travis (and drop 1.1 support).
I have disabled the appveyor webhooks for pull requests.
Let's see how this looks like.
> Enable windows build on travis

- src/julia/Integer.jl
- test/julia/Integers-test.jl
Fixes bug 10 reported on my repo (only just noticed this now).
> Fix incorrect reduction in powmod when exponent is 1.

- docs/src/matrix.md
- docs/src/mpolynomial.md
- src/AbstractAlgebra.jl
- src/generic/MPoly.jl
- src/generic/Matrix.jl
- test/generic/MPoly-test.jl
- test/generic/Matrix-test.jl
I did not touch `map_from_func` etc. I am not sure the convention applies since it is a constructor. There is no object on which the function is applied. Also
`map_from_func(x -> x^2, ZZ, ZZ)` does not look as nice as `map_from_func(ZZ, ZZ, x -> x^2)`.
I don't have strong feelings about it. If someone says we want it, then I will add it here.
> Make func/ring first argument in change_base_ring

- docs/src/matrix.md
- docs/src/perm.md
- docs/src/types.md
- docs/src/ytabs.md
- src/AbstractAlgebra.jl
- src/generic/GenericTypes.jl
- src/generic/Matrix.jl
- src/generic/PermGroups.jl
- test/generic/Perm-test.jl
As a new "breaking" release of AA is in preparation, here is a breaking change.
Julia's [convention](https://docs.julialang.org/en/v1/manual/style-guide/index.html#Use-naming-conventions-consistent-with-Julia-base/-1) is for types to be CamelCase. All exported types from `AbstractAlgebra` follow this convention, except `perm`. Let's fix this.
```julia
julia> function gettypes(m::Module, only_lower=false; all=false)
modnames = names(m, all=all)
if only_lower
filter!(n -> islowercase(first(String(n))), modnames)
end
modobjs = getfield.(Ref(m), modnames)
filter(x -> x isa Union{DataType,UnionAll,Union}, modobjs)
end
gettypes (generic function with 2 methods)
julia> gettypes(AbstractAlgebra)
41-element Array{Any,1}:
AbsSeriesElem
AccessorNotSetError
Array
ErrorConstrDimMismatch
Fac
FieldElem …
```
> rename perm -> Perm

- src/generic/Matrix.jl
We don't test 32 bits architectures on CI right?
> use Int instead of Int64 in a view signature

- src/Rings.jl
- test/Rings-test.jl
I run into this inconvenience regularly. `elem_type` is already implemented on instances, like `eltype`, there is no reason not to do it for `parent_type`.
> implement parent_type on instances

- src/julia/GF.jl
- test/julia/gfelem-test.jl
`rand(::GFField)` seems to be the only left definition which takes only one argument and is not yet converted to using the `Random` API.
> conform rand(::GFField) to the Random API

- docs/src/finfield.md
- docs/src/module.md
- docs/src/types.md
- src/generic/DirectSum.jl
- src/generic/FreeModule.jl
- src/generic/GenericTypes.jl
- src/generic/InvariantFactorDecomposition.jl
- src/generic/QuotientModule.jl
- src/generic/Submodule.jl
- src/julia/GF.jl
- src/julia/JuliaTypes.jl
- test/Fields-test.jl
- test/Rings-test.jl
- test/generic/DirectSum-test.jl
- test/generic/FreeModule-test.jl
- test/generic/InvariantFactorDecomposition-test.jl
- test/generic/Module-test.jl
- test/generic/QuotientModule-test.jl
- test/generic/Submodule-test.jl
- test/julia/GFElem-test.jl
This was quite simpler than renaming `perm` to `Perm`, which required manual renaming because `perm` occured a lot in places which shouldn't be updated. Here `sed` was enough.
rename gfelem -> GFElem
rename free_module_elem -> FreeModuleElem
rename direct_sum_module_elem -> DirectSumModuleElem
rename quotient_module_elem -> QuotientModuleElem
rename snf_module_elem -> SNFModuleElem
rename submodule_elem -> SubmoduleElem
> rename lowercase types to CamelCase

- src/generic/PermGroups.jl
- test/generic/Perm-test.jl
This make `perm"(a, b)"` error out ~~and `perm"(1 2)"` equivalent to `perm"(1,2)"`. I can change the latter to producing an error if desired.~~ (EDIT: I suppressed this possibility, it was making the regex code more complicated. It can be added later.)
> fix #450, safer perm_str macro

- src/AbstractAlgebra.jl
- src/Generic.jl
- src/Rings.jl
- src/generic/AbsSeries.jl
- src/generic/Fraction.jl
- src/generic/InvariantFactorDecomposition.jl
- src/generic/LaurentSeries.jl
- src/generic/MPoly.jl
- src/generic/Matrix.jl
- src/generic/Poly.jl
- src/generic/QuotientModule.jl
- src/generic/RelSeries.jl
- src/generic/Residue.jl
- src/generic/SparsePoly.jl
- src/generic/YoungTabs.jl
- src/julia/Rational.jl
There was more then one issue here. First of all Base does not provide `gcdx` for `Rational{<: Integer}` and also `div` for `Rational{<: Integer}` is doing weird things:
```julia
julia> div(Rational{BigInt}(1), Rational{BigInt}(2))
0
julia> typeof(ans)
BigInt
```
This was easy to fix.
The real rabbit whole were our import/export statements. I  noticed that we are not consistent with our import/export philosophy regarding `exp` and all these other troublemakers. While we did (correctly!) not do `import Base: exp` in src/AbstractAlgebra.jl we did it in src/Generic.jl. This coursed all kinds of confusion! I cleaned this up. In particular every use of these troublemakers (`exp`, `div`, `divrem`, `numerator`, `denomonator` and `sqrt`) inside the library does not need any namespace …
> Clean up import/export and fix #440

- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Poly-test.jl
It was only defined for an abstract type (`AbstractAlgebra.MatAlgElem{T}`), so didn't work with the type of actual instances.
Two questions:
1. is this function useful for `AbstractAlgebra.MatElem`? It seems it's used only for polynomials of matrices, which works only with matrix algebras... If not, should I delete this method?
2. would we consider defining this method for instances, instead of for types, as the related functions `displayed_with_minus_in_front` and `needs_parentheses` are defined on instances?
> fix show_minus_one for matrices

- src/generic/Matrix.jl
These functions were still referenced from matrix.md, leading
to a "Missing docstring" error in the rendered docs.
> restore docstrings for map/map!

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
This is a simple function which is easy to support when matrices are considered as collections/arrays.
This is already defined in Hecke for `MatElem`.
> add eltype(::MatrixElem)

- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
Closes https://github.com/Nemocas/Nemo.jl/issues/651
> Fix copy/deepcopy for generic matrices

- src/AbstractAlgebra.jl
When using e.g. Nemo, and you get the argument wrong, this was leading to a stackoverflow:
```julia
julia> crt(1, 3, 1, 7)
ERROR: StackOverflowError:
Stacktrace:
[...]
```
Now:
```julia
julia> crt(1, 3, 1, 7)
ERROR: MethodError: no method matching crt(::Int64, ::Int64, ::Int64, ::Int64)
Closest candidates are:
[...]
```
> remove useless recursive method of crt

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
Sorry, in #463 I missed the case where the `eltype` is not a `RingElem`.
> make eltype work on all matrices

- src/AbstractAlgebra.jl
- test/generic/Perm-test.jl
These forwarding methods in AbstractAlgebra.jl were leading to infinite recursion because `AbstractAlgebra.Perm === Generic.Perm`.
As I don't know the rationale behind all these forwarding methods in this file, I don't know what fix the maintainers would like:
1. delete the faulty methods from AbstractAlgebra.jl (this PR currently)
2. stop importing `Generic.Perm` within AbstractAlgebra.
I will update according to requests.
BTW, I would love if someone can give me a pointer to an explaination for these forwarding methods (i.e. why `AbstractAlgebra.AllPerms !== Generic.AllPerms` for example).
> fix StackOverflowError with Perm("not an integer")

- docs/src/matrix_algebras.md
This was messing up all the remaining of the page, see https://nemocas.github.io/AbstractAlgebra.jl/latest/matrix_algebras/.
> docs: fix wrongly placed backticks

- src/NCRings.jl
- src/Rings.jl
- src/generic/AbsSeries.jl
- src/generic/LaurentSeries.jl
- src/generic/MPoly.jl
- src/generic/NCPoly.jl
- src/generic/Poly.jl
- src/generic/RelSeries.jl
- src/generic/SparsePoly.jl
- src/julia/Integer.jl
- src/julia/Rational.jl
- test/NCRings-test.jl
- test/Rings-test.jl
- test/generic/AbsSeries-test.jl
- test/generic/LaurentSeries-test.jl
- test/generic/MPoly-test.jl
- test/generic/NCPoly-test.jl
- test/generic/Poly-test.jl
- test/generic/RelSeries-test.jl
- test/julia/Integers-test.jl
- test/julia/Rationals-test.jl
The expression `throw(DomainError())` was actually throwing a `MethodError`, because `DomainError()` doesn't accept zero arguments.
> fix DomainError() without arguments

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
In the spirit of https://github.com/Nemocas/AbstractAlgebra.jl/pull/404:
```
a = matrix(ZZ, [1 2 3; 4 5 6; 7 8 9]);
b = matrix(ZZ, [-1 -2; -3 -4]);
a[1:2, 2:3] = b; a
```
returns the matrix `a` with (the entries of) the 2x2 block in the upper right corner replaced by (`deepcopy`s of the entries of) `b`:
```
[1  -1  -2]
[4  -3  -4]
[7   8   9]
```
Also allows `Int` and `:` arguments. Throws an error if `b` does not fit exactly.
> Block replacement functionality for matrices

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
This is the idiomatic way to call vcat on a vector of matrices,
at least when performance matters (as opposed to
`vcat(vector_of_matrices...)`).
Let's optimize this case, like it's done in `Base` for `Vector`
and `Matrix`.
Similarly for `hcat`.
This is an alternative solution to the special implementation `vcat(A::Vector{<: MatrixElem})` which was removed in #409.
> optimize reduce(vcat, vector_of_matrices)

- src/AbstractAlgebra.jl
- src/NCRings.jl
- src/Rings.jl
- src/generic/Matrix.jl
- src/julia/JuliaTypes.jl
- test/NCRings-test.jl
- test/Rings-test.jl
Previously, `powers(a, 1)[2]` was an undefined entry in the array. When `a::RingElem`, it was fixed in #291, but the bug remained for other objects.
I merged here the three different definitions, which were basically identical.
> fix bug in powers and add few more tests

- src/NCRings.jl
- test/NCRings-test.jl
There doesn't seem to be a justification to disallow `powers(x, 0)`, which would otherwise be perfectly defined according the definition in the docstring. 
This also slightly simplifies slightly the implementation by getting rid of the local variable `c`, and renames `A` to `M`, which makes it easier to compare the implementation to the specification in the docstring.
> enable powers(x, 0)

- src/NCRings.jl
- src/Rings.jl
- test/generic/NCPoly-test.jl
This adjusts the error for NC polynomials to what we have for commutative polynomials:
```julia
julia> PolynomialRing(MatrixAlgebra(ZZ, 2), "x")[2]^-2 # master
ERROR: MethodError: no method matching inv(::AbstractAlgebra.Generic.NCPoly{AbstractAlgebra.Generic.MatAlgElem{BigInt}})
Closest candidates are:
[...]
julia> PolynomialRing(MatrixAlgebra(ZZ, 2), "x")[2]^-2 # PR
ERROR: DomainError with -2:
exponent must be >= 0
[...]
```
> implement literal_pow for NCRingElem

- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
Some methods were using the `.entries` internal field, so
are applicable only to concrete types of matrices which
define this field.
Moreover, these too wide signatures could lead to
ambiguity errors.
> fix some signatures using wrongly MatrixElem

- src/Rings.jl
The test for this is in Nemo itself. It's rather hard to construct a test here as we have separate optimised code for divides within AbstractAlgebra itself.
> Fix a bug in divides that affects Nemo #687.

- src/Factor.jl
- src/generic/Fraction.jl
These signatures had unnecessarily tight constraints, which can lead to more work when downstream types are used as their type parameters.
> Widen some signatures for Fac, FracElem and FracField

- docs/src/matrix.md
- docs/src/matrix_spaces.md
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
First, this relaxes `UnitRange` to `AbstractVector`, at no cost, as `sub(a, ::Vector{Int}, ::Vector{Int})` was already implemented. Then, we allow `Int` and `:` arguments in `sub`, so that `sub` and `getindex` accept exactly the same arguments (when there are two of them).
Personally, I would also remove `sub(a, r1::Int, c1::Int, r2::Int, c2::Int)`, it's too easy to get confused with the order of the arguments, and it's so easy to write instead `sub(a, r1:r2, c1:c2)`. 
I would actually remove `sub` completely, as it's redundant with `getindex`. This function was once part of Julia, and was creating views if I remember correctly, but was removed in version 0.5 I think.
DO NOT MERGE: This depends on #524.
> sub and getindex on matrices: harmonize the arguments they accept

- src/generic/Matrix.jl
Cf. discussion at #516.
The current behavior implies that we can have `isone(a) == true` and `one(a) == a` error out, e.g. `a = ZZ[1 0]`, because `one(a)` requires a square matrix, but `isone(a)` returns `true`. So this PR makes `one` and `isone` consistent. 
I will add tests if this gets support.
> make isone(non_square_matrix) false

- docs/make.jl
This was wrongly documented to default to :none, but it doesn't.
This option was the cause of the huge pile of useless garbage
when running `julia docs/make.jl`, which indicates all the
docstrings that are not referenced in the docs.
We are too far from this state (all methods with docstrings
referenced in the docs) for these warnings to be
currently useful.
> docs: use `checkdocs = :none` option in makedocs

- docs/src/functional_map.md
- docs/src/map_cache.md
This was not reported as an error by Documenter.jl,
but this was still showing a couple of spurious
```
Map with the following data
Domain:
=======
Integers
Codomain:
========
Integers
```
> docs: fix maps output

- test/AbstractAlgebra-test.jl
- test/generic/Matrix-test.jl
To avoid having to copy-paste code for testing different rings on the same operations, while keeping the ability to see easily where the potential errors come from, @fieker suggested to use functions, called repeatedly on different line with different ring arguments. This is "option 1" (cf. code). An alternative is to use `@testset for`, which is "option 2". Here is how both options look like, where `RINGS` is a predefined `Dict` mapping a name (e.g. `"exact ring"`) to an initialized ring together with parameters allowing to call `rand` on it. 
```julia
function test_comparison(R, randparams)
S = MatrixSpace(R, rand(1:9), rand(1:9))
A = rand(S, randparams...)
@test A == A
end
@testset "Generic.Mat.comparison..." begin
test_comparison(RINGS["exact ring"]...)
test_comparison(RINGS["exact …
```
> Matrix tests: comparisons

- src/generic/Matrix.jl
Fixes a serious bug with aliasing of matrix elements in hnf_cohen! when delayed reduction is in use.
> Fix bug in aliasing in hnf_cohen!.

- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Matrix-test.jl
These functions should select the best dense matrix type
for the given destination ring.
Fixes part of Nemocas/Nemo.jl#651 (comment).
(Was open wrongly yesteday at https://github.com/wbhart/AbstractAlgebra.jl/pull/16)
> fix change_base_ring and map_entries for custom matrices

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
We should always have `typeof(transpose(mat)) == typeof(mat)`.
Fixes part of https://github.com/Nemocas/Nemo.jl/issues/651#issuecomment-540493003
> fix typeof(tranpose(mat)) in some cases

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
We should always have `typeof(identity_matrix(mat)) == typeof(mat)`. As a result, we also get `typeof(inv(mat)) == typeof(mat)`.
Fix part of https://github.com/Nemocas/Nemo.jl/issues/651#issuecomment-540493003.
> fix typeof(identity_matrix(::MatElem)) in some cases

- docs/src/matrix.md
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
I suggested this change twice [here](https://github.com/Nemocas/AbstractAlgebra.jl/pull/522#issue-333536648) and [here](https://github.com/Nemocas/AbstractAlgebra.jl/pull/514#issue-331963113), without it being rejected, so here is the PR.
`identity_matrix(R::Ring, n, m)` which produces a non-square matrix has been introduced very recently, so it's unlikely that a user relies on its existence. If there is demand for such a function in the future, we can always re-introduce it, preferably with a better name. But once we have comitted this API, it's more difficult to remove.
I propose this change because `identity_matrix(R, n, m)` is a misnomer when the result is not an identity matrix, and there is now a relatively easy alternative:
`diagonal_matrix(one(R), n, m)`.
The other version, …
> remove methods of identity_matrix which do not create an identity matrix

- src/generic/Matrix.jl
This fixes a couple a bits in the docstrings (like a `;` instead of a `,`, or `nrows` instread of `ncols`), and also renames the `rng` argument to `rows` or `cols` as appropriate; `rng` sounds really like an obscure name, I supposed it's short for "range", but then it's misleading, as it doesn't have to be a range.
I would like to propose to make this `cols`/`rows` argument a keyword argument, as there are already 4 mandatory arguments, so it feels a keyword for the (presumably) more rarely used argument would increase clarity.
> fix add_column (and friends) docstrings

- src/generic/Poly.jl
_map: mpoly case was fixed to NOT type the final argument (Rx)
Problem: here, in Generic, PolyRing does not include Flint-Types
check_parent: Julia complained about b being overwritten with
object of different type
> two problems _map and check_parent

- docs/mkdocs.yml
See also <https://www.mathjax.org/cdn-shutting-down/>.
> Replace obsolete cdn.mathjax.org

- src/AbstractAlgebra.jl
- src/generic/FreeModule.jl
- src/generic/GenericTypes.jl
used currently for FreeModule (in Oscar: to print homogenous
components "properly")
and AnticNumberField (Nemo: to print cyclotomic and quadratic fields)
and GrpAbFinGen (Hecke: many things)
Key features for "nice" jupyter printing
Completely invisible to the user, purely developer toys
> add pretty printing infrastructure

- src/AbstractAlgebra.jl
- src/AbstractTypes.jl
Also change Module{T} to derive from AdditiveGroup instead of Group, and ModuleElem{T} to derive from AdditiveGroupElem instead of GroupElem.
Not sure if this is the best approach, but I believe we do need a way to distinguish between additive and multiplicative groups (in the GAPGroup code, basically all groups will be multiplicative, just as in GAP).
Happy to do it some of other way if you tell me which/how (of course I'd also like to understand why that other way is better).
I would imagine that one then could write relatively efficient "adapter types" which wrap an additive group (element) inside a multiple group (element) and vice versa. In GAP, I can't do this efficiently; in Julia, I am hoping one can compile away most of the conversion if all types are known ahead; but we'll have …
> Add AdditiveGroup, AdditiveGroupElem

- docs/src/matrix.md
- src/generic/Matrix.jl
It's basically the same as that for RingElement, and as
`FieldElement <: RingElement`, trying to show docs for
`inv(M::Generic.MatrixElem{<:FieldElement})` resulted in
showing both docstrings.
> remove docstring for inv(M::Generic.MatrixElem{<:FieldElement})

- src/generic/AbsSeries.jl
- src/generic/LaurentSeries.jl
- src/generic/MPoly.jl
- src/generic/Module.jl
- src/generic/ModuleHomomorphism.jl
- src/generic/Poly.jl
- src/generic/PuiseuxSeries.jl
- src/generic/RelSeries.jl
- src/julia/Integer.jl
For the record, perl command to make the replacement:
```
perl -i -p -e 'BEGIN{undef $/;}  s/"""\n   (\S)/"""\n    \1/smg' *jl
```
> docs: fix wrong spacing in docstrings, which breaks highlighting

- docs/src/constructors.md
This might remove too much, please feel free to push to this branch to adjust. 
Fix #577.
> docs: adjust wrong BigInt("123") constructor example

- docs/src/mpolynomial.md
- src/AbstractAlgebra.jl
- test/generic/MPoly-test.jl
I will add documentation if this change gets support.
> enable R["x", "y"] syntax for MPolyRing construction

- src/generic/MPoly.jl
Before:
```julia
julia> using Nemo; R, x = @PolynomialRing(ZZ, x); typeof(R)
AbstractAlgebra.Generic.MPolyRing{fmpz}
```
Now:
```julia
julia> using Nemo; R, x = @PolynomialRing(ZZ, x); typeof(R)
FmpzMPolyRing
```
Ideas welcome on how to test that without depending on `Nemo`.
By the way, is the only purpose of the macro to not have to write quotes around `x` on the rhs?
> fix #274, at-PolynomialRing macro creates generic polynomials

- docs/src/index.md
It is kind of redundant, since one is already browsing the documentation.
> Remove documentation link from the documentation

- src/generic/PermGroups.jl
- test/generic/Perm-test.jl
It's currently possible to construct an invalid permutation by multiplying two incomptible ones, e.g.:
```julia
julia> p = perm"(1, 2)" * perm"(1, 2, 3)";
julia> p # invalid state
Error showing value of type Perm{Int64}:
ERROR: BoundsError: attempt to access 2-element BitArray{1} at index [3]
[...]
julia> p = perm"(1, 2, 3)" * perm"(1, 2)"; # multiplication fails
ERROR: BoundsError: attempt to access 2-element Array{Int64,1} at index [3]
[...]
```
With this PR, in both of the above cases, we get a more explicit message:
```julia
julia> p = perm"(1, 2, 3)" * perm"(1, 2)";
ERROR: ArgumentError: incompatible permutation groups
Stacktrace:
[...]
```
> Perm multiplication: check that they have compatible parents

- docs/src/polynomial_rings.md
- docs/src/series_rings.md
- src/generic/AbsSeries.jl
- src/generic/LaurentSeries.jl
- src/generic/NCPoly.jl
- src/generic/Poly.jl
- src/generic/PuiseuxSeries.jl
- src/generic/RelSeries.jl
- test/generic/AbsSeries-test.jl
- test/generic/RelSeries-test.jl
Updates set_length!, set_val!, set_prec! and set_scale! to return their argument to support polynomials and series with immutable types.
Fixes #13.
Fixes #16.
Immediately after this is applied, the corresponding Nemo patch should be applied. There is also a Hecke patch but this can be delayed if needed.
Note this is breaking.
> Set val prec length

- src/PrettyPrinting.jl
@tthsqe12 I need your help here. There are unncessary parantheses in the fractions:
```julia
julia> print(AbstractAlgebra.obj_to_latex_string(x^10//(2(x+1)^4)))
\frac{\left(\frac{1}{2}x^{10}\right)}{\left(x^{4} + 4x^{3} + 6x^{2} + 4x + 1\right)}
```
> Add a latex printer

- src/generic/Matrix.jl
I guess it was supposed to be inside code ticks, or quotes. Either way, currently it isn't displayed correctly.
> Properly style kernel function name

- docs/src/fraction.md
- docs/src/integer.md
- docs/src/mpolynomial_rings.md
- docs/src/polynomial.md
- docs/src/rational.md
- docs/src/residue.md
- src/generic/Fraction.jl
- src/generic/MPoly.jl
- src/generic/Poly.jl
- src/generic/ResidueField.jl
- src/julia/Integer.jl
- src/julia/Rational.jl
- test/generic/Fraction-test.jl
- test/generic/MPoly-test.jl
- test/generic/Poly-test.jl
- test/generic/ResidueField-test.jl
- test/generic/Submodule-test.jl
- test/julia/Integers-test.jl
- test/julia/Rationals-test.jl
This main purpose of this PR is to provide:
* generic sparse multivariate square root [1] (new algorithm)
* generic univariate square root [1]
There are two functions: sqrt and issquare.
It also adds:
* issquare for integers and rationals
* issquare and sqrt for Z/pZ
* issquare and sqrt for fraction fields
Exact multivariate sqrt (check=false) is about twice as fast as checked mode (at 4000 terms in output). Exact univariate sqrt is only about 20% faster (at 10000 terms in output).
Note this does not provide sqrt for multivariates in Nemo, as this has to be implemented in Flint (which @tthsqe12 and I have agreed to do soon).
The PR makes no systematic attempt to implement the new sqrt interface being discussed.
[1] over an (exact) integral domain in which a sqrt is available
> Square root of all the things

- src/generic/MPoly.jl
This is not a bug. In writing the paper I was able to prove this extra check is not needed. I have extensively tested it (millions of cases).
> Remove an unneeded check.

- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
The original test code for MPoly sqrt was not testing very much in the non-square case.
This PR makes it work harder.
It also fixes a bug:
* Although the heap was being resized on demand, the list of exponents that could be used on the heap was of fixed size, causing an BoundsError in the worst case (the new test code hits this case).
> Improve test code for sqrt

- src/julia/GF.jl
- test/julia/GFElem-test.jl
We cannot call add! or addeq! on the underlying data, since this will
overflow for Int. So use the same as in the mul! and fall back to +.
> Fix add! and addeq! for GF

- src/generic/Matrix.jl
- test/AbstractAlgebra-test.jl
- test/generic/Matrix-test.jl
- test/runtests.jl
This fixes https://github.com/Nemocas/Nemo.jl/issues/892.
The code was constrained to work only for `Generic.MatSpaceElem` by mistake.
> enable rand for matrix spaces beyond Generic.MatSpaceElem

- src/generic/MPoly.jl
- test/generic/Fraction-test.jl
- test/generic/LaurentPoly-test.jl
- test/generic/LaurentSeries-test.jl
- test/generic/MPoly-test.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
- test/generic/Module-test.jl
- test/generic/NCPoly-test.jl
- test/generic/Poly-test.jl
- test/generic/PuiseuxSeries-test.jl
- test/generic/RelSeries-test.jl
- test/generic/Residue-test.jl
- test/generic/ResidueField-test.jl
- test/julia/Floats-test.jl
- test/julia/GFElem-test.jl
- test/julia/Integers-test.jl
- test/julia/Rationals-test.jl
- test/runtests.jl
This adds a `reproducible(args...)` function in tests, which checks that `rand(rng, args...)` gives reproducible results. All `rand` methods are tested with this now, and the one for `MPoly` is fixed (a call was wrongly using the global RNG).
> fix reproducibility of rand for MPoly, and add reproducibility tests

- src/generic/GenericTypes.jl
- src/generic/MapWithInverse.jl
Don't make assumptions about how the wrapped maps store the (co)domain; instead, go through the official API, i.e., call `domain` resp. `codomain` on the wrapped map.
> Fix (co)domain delegation for maps with retraction/section

- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Matrix-test.jl
This changes solve_fflu to can_solve_with_solution_fflu.
The function also now supports non-square matrices and singular matrices.
I've also added test code for it, as it is quite complex.
I don't know if the algorithm is published or not. 
solve_lu, solve_ff should be easy to derive from can_solve_with_solution_fflu and I will work on these next. They will follow in a later PR.
I have not added can_solve_with_solution_fflu as a special case for solve at this stage. That will come in a later PR.
Of course the generic code will no longer call solve_fflu in Nemo. That will have to be changed to the new interface separately. That will require changes to Flint.
> solve_fflu -> can_solve_with_solution_fflu + non-square/singular cases.

- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
Currently, `rand(matspace, 2)` is ambiguous; it could mean:
* `rand(make(matspace), 2)`, which creates a vector
* `rand(make(matspace, 2)) == rand(make(matspace, make(base_ring(matspace), 2)))`,
i.e. the "2" is used as a make-argument to specify how to generate random
elements of the matrix
We choose the first interpretation here, as we are used to interpret
a call like `rand(X, 2)` as creating a vector, `rand(X, 2, 3)` as
creating a matrix and so on. On the other hand, there are almost no
(or not at all) cases in Oscar where an integer is used as
an argument to make.
> interpret rand(matspace, 2) as creating a Vector

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
* Hooks can_solve_with_solution_fflu up to can_solve_with_solution in the case of matrices over a fraction field
* Left side is handled via naive transposes
* Test code for same
* Puts solve_with_det back in, as Nemo overloads this, and crashes if it isn't there (naughty Nemo!)
> Solve fraction field

- src/PrettyPrinting.jl
Currently, when I load DifferentialEquations.jl, this causes AbstractAlgebra.jl to be loaded which pirates the method
```julia
show(::IO, ::MIME{Symbol("text/latex")}, x::Union{AbstractFloat, Integer, Rational})
```
because
```julia
julia> RingElement
Union{RingElem, AbstractFloat, Integer, Rational}
```
I find this quite aggravating sometimes so I hope it can be removed.
> Remove Base.show piracy

- .github/workflows/CI.yml
- README.md
Also updates badges in README.md, and reformat CI.yml to make future diffs in there clearer.
Preview of updated README with new badges: https://github.com/fingolfin/AbstractAlgebra.jl/blob/mh/coverage/README.md
I would recommend to remove some of the macOS tests, as GitHub offers fewer parallel runners for that, so they hold up processing of the tests for a given PR. E.g. just test on 1.0, 1.5 and nightly. If desired, I can add that to this PR or a future PR.
Also, perhaps consider dropping Travis as that is now heavily rate limited (Nemocas already used up all its credits for December 2020, and they stopped their offer for additional credits to open source software, so there's that). I'd also suggest to drop AppVeyor support, it doesn't seem to add anything compared to the GitHub Action …
> Enable Codecov integration, GH action tests on Windows

- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
This allows to obtain the Sampler in simple cases without having to know about `RandomExtensions.make` (when one can do `rand(M)`, it's natural to expect to be able to do `rand(Sampler(rng, M))` for `M::MatSpace`).
> define Random.Sampler(rng, ::MatSpace) in simple enough cases

- src/generic/FreeModule.jl
- src/generic/Module.jl
- src/generic/ModuleHomomorphism.jl
- src/generic/QuotientModule.jl
- src/generic/Submodule.jl
Unfortunately the whole module code has poor type inference, mainly because of
https://github.com/Nemocas/AbstractAlgebra.jl/blob/475bd212ac7b6fa757448bc298876c3acf00c872/src/generic/GenericTypes.jl#L1143
This makes the compiler crawl if this code is used in some non-trivial examples (see for example https://github.com/thofma/Hecke.jl/issues/111)
This is a quick fix for `sub` for @martinra, but does not solve the underlying issue.
I think it would be best if these fields were properly typed using concrete types or if the access was via a getter function with type assert. What do you think @wbhart?
> Fix some inference issues for module code

- .github/workflows/CI.yml
... this was lost with the removal of Travis (resp. with Travis stopping to work).
However, for the final step (the actual deployment) to work, someone with admin rights for this repo may have to set a `DOCUMENTER_KEY`. To generate one, you can do this:
```julia
julia> using DocumenterTools, AbstractAlgebra
julia> DocumenterTools.genkeys(AbstractAlgebra)
```
Then go to "Settings" -> "Deploy Keys" (should be something like <https://github.com/Nemocas/AbstractAlgebra.jl/settings/keys>) and add it there.
> Deploy documentation to website using GitHub Actions

- src/AbstractAlgebra.jl
- src/algorithms/FinField.jl
- test/julia/GFElem-test.jl
This adds iteration for finite fields:
1. but tests only AA fields (of degree 1), should we consider adding `Nemo` as a test dependency to test generic algorithms more thoroughly?
2. the code is put under "src/algorithms/FinField.jl" as I did for Laurent polynomials, with the idea of separating generic algorithms from algebraic structures provided by AA (I understood this was a desired feature and I still wish to untangle the code in AA in this direction);
3. I added a `test_iteration` function in the "src/" directory, to make it easier to test the functionality from other repositories; a similar function `test_rand` could be moved in the "src/" directory away from the "runtests.jl" file to avoid the duplication that I committed in AA and `Nemo`; this means adding `using Test` in …
> add iteration for finite fields

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
As we currently don't handle multiplication between matrices and vector spaces elements (#572), it can be convenient to use AA matrices as row- or column vecors (`ncols(M) == 1` or `nrows(M) == 1`). But indexing into these vectors still requires providing two indices, which is annoying. There was quite some controversy in #540 on whether AA matrices should support so-called "linear indexing", so this feature was removed from this PR. But linear indexing into "1-dim" matrices (vectors) will likely not meet the same resistance. C.f. also this [comment (if I understood it correctly)](https://github.com/Nemocas/AbstractAlgebra.jl/pull/540#issuecomment-605653519):
> However, it is incredible useful of 1-dim matrices...
and in [the next …
> add linear indexing for matrices which have only one row or column

- src/Rings.jl
- src/generic/AbsSeries.jl
- src/generic/Fraction.jl
- src/generic/LaurentSeries.jl
- src/generic/Matrix.jl
- src/generic/Poly.jl
- src/generic/PuiseuxSeries.jl
- src/generic/RelSeries.jl
- src/generic/Residue.jl
- src/generic/ResidueField.jl
This does not try to unify the implementation notes found in the documention (e.g. in ["required interace" for rings](https://nemocas.github.io/AbstractAlgebra.jl/latest/rings/#Exact-division)) with the only remaining docstring.
The deleted docstrings were also not referred to from the documentation, so no change was necessary there.
cc. @fingolfin
> fix part of #535, deduplicate divexact docstrings

- src/Factor.jl
- src/PrettyPrinting.jl
- test/Factor-test.jl
- test/PrettyPrinting-test.jl
It is probably desired to restore the printing of the spaces around the "*"  in Fac{T}.
> Add cdot for printing * with spaces

- src/AbstractAlgebra.jl
- src/Deprecations.jl
- src/generic/GenericTypes.jl
- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
- Make it a keyword for `MatrixSpace` and `MatrixAlgebra` (It is already a keyword argument for the matrix spaces and matrix algebras defined in Nemo.)
- Fix the caching for `Generic.MatAlg`
> Fixes for caching

- docs/src/perm.md
- docs/src/ytabs.md
- src/Deprecations.jl
- src/generic/Matrix.jl
- src/generic/PermGroups.jl
- test/generic/Perm-test.jl
to follow group interface of oscar, e.g.
https://github.com/oscar-system/Oscar.jl/blob/ae0a3b0e4daa7fdeff73241b80bbeadc39cfe298/src/Groups/GAPGroups.jl#L189
(@fingolfin, is there a doc with the interface we drafted?)
btw. given that GAP permutations are the permutations of oscar I'd also stop exporting `perm` (why lowercase?) to allow this
https://github.com/oscar-system/Oscar.jl/blob/ae0a3b0e4daa7fdeff73241b80bbeadc39cfe298/src/Groups/GAPGroups.jl#L258
to move on.
Also: given the remarkably small impact of this change, is it really worth keeping here? (all usages inside AA only need the storage vector of a permutation).
@rfourquet @fingolfin @thofma
EDIT: In the meantime I forgot why have I started this:
* added compact printing of perms :)
```julia
julia> p = randperm(100);
julia> …
```
> use one(::SymmetricGroup) instead of (G::SymmetricGroup)()

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
This generalizes the `setindex!` function call `A[r, c] = B` for more situations:
1. It allows `A` to be a `MatrixElem`, which means all matrices we have (not sure why it was restricted before).
2. `r` and `c` can be `Vector{Int}, UnitRange{Int}, Int, :`.
3. `B` can be a `MatrixElem`, `Matrix` or `Vector` (in this case the slice must be one-dimensional, that is, `length(r) == 1` or `length(c) == 1`.
For example, one can now just do `z[2, 1:3] = [1,2,3]`.
I had it partially in Hecke, but I think it should live here.
P.S.: There is a chance one could do it more compactly doing some metaprogramming, but I think in this case it is not worth it.
> Allow more general setindex!(::MatrixElem, ...)

- src/julia/JuliaTypes.jl
Instances of these types are meant to be singleton objects
via the caching mechanism, but as they no fields, the
same can be achieved by making them immutable
(having no fields implies that they are bitstypes and
automatically have the singleton property, like e.g. `nothing`;
this also means that comparison should be at leas as cheap
as comparing pointers like was previously the case when mutable).
Moreover, in a `Distributed` setting, uniqueness of instances
was broken, in particular instances from two process would
compare unequal (an alternative fix for that would be to
define `==`).
> make Integers, Rationals and Floats immutable structs

- src/AbstractAlgebra.jl
- src/algorithms/generic_functions.jl
My previous fix was bad. The functions must be defined before the import statements in `Generic.jl`.
> Fix #743 for real

- src/Misc/Poly.jl
In Hecke the functions called `AbstractAlgebra.PowerSeriesRing`, which does the correct thing. During the transfer these functions landed in Generic, meaning that they call `AbstractaAlgebra.Generic.PowerSeriesRing`, which is not optimal. So in particular on input `fmpq_poly` the functions was creating generic power series instead of using `fmpq_abs_series`.
@wbhart
> Fix PowerSeriesRing call in Misc/Poly.jl

- src/generic/Misc/Series.jl
This simply uses the code from Hecke for series inv over a field instead of the existing implementation that was in AbstractAlgebra.
It was missed in the original movement of code from Hecke.
> Enable series inv from Hecke.

- src/generic/RelSeries.jl
`isdefined` was presumably used in lieu of `isassigned`, but then the assertion fail in tests.
> RelSeries: remove useless "isdefined" test

- src/generic/AbsSeries.jl
- src/generic/Fraction.jl
- src/generic/LaurentSeries.jl
- src/generic/Matrix.jl
- src/generic/NCPoly.jl
- src/generic/Poly.jl
- src/generic/RelSeries.jl
- src/generic/Residue.jl
- src/generic/ResidueField.jl
This removes the docstrings looking like `"+(a,b): return a+b"`.
Related to #535.
> remove redundant docstrings for * ^ + -

- src/AbstractAlgebra.jl
- src/Generic.jl
- src/WeakValueDict.jl
- src/generic/GenericTypes.jl
- test/AbstractAlgebra-test.jl
- test/WeakValueDict-test.jl
- test/generic/AbsSeries-test.jl
- test/generic/Fraction-test.jl
- test/generic/FreeModule-test.jl
- test/generic/LaurentPoly-test.jl
- test/generic/LaurentSeries-test.jl
- test/generic/MPoly-test.jl
- test/generic/NCPoly-test.jl
- test/generic/Poly-test.jl
- test/generic/PuiseuxSeries-test.jl
- test/generic/RelSeries-test.jl
- test/generic/Residue-test.jl
- test/generic/ResidueField-test.jl
- test/generic/SparsePoly-test.jl
This is the `WeakValueDict` silbling of `Base.WeakKeyDict`, which is exactly what we need for caching. This seems to work pretty well.
```julia
julia> using Revise, AbstractAlgebra         
julia> for s in 'a':'z'                      
Qx, x = PolynomialRing(QQ, s)       
end                                   
julia> length(AbstractAlgebra.Generic.PolyID)
26                                           
julia> GC.gc()                               
julia> length(AbstractAlgebra.Generic.PolyID)
0                                            
```
I put it in AA mainly to test it. This will be fine if we only need it in AA/Nemo/Hecke/Oscar/Singular. I don't know if we need it for GAP.jl or Polymake.jl though. Otherwise it would have to go in a small separate package, which would also be no …
> Implement WeakValueDict and use it for caching

- src/generic/AbsSeries.jl
- src/generic/Misc/Series.jl
- src/generic/RelSeries.jl
- test/generic/AbsSeries-test.jl
- test/generic/RelSeries-test.jl
Nemo passes with these changes.
Running Hecke tests now. @thofma @fieker the Hecke tests currently take about half an hour to run on my poor laptop. Some individual tests take 5 or 10 minutes to run. Are these testing functionality not tested by the shorter tests, or are they mainly there to keep an eye on performance regressions?
If the latter, is there any possibility of wrapping them in a test for HECKE_TESTLONG or so in ENV? Only you guys actually know what timings to look out for, I presume, as these would be machine specific.
> Move implementation of inv for series over fields to generic, add tests.

- .github/workflows/CI.yml
Test all versions on linux. Test 1.0, 1.5, 1.6-nightly and nightly on macOS and Windows. This is in preparation for the upcoming downstream testing.﻿
> Cut down the number of CI jobs

- src/generic/Misc/Poly.jl
- src/generic/Poly.jl
- src/julia/Integer.jl
- test/generic/Poly-test.jl
Let me know if you want these three documented.
Note that there were bugs in these, so Hecke tests may now fail as I have corrected their implementation.
I also sped up the third function using unsafe operators.
> Move divhigh, mulhigh_n and divexact_low from Misc. Add tests.

- src/generic/MPoly.jl
Not the end of the world. The deprecation did its job.
> Fix a missing coeffs -> coefficients replacement.

- .github/workflows/oscar.yml
- OscarCI.toml
This should run just two jobs (and will not create a separate axis per package):
- `<matching>`: for each of the repos look up a corresponding branch and use master otherwise
- `release`: run with the latest released version of the packages (version as chosen by Pkg.jl)
We could add some explicit extra combinations via `[include]`.
> OscarCI: update workflow, use global axis to reduce combinations

- docs/src/mpolynomial.md
- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
This should work for Nemo (and Singular.jl once imported/exported). As it has to do it the generic way using iterators it will be slow for Nemo, but I will write a faster version over there.
In the meantime, this should be ok as is, I believe.
Fixes #822 (tail was dealt with in the relevant PR)
> Add trailing_coefficient for MPoly.

- src/generic/AbsSeries.jl
- src/generic/RelSeries.jl
- test/generic/RelSeries-test.jl
Speeds up relative and absolute series generic exp over rings by:
* computing derivative once to avoid allocations
* using delayed reduction (where available)
Note that this may be breaking, as fit! is not available for Nemo polynomial rings and derivative uses it. I will make a PR to fix this soon.
> Use derivative to cut down number of allocations.

- src/generic/Poly.jl
I've tested with Nemo, but Hecke master isn't using AA master, so that's as far as I can test.
Technically this can't break anything upstream, but there's always a possibility something bizarre happens.
Fixes #833
> Don't use .coeffs member in PolyElem functions. Fixes #833

- src/generic/RelSeries.jl
This is a small fix required for the absolute series deduplication in Nemo.
> Allow modulus to work over finite fields.

- docs/make.jl
- docs/src/misc.md
- src/PrettyPrinting.jl
- test/PrettyPrinting-test.jl
This was requested on the mailing list and something I also needed a few times. With the printer refactoring this is now very easy:
> Add an option to disable latex output in jupyter

- docs/src/series_rings.md
- src/AbstractAlgebra.jl
- src/generic/AbsSeries.jl
- src/generic/RelSeries.jl
- test/generic/AbsSeries-test.jl
- test/generic/RelSeries-test.jl
I had a lot of trouble deciding what precision and valuation the resulting series should have. As the series returned is going to be zero, I decided the precision should equal the valuation, so only one should be supplied.
But that still left two possibilities for this precision:
* set it to the max_precision of the parent of the input series
* set it to the precision of the input series
I decided to go with the former, as the other parameters (when specified) change some feature of the parent ring and otherwise use the values from the parent ring.
However, if this convention turns out to not be useful in practice, we can certainly revisit this.
I've also slipped constructors for abs_series and rel_series, without creating the parent ring, and abs_series_type and rel_series_type into this …
> Implement similar and zero for absolute and relative series.

- src/generic/Matrix.jl
Fixes #664 
I tested by hand that it works fine for Nemo matrices over GF(7) as per the ticket. I can't really test that here, but the change is not exactly complex.
> Make randmat_with_rank apply to other matrix types, e.g. Nemo matrices.

- docs/src/residue_rings.md
- src/generic/AbsSeries.jl
- src/generic/Poly.jl
- src/generic/RelSeries.jl
- src/generic/Residue.jl
- test/generic/Residue-test.jl
Fixes #629 
This could be controversial. Let me know if you want this. If so, I'll also add mod, rem, div, divrem, mulmod and powmod for Flint poly rings in Nemo so that this works with Nemo.
I've made this work simply by lifting the restriction to a field as the coefficient ring of mod, rem, divrem, div, mulmod and powmod for univariate polynomials. I didn't lift the restriction for invmod, gcdinv, gcdx, as this of course leads to incorrect results as it is not a Euclidean domain. This also means divexact is not available for residue rings of polynomial rings when not over a field (I'm not sure what it could actually do generically if I did implement that). This is the case even though divexact is part of our ring interface. (I could have it raise a not implemented error, but Julia will …
> Univariate polynomial residue rings

- docs/src/types.md
This fixes #872 according to this page [1] on the GitHub blog.
[1] https://github.blog/2016-12-05-relative-links-for-github-pages/
> Correct relative link for visualization.

- src/PrettyPrinting.jl
- test/PrettyPrinting-test.jl
a + b - c instead of a + (b - c) in some cases.
> fix some extra parentheses

- src/Poly.jl
- src/generic/Misc/Poly.jl
Fixes #886 
This was barely worth doing. It gets rid of the extra allocations due to collect (though there may still be an allocation for Take and Reverse, I'm not sure), but it's clear that supporting Julia iterators in general is not worth it. They are just not a useful construct in the language due to the lack of multiple inheritance and due to iterators themselves being very, very limited.
> Allow use of reverse(PolyCoeffs) and take(reverse(PolyCoeffs)) and make use of this in polynomial_to_power_sums.

- src/NCPoly.jl
- src/Poly.jl
- src/generic/AbsMSeries.jl
- src/julia/GF.jl
- test/generic/AbsMSeries-test.jl
- test/generic/AbsSeries-test.jl
- test/generic/FunctionField-test.jl
- test/generic/LaurentSeries-test.jl
- test/generic/MPoly-test.jl
- test/generic/NCPoly-test.jl
- test/generic/Poly-test.jl
- test/generic/PuiseuxSeries-test.jl
- test/generic/RelSeries-test.jl
- test/julia/GFElem-test.jl
I think the convention in julia is to treat 0^0 as 1, which is not the case for the following
```julia
julia> GF(3)()^0
0
julia> PolynomialRing(MatrixAlgebra(QQ, 2), "y")[1]()^0
0
julia> R, x = QQ["x"]; ResidueField(R, x^2+1)()^0
0
```
This PR fixes these cases, and also removes all the senseless checks in the test files.
(For `AbsMSeries`, the `isequal` function checks using `poly(x) == poly(y)`, which might not be truncated to the given precision and will cause the tests to fail.)
> Make 0^0=1

- src/AbstractAlgebra.jl
First, actually honor the argument `M` instead of hardcoding `Main`.
Next, avoid `Meta.parse` and exception handling. Before this PR:
julia> @time AbstractAlgebra.find_name(R)
0.000165 seconds (44 allocations: 2.031 KiB)
Afterwards:
julia> @time AbstractAlgebra.find_name(R)
0.000011 seconds (4 allocations: 288 bytes)
> Improve find_name

- src/AbstractAlgebra.jl
Alternatively, one try to fix it; to get the package version, one could adapt this code from Oscar.jl:
```
if VERSION < v"1.4"
pkgdir(m::Core.Module) = abspath(Base.pathof(Base.moduleroot(m)), "..", "..")
end
pkgproject(m::Core.Module) = Pkg.Operations.read_project(Pkg.Types.projectfile_path(pkgdir(m)))
pkgversion(m::Core.Module) = pkgproject(m).version
const VERSION_NUMBER = pkgversion(@__MODULE__)
```
But then it'll still die because fail with `UndefVarError: LibGit2 not defined`, but of course that, too, could be fixed.
CC @thofma
> Remove outdated versioninfo()

- README.md
- docs/src/ytabs.md
In doc URLs, `latest` changed to `dev` some time ago.
> Update doc links, add link to stable docs

- src/Poly.jl
- test/generic/Poly-test.jl
Fixes #897 
Note that there is a corresponding Nemo fix required for this to pass.
This is the most conservative fix I can come up with which fixes 897 and does what we all agree on.
If this is accepted I will do the same thing for power series.
The system is still inconsistent, but we all agree the current functionality is not useful. The principle here is:
* If the polynomial being created would have lived in the exact same (AbstractAlgebra/Nemo) ring (if parents had been cached), then "zero" and "similar" steal the parent from the original polynomial rather than create a new one.
At least this fix is not inconsistent with matrices, given that parents are not stored in the objects anyway. We probably should use @rfourquet's parent comparison idea there instead.
I should point out that I …
> Make Generic.Poly similar and zero steal parents if appropriate.

- src/Rings.jl
- src/generic/FunctionField.jl
- src/generic/GenericTypes.jl
- src/generic/LaurentPoly.jl
- src/generic/Poly.jl
- src/generic/RationalFunctionField.jl
- test/generic/FunctionField-test.jl
- test/generic/LaurentPoly-test.jl
- test/generic/RationalFunctionField-test.jl
Before
```julia
julia> using Revise, AbstractAlgebra                                                                                                                
julia> Qt, t = RationalFunctionField(QQ, "t");
julia> Qtx, x = PolynomialRing(Qt, "x");
julia> F, a = FunctionField(x^6+27*t^2+108*t+108, "a");
julia> FT, T = PolynomialRing(F, "T");
julia> T + a
ERROR: MethodError: no method matching Rational{BigInt}(::AbstractAlgebra.Generic.Poly{AbstractAlgebra.Generic.FunctionFieldElem{Rational{BigInt}}})
Closest candidates are:
(::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
(::Type{T})(::Base.TwicePrecision) where T<:Number at twiceprecision.jl:243
(::Type{T})(::Complex) where T<:Real at complex.jl:37
```
The problem is that the method …
> Remove wrong ad hoc methods

- src/RelSeries.jl
- test/generic/RelSeries-test.jl
> Fix bug in zero relative series to power zero.

- src/Matrix.jl
The `combinations` function was very slow...
```julia
julia> @btime AbstractAlgebra.combinations(10, 3); # before
32.587 μs (996 allocations: 92.59 KiB)
julia> @btime AbstractAlgebra.combinations(10, 3); # after
5.971 μs (129 allocations: 15.47 KiB)
julia> @btime collect(Combinatorics.combinations(1:10, 3));
5.783 μs (242 allocations: 18.05 KiB)
```
The output order of the combinations is same as before.
> Improve combinations

- src/Residue.jl
- src/generic/MatrixAlgebra.jl
- src/julia/Float.jl
- test/AbstractAlgebra-test.jl
- test/Rings-conformance-tests.jl
- test/Rings-test.jl
- test/julia/Floats-test.jl
- test/julia/GFElem-test.jl
- test/julia/Integers-test.jl
- test/julia/Rationals-test.jl
Just looking for comments. @fingolfin @wbhart
~~I like the approach of the user providing explicit elements, which can hit coner cases, and also gives you the elem_type.~~
It uses functions now.
Will work on matrix, and poly tests soon.
Currently these rings do not pass, but the other ones work well.
```
zz
RDF
RealField
ResidueRing(ZZ, 1)
```
> add conformance tests

- Project.toml
Not sure why, but documentation build was failing here: https://github.com/Nemocas/AbstractAlgebra.jl/runs/3201646567?check_suite_focus=true
This seems to fix it.
> Fix documentation and bump version

- src/AbstractAlgebra.jl
Functions such as inv, sqrt, log, exp, etc. have special local versions which we use internally, which conflict with the Base definition.
This PR adds those to the relevant import/export exclude lists.
Fixes https://github.com/Nemocas/Nemo.jl/issues/1038
> Add all functions with special local versions to import/export lists

- docs/src/poly_interface.md
- test/Rings-conformance-tests.jl
The ring conformance tests added by @tthsqe12 some time ago already tested for this in a randomized fashion. When I tried to use the conformance tests in Nemo, I found that not all polynomial implementations support this. But I think they should. So, as a first step, this PR documents the expected behavior. I will submit further PRs to adjust implementations in Nemo and possibly elsewhere to conform to this.
> Document constructing polynomials from empty vectors

- src/julia/Integer.jl
- src/julia/Rational.jl
This is also part of PR #995, but that PR produces failures in CI that I can't reproduce. So let's see if this commit on its own causes issues or not, that might help narrow it down.
> Add support for `rand(QQ, -big(5):big(5))`

- .github/workflows/CI.yml
Also instead of excluding most mac/Windows jobs, just explicitly
write down those we want.
Also drop testing on 1.1 and 1.2 (it's unlikely a regression only
occurs there, and even if, it is unlikely anybody still is using those)
> CI: test against Julia 1.7

- src/generic/FunctionField.jl
- test/generic/FunctionField-test.jl
Remove an ad hoc method which is too general. Let the promotion
system do its job.
> Fix ad hoc divexact for polynomials over function fields

- src/AbstractAlgebra.jl
- src/Residue.jl
- src/error.jl
- test/generic/Residue-test.jl
If it were up to me, I would get rid of the non-informative `DivideError` and throw an `ImpossibleInverse` instead. Suppose you are doing polynomial arithmetic. Would you want to see
```julia
julia> ZZx,x = ZZ["x"]; x//(x-x)
ERROR: DivideError: integer division error
```
? It doesn't make much sense to me, but here we are.
> start using NotInvertibleError

- docs/src/euclidean_interface.md
- src/Poly.jl
- src/generic/MPoly.jl
- test/Rings-conformance-tests.jl
This hard and fast definition of `lcm` was already violated both inside and outside of AA. @wbhart I can't imagine this pr breaking anything, but please confirm that this is reasonable.
> relax lcm definition

- src/Matrix.jl
- test/generic/Matrix-test.jl
I would hate to document the * operation, but the matrix or vector is zero-extended in the case of a dimension mismatch. This is more useful than throwing an error :).
> add matrix vector products

- docs/src/univpolynomial.md
The same heading already exists in the multivariate docs, which broke the reference to the heading "Generic sparse distributed multivariable polynomial types" in the Oscar docs.
We could work around this in another way preserving the heading, but I think it makes sense to sprinkle in the word "universal".
> Adjust heading in universal polynomial ring docs

- src/AbstractAlgebra.jl
- src/WeakValueDict.jl
- test/WeakValueDict-test.jl
I am not interested ATM in making a WeakValueDict, partly because it has many superfluous requirements, partly because I don't like locks in single-threaded code, and mainly because I don't see how it can coherently fulfill the dictionary interface.
I have not observed the AA or Nemo test code failing with this WeakValueCache, but to be fair, I did not observed the WeakValueDict failing on the same machine.
> add WeakValueCache and fix WeakValueDict

- src/generic/YoungTabs.jl
- test/generic/YoungTabs-test.jl
Otherwise this falls back to the generic `AbstractArray` method which produces a `Matrix`. I wasn't quite sure whether the partition should be copied as well, but decided against that for now, since a tableau is treated like a matrix, so only the entries are really supposed to be copied, not the shape.
> implement `copy` for young tableaux

- src/Map.jl
- src/generic/GenericTypes.jl
- test/generic/Map-test.jl
The restriction on the signature of the compose functions does not
work together with the design of module morphisms. Here is an example:
```julia
julia> using Revise, AbstractAlgebra
julia> V = FreeModule(QQ, 2)
Vector space of dimension 2 over Rationals
julia> f = AbstractAlgebra.ModuleHomomorphism(V, V, QQ[1 1; 1 2])
Module homomorphism with
Domain: V
Codomain: V
julia> g = identity_map(V)
Identity map with
Domain:
=======
Vector space of dimension 2 over Rationals
julia> f * g
ERROR: MethodError: no method matching compose(::AbstractAlgebra.Generic.ModuleHomomorphism{Rational{BigInt}}, ::AbstractAlgebra.Generic.IdentityMap{AbstractAlgebra.Generic.FreeModule{Rational{BigInt}}})
Closest candidates are:
compose(::Map{D, D, var"#s451", T} where {T, var"#s451"<:IdentityMap}, ::Map{D, D, …
```
> Fix compose signature

- docs/src/rational.md
- src/julia/Integer.jl
- src/julia/Rational.jl
- test/julia/Rationals-test.jl
* Add root, ispower and ispower_with_root for rationals
* Make docstrings for root, sqrt and friends more generic (so they apply to other rings as well)
* Remove docstrings for sqrt and friends in Rational.jl (rely on the more generic docstrings)
> Rational root functions

- src/julia/Float.jl
- src/julia/Integer.jl
- src/julia/Rational.jl
- test/generic/Poly-test.jl
Fixes #1077 
Fixes #1075 (both issues)
Turning off mutation for Julia types appears to be necessary for correctness (see #1077), as Julia doesn't make the same assumptions as us that new objects are created that don't alias even in part when arithmetic operations are performed, e.g. "-a" for a Rational{BigInt} keeps the same denominator identically.
Test code now takes about 9 minutes to run, which seems acceptable.
> Remove mutation for julia types

- src/AbstractAlgebra.jl
Don't export `package_handle` and `Array`. Also, turn `package_handle`
into a `Ref{Int}`.
Before this patch:
julia> @btime get_handle()
1.982 ns (0 allocations: 0 bytes)
500503
After this patch:
julia> @btime C.get_handle()
1.391 ns (0 allocations: 0 bytes)
500503
Not that this matters, as this function is normally only called a few times ;-)
> Optimize get_handle, remove some exports

- docs/src/matrix.md
- src/Matrix.jl
- test/generic/Matrix-test.jl
There are two versions, one which accepts a ring and a vector of Julia matrices and another which accepts a vector of AA matrices.
> Implement block_diagonal_matrix constructors

- src/Attributes.jl
- test/Attributes-test.jl
- Unify attribute tests
- Remove type restriction for `f` in `get_attribute!(f,G,attr)`:
Many "callable" things are not of type `Function`, including type constructors. Being able to pass such non-function callables can be handy.
> Yet more attributes related tweaks

- src/Attributes.jl
- test/Attributes-test.jl
Also improve docstring for `get_attribute!(f::Function, G::Any, attr::Symbol)`
by mentioning that it is meant for use with `do` blocks
> Add get_attribute(f::Function, G::Any, attr::Symbol)

- src/Attributes.jl
- test/Attributes-test.jl
The old approach using `Base.return_types` was fatally flawed:
we can't always correctly deduce the return type of code at the
time it is defined, as e.g. it might reference methods that are
not even defined yet.
So we remove this code. Instead, an optional first argument is
added to the `@attr` macro which now is used to specify a
type assertion on the type of the attribute.
> Revise @attr return type handling

- docs/src/euclidean_interface.md
- docs/src/polynomial.md
- src/Poly.jl
- src/algorithms/GenericFunctions.jl
- src/generic/Misc/Localization.jl
This way, not all euclidean ring implementations need to repeat this.
Also, by inserting this as docstrings into the manual, these functions
become findable via the search feature of the online manual.
Also improve some of the docstrings, and remove some redundant docstrings.
BTW, what does "loosely reduced" means in the docstrings for `gcdx`?
> Use docstrings for euclidean ring interface

- src/Attributes.jl
- test/Attributes-test.jl
- document that attribute storage is always enabled for singleton types
- allow applying `@attributes` to singleton types (it simply does nothing)
- actually perform tests with singleton types again (tests were accidentally
disabled in a previous patch)
> Improve `@attributes` for singleton types

- src/Attributes.jl
- src/Matrix.jl
The first line should be indented with 4 spaces, to mark it as a Markdown codeblock
> Fix two docstrings

- docs/src/field.md
- docs/src/field_interface.md
- docs/src/fraction.md
- docs/src/mpolynomial.md
- docs/src/polynomial.md
- docs/src/residue.md
- docs/src/ring_interface.md
- docs/src/series.md
- src/AbsMSeries.jl
- src/NCRings.jl
- test/Rings-conformance-tests.jl
Fixes #993 
This may cause some rings to no longer function when characteristic is used in generic code. But so far current tests pass (after modifying conformance tests to ignore the exception.
> Make characteristic raise an exception if it cannot be computed easily.

- src/generic/LaurentMPoly.jl
- test/generic/LaurentMPoly-test.jl
- Allow arbitrary coefficients in the build context
- Add constant_coefficient
@tthsqe12 I do not need to `_normalize` in the `constant_coefficient` function, right?
> Improvements for LaurentMPoly

- docs/src/matrix.md
- docs/src/matrix_introduction.md
- src/Matrix.jl
- src/MatrixAlgebra.jl
- src/NCPoly.jl
- src/NCRings.jl
- src/Rings.jl
- src/generic/GenericTypes.jl
- src/generic/Matrix.jl
- src/generic/MatrixAlgebra.jl
- test/generic/Matrix-test.jl
- test/generic/MatrixAlgebra-test.jl
> Enable matrix algebras over noncommutative rings

- src/Poly.jl
see also https://github.com/Nemocas/Nemo.jl/issues/1304
though I think `set_length!(poly, n)` and `normalise(poly, n)` should be part of an official interface since they are used on the abstract type.
> The parent constructor already does normalization

- docs/src/euclidean_interface.md
- src/algorithms/GenericFunctions.jl
- test/Rings-conformance-tests.jl
- test/julia/Rationals-test.jl
closes #1165 
while I was at it, I also added the corresponding functions for `lcm`.
If somebody knows how to change the documentation to one box containing all three same-named methods instead of the current three separate boxes, that would be appreciated.
> add gcd and lcm versions for AbstractVector and vararg

- src/AbstractAlgebra.jl
- src/AliasMacro.jl
- src/Aliases.jl
Also export them explicitly (before @alias did it for us), and use @alias for
our LinearAlgebra aliases, too (makes it easier to find them by grepping)
CC @HechtiDerLachs this is what I was talking about
> Declare is_one, is_zero as early as possible

- docs/src/mpolynomial.md
- src/MPoly.jl
- test/generic/MPoly-test.jl
Given an MPolyElem f and a list of some of the variables in f,
deflate(f, vars, shift, defl) returns a polynomial obtained by deflating
only the specified variables. vars can be an array of either generators
or variable indices. shift and defl var arrays of integers, one for each
of the specified variables. inflate(f, vars, shift, defl) is defined
similarly.
Example:
```
using AbstractAlgebra
R, (x,y,z) = PolynomialRing(ZZ, ["x", "y", "z"])
g = (2*x^2 + y*x + 3*y^2*z - 4*x^3 + x*z - 5*z^2)^2
g0 = coeff(g, [y], [0])
g1 = deflate(g - g0, [y], [1], [1])
@assert g == g0 + y * g1 == g0 + inflate(g1, [y], [1], [1])
```
For some code I am trying to write, some functions only use operations like those in the examples. I assume that inflate and deflate is faster than multiplying and dividing with …
> Deflate and inflate exponents of only some variables

- src/WeakValueDict.jl
Note that Base.Callable is an undocumented alias for Union{Function, Type}.
And of course in principle more things could be callable, but so far we only
ever use either functions or types for these arguments, so this seems like a
fair compromise
> Reduce method invalidations for get/get!

- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
`divrem(a, [])` should just return `[], a` like it does for fmpq-mpoly's in Nemo.
> Catch empty array of divisors in `divrem`

- src/Matrix.jl
- src/PrettyPrinting.jl
Here is the rational:
We have to be careful for jupyter. When jupyter prints an object x through
IJulia.jl, it collects sprint(show, m, x) for all m in
[ "text/plain", "text/html", "text/latex" ... ]
and then picks one according to some precedence. If there is a string for
either "text/html" or "text/latex", it will *not* use "text/plain". But
"text/plain" is the only thing which will trigger rendering using a monospace
font (hence it will look like "code"). This explains why all julia base
objects are printed using monospace: none of these objects has print methods
for text/html or text/latex.
The challenge for us is that we always want to define text/latex and
text/html methods. This has the disadvantage that if
get_html_as_latex()== false, then our objects will print their ordinary …
> Make jupyter printing less ugly

- src/WeakValueDict.jl
- src/generic/AbsMSeries.jl
- src/generic/UnivPoly.jl
I didn't check, but unbound type parameters often cause performance issues, so this isn't merely cosmetic.
FTR, there's a relevant function in Test in stdlib for checking this stuff:
https://docs.julialang.org/en/v1/stdlib/Test/#Test.detect_unbound_args
> remove unbound type parameters

- src/algorithms/MPolyEvaluate.jl
- test/algorithms/MPolyEvaluate-test.jl
This isn't HechtiDerLach's original horner_lex code since I couldn't figure out why that code wasn't doing an iterated univariate horner. This code here has a better bound on the recursion depth (nvars instead of total degree), and it is about the same speed as the non-recursive horner while having sub-quadratic overhead in the worst case.
> add evaluate_horner_lex

- src/AliasMacro.jl
- test/AbstractAlgebra-test.jl
The `@alias` macro is supposed to set a special docstring for aliases which indicate what they are an alias for. This was broken at some point, but because the tests were not run, nobody noticed.
I noticed this a few weeks ago, and was confused why the test I wrote for this didn't trigger... well, because I was / am stupid *sigh*.
I also discussed this with a few people (in Blaubeuren? perhaps with @fieker or @thofma ?!) Anyway, in that discussion, some people said they actually thought the current behavior (were the alias gets the same docstring as the original symbol) was intentional and perhaps even better. So of course we could also discuss dropping this behavior and the test instead. However, my rationale for having a different docstring for the alias is that this makes it clearer …
> Fix `@alias` macro and add its tests to the test suite

- src/Attributes.jl
When using Revise and editing a function using @attr, one previously got warning like this one:
┌ Warning: skipping callee ##compute_elements#699 (called by false) due to UndefVarError(Symbol("#3732#3733"))
└ @ LoweredCodeUtils ~/.julia/packages/LoweredCodeUtils/0oUEK/src/signatures.jl:292
This patch avoids this, and perhaps also is useful for debugging the underlying code of a function decorated by `@attr`
CC @simonbrandhorst
> Change @attr to use fixed symbols for compute functions

- docs/src/ideal.md
- src/AbstractTypes.jl
- src/Ideal.jl
- src/generic/Ideal.jl
- test/generic/Ideal-test.jl
- Remove the `Ideal{T}(...)` methods. This is an abstract type, so these constructors make little sense.
- Introduce the `ideal` function without methods.
- Add fallback methods for `x::RingElement * R::Ring` and the other way around. (These are prone to ambiguities, so handle them once and for all here).
CC: @fingolfin @tthsqe12 
The plan is that individual rings implement `ideal(::MySpecialRing, y)` for whatever `y` they want. The downstream ideal types can be subtyped as `MySpecialIdeal <: Ideal{fmpz}`.
> Make ideal related things play nicer with downstream

- src/PrettyPrinting.jl
In the pretty printing code, there are many invocations of ==(::Any,::Symbol)
due to the left side not being inferable (be it due to `@nospecialize`, or
because `obj.args[1]` can be anything, or other reasons).
To give an idea of the effect, consider the following timings, made with the
latest Julia master branch, which now contains code for caching compiled code.
I've benchmarked a simple Hecke computation, with and without loading CxxWrap:
Without CxxWrap:
julia> using Hecke ; @time @eval maximal_order(quadratic_field(-3)[1]);
0.029069 seconds (74.71 k allocations: 4.971 MiB, 121.79% compilation time)
With CxxWrap but without this patch:
julia> using Hecke ; using CxxWrap ; @time @eval maximal_order(quadratic_field(-3)[1]);
3.239503 seconds (3.83 M allocations: 255.878 MiB, 1.47% gc …
> Avoid method invalidations when CxxWrap is loaded

- src/Poly.jl
This is for https://github.com/Nemocas/Nemo.jl/blob/master/benchmarks/fateman.jl. It seems this is a benchmark we brag about, so we should not make it slower and slower.
Before:
```
benchmark_fateman ...   2.114 s (594448 allocations: 43.20 MiB)
```
After:
```
benchmark_fateman ...   1.171 s (150346 allocations: 11.95 MiB)
```
@tthsqe12 do you know a better way to fix this regression?
> Disable karatsuba by default

- src/MPoly.jl
(which has been removed in pull request #1259)
> do not export the now undefined `coeffs`

- src/Matrix.jl
- src/NCRings.jl
- test/generic/MatrixAlgebra-test.jl
Most `jldoctest` examples in AbstractAlgebra.jl had already an explicit `setup = :(using AbstractAlgebra)`.
Now I have added this to the few occurrences where this was missing.
Note that the AbstractAlgebra.jl doctests are run also when the documentation of Nemo.jl gets built,
and setting `:(using AbstractAlgebra)` in a global `DocMeta.setdocmeta!` call inside Nemo.jl's `docs/make.jl` is not suitable because Nemo.jl carefully avoids calling `using AbstractAlgebra`. (One runs into problems when one tries to use `ZZ` in a jldoctest for Nemo.jl after calling `using AbstractAlgebra` because both packages export `ZZ`. Up to now this was no problem because there were no jldoctests of this kind in Nemo.jl.)
> added `setup` to `jldoctest`

- .github/workflows/CI.yml
The same as https://github.com/oscar-system/Oscar.jl/pull/1957, i.e. the tests should now fail once a deprecation warning is encountered.
cc @thofma @fieker @fingolfin
> Fail CI on deprecation warning

- docs/make.jl
(This is a follow-up of #1261.)
> do not call `DocMeta.setdocmeta!` in AbstractAlgebra

- src/Matrix.jl
Work around timholy/Revise.jl#735 so revising `Matrix.jl` works.
> Change syntax to make Revise.jl happy

- src/UnivPoly.jl
- src/generic/GenericTypes.jl
- src/generic/UnivPoly.jl
Not all multivariate polynomial rings can be constructed with
zero indeterminants (e.g. all ring coming from flint).
Thus we always use a generic polynomial ring underpinning the
universal one.
Fixes https://github.com/oscar-system/Oscar.jl/issues/2076
I cannot test it here.
> Fix bug in universal polynomial ring

- src/NCRings.jl
- src/Rings.jl
- test/Rings-conformance-tests.jl
... as discussed in https://github.com/oscar-system/Oscar.jl/issues/1618
TODO:
> Allow `/` as shortcut for `divexact`

- docs/src/ncpolynomial.md
- docs/src/poly_interface.md
- docs/src/polynomial.md
- src/AbstractAlgebra.jl
- src/MPoly.jl
- src/NCPoly.jl
- src/Poly.jl
- src/generic/GenericTypes.jl
- src/generic/MPoly.jl
- src/generic/NCPoly.jl
- src/generic/Poly.jl
- test/generic/MPoly-test.jl
- test/generic/NCPoly-test.jl
- test/generic/Poly-test.jl
The AbstractAlgebra side to solve Nemocas/Nemo.jl#1405. Introduces new functions `polynomial_ring_only`, `polynomial_ring_type`, and `mpolynomial_ring_type`.
> Move `polynomial_ring` code to abstract level

- src/generic/FreeAssAlgebra.jl
- test/generic/FreeAssAlgebra-test.jl
> add `ngens` for `FreeAssAlgebra`

- src/Attributes.jl
- test/Attributes-test.jl
Fixes #1296.
I spared the docstring, since it is just a copy of `get_attribute(::Any, ::Symbol, ::Any)` and the user should not have to care about this ambiguity.
@thofma
> make `get_attribute` unambiguous

- src/MPoly.jl
- src/NCPoly.jl
- test/generic/MPoly-test.jl
- test/generic/NCPoly-test.jl
Discussed in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1282#discussion_r1140590392. Adds methods `mpoly_type(x)`, `mpoly_ring_type(x)`, `dense_poly_type(x)`, `poly_ring_type(x)` which do the same as those functions called with `typeof(x)` instead.
I am inclined to metaprogram this
```julia
macro type_function(f::Symbol) quote
$(esc(f))(x) = $(esc(f))(typeof(x))
$(esc(f))(::Type{T}) = throw(MethodError($(esc(f)), (T,)))
end end
@type_function mpoly_type
@type_function elem_type
...
```
But we can also go with the manually added methods.
> Add `*poly*_type` methods for elements

- src/AbstractAlgebra.jl
- src/MPoly.jl
- src/NCPoly.jl
- test/generic/NCPoly-test.jl
... for consistency. We can rename it again in the future, but then together with `dense_poly_type`.
Resolves #1289
CC @mgkurtz
> Rename poly_ring_type -> dense_poly_ring_type

- docs/src/map_interface.md
- src/AbstractAlgebra.jl
- src/Generic.jl
- src/Map.jl
- src/generic/GenericTypes.jl
- src/generic/Map.jl
- src/generic/MapCache.jl
- src/generic/ModuleHomomorphism.jl
- test/generic/Map-test.jl
- test/generic/ModuleHomomorphism-test.jl
I just came across this branch, which I wrote almost exactly a year ago but then never submitted. I tried to understand the `Map` code and `get_field` really took me some time to understand, and then determine that it seems mostly (?) useless? Anyway, I felt I should just submit this now, either we use it or we discard it *shrug*.
Here is the description from the original commit message:
There were meant to provide additional generality to maps in Oscar, and allow writing "more generic" code. In practice, as far as I can tell no public code outside of AbstractAlgebra ever used them. As to writing generic code: the idea, as I understand it (which may be wrong) seems to be that certain generic map implementation can use it to forward "arbitrary" map functionality, even beyond what they were …
> Remove `get_field` and `set_field!`

- src/MPoly.jl
- src/NCPoly.jl
They all now accept both rings, ring elements, or their types. Also fix the docstrings.
Motivated by https://github.com/Nemocas/Nemo.jl/issues/1423.
> Enhance *poly*_type methods

- src/error.jl
There are actually many other `mutable struct` which I think
could be changed to `struct`...
> No need for our exceptions to be mutable

- docs/src/matrix_interface.md
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
Before it only supported rings (documented) and ring element types
(undocumented) as argument. Now it also supports ring types and ring
elements as arguments.
> Make dense_matrix_type more consistent

- src/MPoly.jl
- src/NCPoly.jl
- src/fundamental_interface.jl
- src/generic/UnivPoly.jl
This also fixes the doctests, which failed due to a reference to a `polynomial_ring(R::Ring, n::Int, s::VarName)` which did not exist before this patch.
> Fix doctests & get rid of VarNameNonSymbol

- src/Poly.jl
The `0` and `1` should be `zero` and `one` of the base ring instead. This was fixed in a special case, and could be fixed in general:
https://github.com/oscar-system/Oscar.jl/blob/6abf75f599c1f81abb17a2325e569cb6fcadee25/src/AlgebraicGeometry/TropicalGeometry/semiring.jl#L465-L468
> Fix `zero` and `one for `PolyRing`

- docs/src/direct_sum.md
- src/generic/AbsMSeries.jl
- src/generic/DirectSum.jl
- src/generic/FreeAssAlgebra.jl
- src/generic/FreeModule.jl
- src/generic/InvariantFactorDecomposition.jl
- src/generic/MPoly.jl
- src/generic/QuotientModule.jl
- src/generic/Submodule.jl
- src/generic/UnivPoly.jl
- test/generic/AbsMSeries-test.jl
- test/generic/DirectSum-test.jl
- test/generic/FreeAssAlgebra-test.jl
- test/generic/MPoly-test.jl
- test/generic/Module-test.jl
- test/generic/QuotientModule-test.jl
- test/generic/Submodule-test.jl
- test/generic/UnivPoly-test.jl
Also use @boundscheck annotation.
Note that I deliberately did not use `BoundsError` as upon closer inspection it does not seem to really apply in this situation and the error message is not any more helpful either. However, it could be changed later again if someone has a different preference, or we could even introduce our own exception type...
Resolves half of #571 by @ulthiel
> Add bounds checks to all gen methods

- src/generic/FreeModule.jl
- src/generic/GenericTypes.jl
Note that you can still modify the content of a `FreeModuleElem`, as that just requires access to the the underlying vector, which is still perfectly mutable. So this is mostly an optimization: Julia is now free to stack allocate instances or completely elide them.
> Turn `FreeModuleElem` into a `struct`

- test/Rings-conformance-tests.jl
Some packages do not import these functions and so they are not
available.
> Adjust conformance test

- src/Matrix.jl
- test/generic/Matrix-test.jl
This enables '@view m[1,:]' to work.
Resolves #1218
> Extend view support to match supported matrix indexing

- src/AbstractAlgebra.jl
- test/generic/AbsMSeries-test.jl
- test/generic/DirectSum-test.jl
- test/generic/FreeAssAlgebra-test.jl
- test/generic/MPoly-test.jl
- test/generic/Module-test.jl
- test/generic/QuotientModule-test.jl
- test/generic/Submodule-test.jl
- test/generic/UnivPoly-test.jl
As requested by @ulthiel in #571. Together with PR #1331 this resolves #571, *if* we choose to merge it.
This one might be a bit controversial, so paging @fieker @thofma @simonbrandhorst @ThomasBreuer and anyone else who might care about such things.
> Allow `S[i]` as shorthand for `gen(S,i)` for all parents `S`

- src/AbstractAlgebra.jl
to use:
DocMeta.setdocmeta!(Oscar, :DocTestSetup, :(using Oscar; Oscar.AbstractAlgebra.set_current_module(@__MODULE__)); recursive = true)
or equivalent. This stores the module handle in AA, hence we can use it.
> provide infrastructure to do the name printing

- src/julia/GF.jl
Resolves oscar-system/Oscar.jl#866.
> Fix docstring for `lift(::GFElem)`

- docs/src/perm.md
- docs/src/ring.md
- docs/src/ring_interface.md
- src/MatrixAlgebra.jl
- src/Residue.jl
- src/generic/AbsSeries.jl
- src/generic/LaurentSeries.jl
- src/generic/Matrix.jl
- src/generic/Misc/Localization.jl
- src/generic/NCPoly.jl
- src/generic/PermGroups.jl
- src/generic/Poly.jl
- src/generic/PuiseuxSeries.jl
- src/generic/RelSeries.jl
- src/generic/UnivPoly.jl
- src/julia/GF.jl
- test/algorithms/GenericFunctions-test.jl
All implementations now pass the `IdDict` along.
Fixed some references to `deepcopy_internal` in the docs.
Closes #906.
> Make `deepcopy_internal` consistent

- Project.toml
- docs/src/matrix.md
- docs/src/matrix_algebras.md
- docs/src/mpolynomial.md
- docs/src/ncpolynomial.md
- src/MatrixAlgebra.jl
- src/PrettyPrinting.jl
- src/fundamental_interface.jl
- test/PrettyPrinting-test.jl
There was a bug in handling newio = pretty(IOContext(pretty(io))),
since newio did not preserve the state of io. One fix would be
be to specialize IOCustom(io::IOContext{<:IOCustom}), but the
easiest thing is to make pretty(x::IOContext{<:IOCustom}) = x
since we consider IOCustom already prettified.
> Another fix for the printing

- src/Matrix.jl
- test/generic/Matrix-test.jl
Most notably, this allows to write `A[axes(B)...] = B`.
> Support `AbstractUnitRange` in `setindex!`

- src/PrettyPrinting.jl
The Julia library already provides `convert(::Type{T},x::T)=x`.
Reduces the number of invalidations from 607 to 511 in this snippet:
using SnoopCompileCore
invalidations = @snoopr using AbstractAlgebra;
using SnoopCompile
length(uinvalidated(invalidations))
> Avoid some method invalidations

- src/AbstractAlgebra.jl
`NCRingElem` gets already exported, then why not `NCRing`?
> Export `NCRing`

- src/AbstractAlgebra.jl
- test/generic/Matrix-test.jl
This makes matrix literals (like `QQ[1 2; 3 4]`) more flexible. See the new tests for examples.
> Let matrix literals actually concatenate

- src/generic/PermGroups.jl
- test/generic/Perm-test.jl
First off, these cause invalidations. Secondly, doing this kind of
conversion implicitly also seems semantically dubious.
This is a breaking change.
> Avoid implicit conversion of Perm{T} to Vector{T}

- src/generic/FreeModule.jl
way more efficient if the vector is not created at all ...
> make gen for vector spaces faster

- src/Matrix.jl
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
Resolves #1406.
I furthermore moved linear indexing next to the corresponding functions for cartesian indexing.
> Add `setindex!` for `MatElem` with linear indexing

- src/julia/Rational.jl
These are already provided by Julia
> Remove gcd and gcdx for Rational{<:Integer}

- .github/workflows/CI.yml
https://github.com/oscar-system/Oscar.jl/pull/2770 for AbstractAlgebra. This is recommended by the [readme](https://github.com/julia-actions/julia-buildpkg#usage).
> CI: use concrete action version

- docs/src/rand.md
- src/AbsMSeries.jl
- src/Fraction.jl
- src/FreeAssAlgebra.jl
- src/LaurentMPoly.jl
- src/MPoly.jl
- src/Matrix.jl
- src/MatrixAlgebra.jl
- src/Module.jl
- src/NCPoly.jl
- src/Poly.jl
- src/RelSeries.jl
- src/Residue.jl
- src/ResidueField.jl
- src/generic/FunctionField.jl
- src/generic/LaurentPoly.jl
- src/generic/LaurentSeries.jl
- src/generic/NumberField.jl
- src/generic/RationalFunctionField.jl
- src/generic/TotalFraction.jl
- src/generic/UnivPoly.jl
Self-recursion disables optimizations and can lead to `@inferred` reporting failures as a result, even when `@code_warntype` seemingly suggests that the code being called is type stable.
As an example, without this patch the following reports failure
using AbstractAlgebra, Test
using AbstractAlgebra.RandomExtensions: RandomExtensions, make
R = polynomial_ring(polynomial_ring(QQ,:x1)[1], :y)[1]
@inferred make(R, 0:0, 1:10, -10:10)
> Avoid self-recursion in RandomExtensions.make

- src/AbstractAlgebra.jl
This will fix a failure in https://github.com/thofma/Hecke.jl/pull/1206.
And I see no reason why this functionality should be restricted to the commutative world.
> Widen `zeros` to `NCRing`

- docs/src/matrix.md
- src/Matrix.jl
- src/NemoStuff.jl
- fix their docstrings to say `transpose` instead of `tr` (which is the trace)
- align the implementations
- ensure they are both applicable to `MatrixElem` with no restrictions
- remove redundant `is_symmetric(M::MatElem`) method
> Tweak is_symmetric and is_skew_symmetric

- src/AbstractAlgebra.jl
- src/error.jl
Nothing uses it. Nemo defines its own version of this.
> Remove error_dim_negative

- src/AbstractAlgebra.jl
- src/NemoStuff.jl
- export `is_positive`
- drop `isnegative` alias
- add more generic methods for both
I realized that the `is_positive(::Integer)` method was the only mention of `is_positive` in `AbstractAlgebra.jl` at all. So this at least makes the situation "symmetric"
An alternative would be just move this back to Nemo -- I am not sure how useful it is to have it here, with no use cases and documentation.
CC @fieker @lgoettgens
> Adjustments for is_negative and is_positive

- src/NemoStuff.jl
I could not find any uses downstream. And it is just completely weird and unintuitive to have. So I propose to remove it (if the OscarCI does not complain).
Edit: this is breaking
> Remove weird `:` method

- docs/src/functional_map.md
- docs/src/map_interface.md
- src/Map.jl
- src/generic/Map.jl
Also include jldoctests for each, and fix a bug in the printing of IdentityMap instances.
> Add docstrings for various map construction functions

- docs/src/matrix.md
- src/Matrix.jl
- src/NemoStuff.jl
Moves some stuff from `NemoStuff.jl` to `Matrix.jl` and makes that code consistent with already existing code. Adapts docstrings and makes them a bit more consistent.
> Some matrix function cleanup

- src/PrettyPrinting.jl
Also clarify write_indent code, it is always called on an IOCustom instance
> Add missing _unwrap call in Dedent handler

- src/Matrix.jl
This lets one call the other. Should we leave this like this or deprecate one of them?
> Remove duplicate implementation of block diag matrices

- Project.toml
- src/Matrix.jl
It appears that #1438 was in fact breaking for https://github.com/thofma/Hecke.jl/blob/75dbabf5ab7c863bba8fc233a85583b674211554/src/QuadForm/Quad/ZGenus.jl#L1600 in Hecke, as it removed the possibility to use `diagonal_matrix(::NCRing, ::Vector{<:MatElem})` with empty list of blocks.
Thus, currently, Hecke master's CI is broken (but there have been no runs yet). I thus would like to have this patch here released shortly.
> Fix one `diagonal_matrix` dispatch

- src/AbstractAlgebra.jl
- src/PrettyPrinting.jl
If we print a name, we don't want to change its capitalization.
I don't have a good test case here, but it fixes this bug in Oscar:
julia> F = cyclotomic_field(3)[1];
julia> vector_space(Fun, 6)
Vector space of dimension 6 over f
Resolves #1449
> Use LowerCaseOff in @show_name

- docs/Project.toml
- docs/make.jl
Note that the equivalent of `strict = true` is now the default.
> Switch docs to build using Documenter 1.0

- src/PrettyPrinting.jl
- test/PrettyPrinting-test.jl
These are useful for writing tests also for downstream packages.
This is a tiny subset of #1450 which however is not breaking (unlike that PR) and thus could be merged quickly and put into a new release, so that other packages can make use of them for writing tests.
> Move some helpers into AbstractAlgebra.PrettyPrinting

- test/generic/Ideal-test.jl
- test/generic/LaurentMPoly-test.jl
<s>Depending on the random seed, this test could take forever resp. run out of memory. Restrict it to fewer tests for now.
This may not be enough, though; we may need to set a fixed RNG seed in this testset, or just replace the "random" ideals by fixed ones which are known to not exhibit the bad performance.</s>
Don't use random examples in the multivariate case, as some of these can
lead to *really* horribly bad runtimes. Instead use a fixed list of
examples.
For the univariate cases and the ideals in Z, I did not change anything
so far, as those should not suffer from the same problems (famous last
words...)
CC @benlorenz
> Modify testset "Generic.Ideal.addition"

- docs/src/matrix.md
- src/AbstractAlgebra.jl
- src/Matrix.jl
- test/Matrix-test.jl
... as alias for `LinearAlgebra.isdiag` -- and replacement for the Nemo method.
> Add `is_diagonal(A::MatrixElem)`

- src/NCRings.jl
- src/Rings.jl
... to match those of their counterpart functions `divexact_right` and
`divexact_left`: it seems more natural to expect to be able to divide
a ring element *by* floats or rationals than the other way around.
> Change signature of / and \ methods

- src/generic/AbsMSeries.jl
Provide `power_series_ring(R, prec, s; weights)` and let the old method call the new one. I factored this out of #1360.
> Refactor `power_series_ring(R, weights, prec, s)`

- src/generic/AbsMSeries.jl
This function is type unstable, so at least internal code is better off not calling it.
See also [this discussion](https://github.com/Nemocas/AbstractAlgebra.jl/pull/1478#discussion_r1375747337).
> Replace multiple calls to precision(::AbsMSeries)

- src/PrettyPrinting.jl
There is already a type assertion inside the code, so no
need for this conversion inducing type declaration.
> Remove redundant 'convert' invocation

- src/AbstractAlgebra.jl
- src/Ideal.jl
- src/algorithms/MPolyNested.jl
- src/generic/GenericTypes.jl
- test/Rings-test.jl
- test/algorithms/MPolyNested-test.jl
- add `@attributes` mutable struct MPolyRing
- generic `iszero` for ideals
- Dan's code for gcd, factor for nested polynomial rings
> Move stuff from Oscar to AbstractAlgebra

- src/AbstractAlgebra.jl
- src/PrettyPrinting.jl
Some time ago `with_unicode` was improved in Oscar, apply that here.
> Improve with_unicode

- src/Matrix.jl
Continuation of https://github.com/Nemocas/AbstractAlgebra.jl/pull/1443.
Changed functions:
- handling `CartesianIndex`
- `setindex!`
- trace `tr`
- row and column permutations and swaps
- adjusted docstrings of earlier changed functions
> Enable more functionality for matrices over NCRing

- src/Aliases.jl
- src/Generic.jl
- src/generic/Misc/Localization.jl
- src/generic/PuiseuxSeries.jl
This way any access to them trigger a depwarning (if those are enabled,
as they are in our CI).
This is a first step to eventually removing these aliases.
> Replace many @aliases by @deprecate_binding

- README.md
The list of people who supposedly develop AbstractAlgebra "currently" was not quite accurate. I tried to adjust this a bit.
Feedback welcome! In particular I really don't want to misrepresent anything or diminish someones contributions or whatever.
The justification for the order of the "original developers" is also unclear to me, nor whether it should be considered complete; I simply did not touch it.
See also https://github.com/Nemocas/Nemo.jl/pull/1589
> README.md: corrected developers list

- Project.toml
- src/MPoly.jl
- src/misc/VarNames.jl
- test/generic/MPoly-test.jl
We don't `VarName` as part of `VarNAmes`. This removes a few call variations
of `polynomial_ring` etc., that we did not actually agree to put in (they were
likely a leftover of an earlier iteration of the recent varname changes).
This allows us to remove some `polynomial_ring` methods that were added purely
for disambiguation, but which caused a type instability in `polynomial_ring`
in Julia 1.6 (but not in 1.9).
> Restrict VarNames union type

- src/AbstractAlgebra.jl
- src/Matrix-Strassen.jl
- src/Matrix.jl
- src/generic/Matrix.jl
- test/Matrix-test.jl
but what do we want?
we have
solve_triu       for fields            Ax = b
rings (this PR)   Ax = b
solve_triu_left      rings (this PR)   xA = b
All three accept large "b", ie. can solve multiple equations in one.
However, they require "A" to be non-singular square
We also have
can_solve_left_reduced_triu
which can deal with arbitrary matrices "A" in rref, but can only deal with single row "b"
solve_triu for fields also has flags for the diagonal being 1
if b and A are square, this is asymptotically not optimal as it will be a n^3/2 algo
I can add test - if we want this "interface"
Note: for triangular, one cannot transpose to reduce one case to the
other
Note: in serious use, should also be supplemented by special
implementations in Nemo/ Flint for nmod and/or ZZ
and friends
> add some triangular ring solver and asymptotically fast generics

- Project.toml
- src/misc/VarNames.jl
- test/generic/MPoly-test.jl
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1518 and adapts tests for checking type interference.
MPoly tests succeed locally. Let's wait for ci for the other types that use the varname stuff.
> Fix interference for polynomial_ring constructor

- src/Fraction.jl
- test/generic/Fraction-test.jl
> Add `vars` for rational functions of multivariate polynomials

- docs/src/ring.md
- src/Factor.jl
- src/algorithms/GenericFunctions.jl
Also clarify their docstrings and those of factor and factor_squarefree; and use these docstrings in the manual.
Note that Oscar already has such a generic `is_irreducible` method which however is mathematically wrong; https://github.com/oscar-system/Oscar.jl/pull/2995 contains a fixed version. But with this PR we could eventually remove it there.
Resolves #1496
The "definition" for "square free" given there only (or rather: at best, if at all) makes sense for unique factorization domains. I am happy to use a different one, if someone can provide one. But we definitely should clarify what it is supposed to mean one way or another.
I would include a test, except I don't think we have any `factor` or `factor_squarefree` methods in AA, so tests could only happen in Nemo?
> Add generic `is_irreducible`, `is_squarefree` methods

- Project.toml
- docs/src/ring.md
Oscar includes the AA manual into its own manual. Unfortunatel the
'factor' function in Oscar is different from that in AA (it gets replace
by Hecke), and the alternative 'factor' has no method matching the
signature here.
To unbreak building of the Oscar docs, revert the 'factor' documentation
to a handcrafted block instead of using @docs.
> Unbreak Oscar docs

- src/AbstractAlgebra.jl
Nemo skips them separately (see https://github.com/Nemocas/Nemo.jl/blob/37b49d9dc0df0d6d8dfa9ede3b4d12b64d92fa56/src/Nemo.jl#L60-L61). This change makes it possible to refactor that away in Nemo.
> Adapt import_exclude list

- test/generic/LaurentMPoly-test.jl
This reverts commit 72ce576375506501997bdf825e4efd9415ac7a8d.
For now this will likely just result in the 1.10 CI tests failing. We should re-run the tests here once 1.10 has reverted those changes (I assumes that means 1.10-beta4 or 1.10-rc1 or so). I am mostly opening this PR now so that we won't forget later.
> Revert GC HACK

- docs/src/integer.md
- docs/src/rational.md
- src/AbstractAlgebra.jl
- src/Aliases.jl
- src/julia/Integer.jl
- src/julia/Rational.jl
- test/julia/Integers-test.jl
- test/julia/Rationals-test.jl
Reverts Nemocas/AbstractAlgebra.jl#1535.
Second shot of https://github.com/Nemocas/AbstractAlgebra.jl/pull/1529, now marked as a breaking change.
> Revert "Revert "Streamline `is_power` for julia and AA types...""

- src/Fields.jl
- src/julia/Rational.jl
I'd rather have an error than to get a wrong characteristic by accident because someone forgot to implement a method.
This might be breaking if there are ring implementations that relied on it.
> Don't default characteristic of fields to 0

- Project.toml
- src/AbsSeries.jl
- src/MPoly.jl
- src/Matrix.jl
- src/NCPoly.jl
- src/NemoStuff.jl
- src/Poly.jl
- src/generic/FreeAssAlgebra.jl
- src/generic/LaurentMPoly.jl
- src/generic/LaurentPoly.jl
- src/generic/LaurentSeries.jl
- src/generic/PuiseuxSeries.jl
- src/generic/UnivPoly.jl
Julia has a heuristic, to pass through arguments of type `Type` or
`Function`, which results in degraded performance and inference problems.
Avoid this by introducing auxilliary type parameter.
> fix: force specialization for map arguments

- src/broadcasting.jl
- test/broadcasting-test.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/3204.
I must admit that I don't understand some parts of the broadcasting code, but broadcasting trivially over `Ref`s should always be safe.
The mwe from https://github.com/oscar-system/Oscar.jl/issues/3204 has been added as a test.
> Fix broadcasting of `evaluate`

- docs/src/residue.md
- src/Generic.jl
- src/NemoStuff.jl
- src/Residue.jl
- src/ResidueField.jl
- src/generic/GenericTypes.jl
- src/generic/NumberField.jl
- src/generic/Residue.jl
- src/generic/ResidueField.jl
- test/generic/LaurentMPoly-test.jl
- test/generic/Residue-test.jl
- test/generic/ResidueField-test.jl
- test/generic/UnivPoly-test.jl
These implementations only make sense if the underyling ring is an
Euclidean ring. Thus we rename the types to `EuclideanRingResidueRing`
and `EuclideanRingResidueField` respectively.
> feat: Rename Generic.[ResidueRing|ResidueField]

- Project.toml
- docs/src/residue.md
- src/AbstractAlgebra.jl
- src/NemoStuff.jl
- src/Residue.jl
- src/ResidueField.jl
- test/generic/LaurentMPoly-test.jl
- test/generic/Residue-test.jl
- test/generic/ResidueField-test.jl
- test/generic/UnivPoly-test.jl
We should keep it consistent between parents and their elems. I noticed this in downstream tests, so it would be great to fix it while still adapting downstream.
> Export EuclideanRingResidue*Elem as well

- src/generic/Residue.jl
- Some types in Nemo only do lift properly
- Sanity check for image function
> feat: minor improvements for residue maps

- docs/src/linear_solving.md
- src/Solve.jl
- test/Solve-test.jl
Adds `kernel` to the `Solve` submodule (for the moment just a wrapper of `nullspace`).
@thofma the HackMD says we want the left kernel. In consistency with `solve`, I made the right kernel the default.
> New generic `kernel`

- Project.toml
- src/AbstractAlgebra.jl
- src/Groups.jl
- test/Groups-conformance-tests.jl
So downstream only needs to implement `div_left/right` if they want to change stuff, and not the `/` or `\` functions. (to be consistent with `^` and `conj`)
> Adapt Groups interface for `div_left` and `div_right`

- Project.toml
- src/AbstractAlgebra.jl
- test/Groups-conformance-tests.jl
These function used to be there in GroupsCore, ignored from AA to Hecke, and Oscar implemented them for GAPGroups and exported. https://github.com/Nemocas/AbstractAlgebra.jl/pull/1528 moved the implementation from GroupsCore to AA.
When I removed the silly overloads in Oscar in https://github.com/oscar-system/Oscar.jl/pull/3231 with the intent to use the fallback in AA, the Oscar Aqua tests complain about functions not being there. Since many similar functions are already exported I think these should propagate to Oscar as well (where they already have been exported for a long time).
> Export mutating functions from Groups interface

- src/AbstractAlgebra.jl
Necessary for https://github.com/thofma/Hecke.jl/pull/1370 (assuming we really want to go down this rabbit hole).
> Add `::MIME"text/plain"` versions of `show_special` macros

- Project.toml
- src/generic/MPoly.jl
> fix: use is_one instead of == 1

- .gitignore
- src/PrettyPrinting.jl
To be able to disable unicode for tests/doctests etc., see e.g. https://github.com/oscar-system/Oscar.jl/pull/3271
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1588.
> Overhaul Unicode preferences

- docs/src/misc.md
- src/AbstractAlgebra.jl
- src/PrettyPrinting.jl
- test/PrettyPrinting-test.jl
Inspired by https://github.com/oscar-system/Oscar.jl/pull/3288#issuecomment-1921290702.
This PR contains the following minor changes:
- Document the behavior of the special printing macros and their helper functions.
- Introduce `get_name` as an alternative to `find_name` in downstream packages, that does the same steps as the printing to find a name (e.g. first look into attribute storage before finding a new name in the global namespace). `find_name` should get changed to being private once all call-sites use `get_name`.
One fundamental change/question is the following:
It was motivated by https://github.com/oscar-system/Oscar.jl/pull/3288#issuecomment-1921280610, where we tried to enable `@show_name` for multivariate polynomial rings. The issue was that rings print the name that was …
> Overhaul special printing macros

- Project.toml
To be released once https://github.com/Nemocas/AbstractAlgebra.jl/pull/1586 and https://github.com/Nemocas/AbstractAlgebra.jl/pull/1594 are merged.
> chore: bump to 0.37.5

- Project.toml
- docs/src/linear_solving.md
- src/Solve.jl
- test/Solve-test.jl
I learned that `nullspace(::RingElement)` returns a "rational nullspace" EXCEPT for `ZZMatrix`.
The output of `Solve.kernel` is still not exactly the same as of `kernel`; I will probably adjust some more.
> Further solving related adjustments

- test/Groups-conformance-tests.jl
- test/generic/PermGroupAPI-test.jl
As already pointed out by @fingolfin in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1528#discussion_r1424740679, this leads to `InexactError`s.
When trying to enable the group conformance tests for Weyl groups in https://github.com/oscar-system/Oscar.jl/pull/3351 I stumbled over this and thus made this quick PR.
> Allow Groups of order > 2^15 in conformance test

- src/Matrix.jl
- src/generic/GenericTypes.jl
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
- make A[i::Int, js::Array] return a Vector and support views
> feat: fix generalized indexing

- src/AbstractAlgebra.jl
I assume we also want to export `solve_init` and `can_solve_with_solution_and_kernel`
> Add two exports

- Project.toml
- docs/src/polynomial.md
- src/AbsSeries.jl
- src/Poly.jl
- src/RelSeries.jl
- src/polysubst.jl
- test/generic/AbsSeries-test.jl
- test/generic/Poly-test.jl
- test/generic/RelSeries-test.jl
- First step at resolving https://github.com/oscar-system/Oscar.jl/issues/690
- Introduce a mandatory keyword argument for compose(f, g)
and add a hint for f(g)/g(f) syntax.
[breaking]
Edit: I threw a dice and decided that
- `compose(f, g; side = :right)` means `f(g)`,
- `compose(g, f; side = :left)` means `g(f)`.
Obviously I don't have a strong opinion.
> fix: make compose do what it says

- docs/src/free_associative_algebra.md
fixed the Example not displaying correctly
_edit:_ at the bottom of https://nemocas.github.io/AbstractAlgebra.jl/dev/free_associative_algebra/#Groebner-bases
> Fixed jldoctest of groebner_basis section in free_associative_algebra.md

- docs/src/misc.md
- src/AbstractAlgebra.jl
- src/PrettyPrinting.jl
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1594 defined a new interface but kept everything non-breaking to ease the adaption.
Oscar and Hecke have been adapted in https://github.com/oscar-system/Oscar.jl/pull/3327 and https://github.com/thofma/Hecke.jl/pull/1393 to use the new interface.
This is now the following change, that is technically breaking, but shouldn't need any changes in Hecke and Oscar (let this be verified by CI) due to the earlier adaption.
> Cleanup after name printing changes

- Project.toml
I already merged something breaking (didn't notice the label), so we should bump the version immediately.
> chore: Bump to 0.40.0-DEV

- src/Matrix.jl
- src/Solve.jl
- test/Solve-test.jl
- the syntax foo(R::Ring, M::Mat) is too valuable to use it only as a
"shortcut" for foo(R.(M))
> fix: remove some unncessary kernel method

- src/AbstractAlgebra.jl
- src/fundamental_interface.jl
- src/generic/DirectSum.jl
not optimal implementation of  the maps, and no change to the (soon to be illegal) behviour of direct_sum
> add most of the direct_sum new stuff

- src/AbstractAlgebra.jl
- src/Generic.jl
- src/generic/YoungTabs.jl
Found using the great new tool [ericphanson/ExplicitImports.jl](https://github.com/ericphanson/ExplicitImports.jl)
New version of https://github.com/Nemocas/AbstractAlgebra.jl/pull/1622
> Consolidate some `using` statements and make them explicit

- src/misc/VarNames.jl
- test/generic/MPoly-test.jl
Resolves #1631 (was easier than I feared :-) )
> Fix handling of kwargs in @polynomial_ring

- src/misc/VarNames.jl
- test/generic/MPoly-test.jl
See the new tests for examples now working.
> Fix kwargs and scoping in `@polynomial_ring`

- Project.toml
- src/PrettyPrinting.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/3515.
The field `io.printed` should keep track of the width already printed in the current line (indentation is not tracked here).
In two places, a newline char was printed, but the field was not reset to 0.
There is unfortunately no way to test this in a doctest, as all of this linebreaking business is skipped for doctests.
In local testing, this both resolves the MWE in https://github.com/oscar-system/Oscar.jl/issues/3515#issuecomment-1997453137, and the printing issues with `MonomialBasis` (at least those that I could observe locally).
cc @benlorenz @lkastner
> Fix handling of line break characters in a string in pretty printing

- docs/make.jl
- docs/src/euclidean_interface.md
- docs/src/integer.md
- src/AbstractAlgebra.jl
- src/Rings.jl
- src/julia/Integer.jl
- test/Rings-test.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/3093
> Add `is_associated`

- src/AbstractAlgebra.jl
- src/Aliases.jl
- src/Groups.jl
- test/Groups-conformance-tests.jl
I think `is_finiteorder` is against the naming conventions? While I'm at it: shouldn't it be `has_finite_order`?
> `is_finiteorder` -> `is_finite_order`

- src/Matrix.jl
- src/Module.jl
- test/generic/Matrix-test.jl
Removes `_can_solve_left_reduced_triu` by using a solve context in the one place it is used.
I assume we want to get rid of the function completely; otherwise I can also revert the second commit.
> Remove `_can_solve_left_reduced_triu`

- src/Fraction.jl
- src/generic/Fraction.jl
The moved methods were defined for arguments of an *abstract* type
but accessed specific struct fields, which doesn't make sense in
this setting. So instead move them to the file defining the concrete
type, and change them to apply to just that.
> Move FracField methods for concrete type to right place

- src/julia/JuliaTypes.jl
Builds upon #1659 to provide thread-safety by default.
My tentative search shows 1 place with the same issue potentially:
https://github.com/Nemocas/AbstractAlgebra.jl/blob/17e182aaf7c482d59abde4afb9ca0ba1eaa25852/src/generic/Misc/Localization.jl#L39
> Use CacheDictType for caching GF(p)

- src/generic/GenericTypes.jl
- src/generic/Misc/Localization.jl
- test/algorithms/GenericFunctions-test.jl
There is kind of an expectation for parent types to be attribute
storing, and I see no strong reason why any of these shouldn't just do
it by default. If no attributes are used, the overhead is minimal
anyway.
> Make all (?) ring types attribute storing

- src/generic/UnivPoly.jl
- test/generic/UnivPoly-test.jl
Consider the following example:
```julia
julia> R = universal_polynomial_ring(QQ)
Universal Polynomial Ring over Rationals
julia> x = gen(R, "x")
x
julia> S, y = polynomial_ring(R, "y")
(Univariate polynomial ring in y over universal Polynomial Ring over Rationals, y)
julia> (x+1)*y
x + 1*y
```
The missing parentheses in the last output are clearly misleading, and create an ambiguity between `(x+1)*y` and `x+1*y`.
This PR addresses this issue by replacing the printing of univ polys by using the expressify output of the underlying MPolyRing. This then fixes the recursive call of expressify on the coefficients of the polyring `S`.
Let's hope that this behavior is not doctested downstream and can be released quickly.
> Add missing parentheses in stacked printing of univpolys

- src/Matrix.jl
- test/Matrix-test.jl
These methods should never be called because there are `vcat(::MatrixElem{T}...) where T <: NCRingElement` and `hcat(::MatrixElem{T}...) where T <: NCRingElement`.
If they are called, then the matrices don't have the same base ring, so the result is not well-defined.
This breaks OSCAR 1.0.0, but not OSCAR 1.0.1.
> Remove `vcat(::MatElem, ::MatElem)` and `hcat(::MatElem, ::MatElem)`

- src/fundamental_interface.jl
This is mostly about making `base_ring_type` more convenient to use. 
Found this this while cleaning up old branches in my local clone, apparently I made it last November, but never submitted... Huh. Not sure why, perhaps because I started to question whether it should really apply to elements, too... *shrug* you tell me what you think, I guess.
> Uniform `base_ring_type` method

- src/Map.jl
- src/Matrix.jl
- src/Module.jl
- src/exports.jl
- src/generic/DirectSum.jl
- src/generic/FreeModule.jl
- src/generic/Map.jl
- src/generic/Misc/Poly.jl
- src/generic/ModuleHomomorphism.jl
- src/generic/exports.jl
The idea is to add this code to AbstractAlgebra.jl, and then to remove it from Oscar.jl.
Once we agree what shall be really added here, tests and documentation have to be added.
(I am quite sure that I have put certain parts into the wrong files, and that some functions have to be changed.)
> move code from `Oscar.jl/experimental/GModule/Misc.jl` here

- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
Part of https://github.com/Nemocas/Nemo.jl/pull/1729 to address the issue described in https://github.com/Nemocas/Nemo.jl/pull/1711.
> Add dim check to `matrix_space`

- src/AbsMSeries.jl
- src/Fraction.jl
- src/FreeAssAlgebra.jl
- src/LaurentMPoly.jl
- src/MPoly.jl
- src/Map.jl
- src/MatRing.jl
- src/NCPoly.jl
- src/Poly.jl
- src/RelSeries.jl
- src/Residue.jl
- src/ResidueField.jl
- src/algorithms/LaurentPoly.jl
- src/generic/DirectSum.jl
- src/generic/FunctionField.jl
- src/generic/InvariantFactorDecomposition.jl
- src/generic/LaurentSeries.jl
- src/generic/Misc/Localization.jl
- src/generic/PuiseuxSeries.jl
- src/generic/QuotientModule.jl
- src/generic/RationalFunctionField.jl
- src/generic/SparsePoly.jl
- src/generic/TotalFraction.jl
- src/generic/UnivPoly.jl
- src/generic/imports.jl
- src/julia/GF.jl
This includes and hence closes #1628
It will most likely fail tests as I did not yet have a chance to adjust any tests, but I wanted to get this on here before I forget it *again*
> Use `@show_name`, `@show_special` for all (?) parent show methods

- src/AbsMSeries.jl
- src/RelSeries.jl
- src/generic/LaurentSeries.jl
- test/generic/AbsMSeries-test.jl
- test/generic/AbsSeries-test.jl
- test/generic/FunctionField-test.jl
- test/generic/LaurentSeries-test.jl
- test/generic/PuiseuxSeries-test.jl
- test/generic/RationalFunctionField-test.jl
- test/generic/RelSeries-test.jl
- test/generic/SparsePoly-test.jl
These signatures were wrong but since we run no conformance tests on
these rings we never noticed...
<s>
Of course there should also be tests. But guess what, rings that
we did not conformance tests are not conformant... plus one has
to add `test_elem` methods in order to run the conformance tests.
So let's get this fix out now and add tests later.</s>
UPDATE: Actually it wasn't so bad to get the conformance tests added, I just made a silly mistake earlier. So I added those tests now and a few extra ones as bonus. Problems only pop up with the "recursive" conformance tests, which I therefore skipped. (Several ring types still are not tested for conformance at all.)
> Make base_ring_type work for (M)SeriesRing

- src/exports.jl
- src/generic/GenericTypes.jl
- src/generic/SparsePoly.jl
- test/generic/SparsePoly-test.jl
Contains and thus closes https://github.com/Nemocas/AbstractAlgebra.jl/pull/1691.
Contents:
- Fixes two of the three issues experienced in https://github.com/Nemocas/AbstractAlgebra.jl/issues/1689
- Fixes some ambiguities that arise in running the tests
- Removes the export `SparsePolynomialRing` (technically breaking)
> Fixes for SparsePolyRing

- docs/src/misc.md
- src/Map.jl
- src/PrettyPrinting.jl
- test/PrettyPrinting-test.jl
- test/generic/Map-test.jl
- test/generic/MapWithInverse-test.jl
- test/generic/ModuleHomomorphism-test.jl
We retain the name  `:supercompact` for the IOContext property for now to maximize compatibility while some of our downstream packages still use it.
Moreover, we retain the `PrettyPrinting.supercompact` helper for now as it is used by Nemo.
Also, while replacing a reference to `supercompact` in a comment to the detailed `show` method for maps, I've decided to fully rewrite that comment.
There is one issue with the new `PrettyPrinting.terse` helper which replaces `PrettyPrinting.supercompact`: it has the same name as the function we use to activate terse mode for IO objects... the only impact of this I can think of is that we can't use it to "terse print" IO objects -- which seems perfectly fine by me given that this function is only meant for use in test suites anyway, and we don't have …
> Replace most remaining supercompact uses by terse

- docs/src/matrix_interface.md
- src/Matrix.jl
- src/generic/GenericTypes.jl
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
> Make Generic.MatSpace truly generic

- src/Matrix.jl
- test/generic/Matrix-test.jl
This is a useful "inverse" for `dense_matrix_type`.
> Add base_ring_type for MatrixElem; fix it for MatSpace

- src/generic/ModuleHomomorphism.jl
- test/generic/ModuleHomomorphism-test.jl
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1712.
I added an example to the test that failed before and now returns something sensible.
The main problem is that over QQ every module is free, and thus the code in ModuleIsomorphism handling relations never gets run. Over ZZ, not every random matrix gives an iso, so I fixed some example instead.
> Fix ModuleIsomorphism

- src/Groups.jl
- test/Groups-conformance-tests.jl
Replaces and thus closes https://github.com/oscar-system/Oscar.jl/pull/3787.
We already have the analogous thing for NCRingElem, so I see no reason not to have it for GroupElem.
cc @ThomasBreuer
> Make GroupElem broadcastable

- src/AbstractAlgebra.jl
- src/Fraction.jl
- src/Module.jl
- src/NCPoly.jl
- src/NCRings.jl
- src/Poly.jl
- src/RelSeries.jl
- src/algorithms/LaurentPoly.jl
- src/generic/AbsMSeries.jl
- src/generic/FreeAssAlgebra.jl
- src/generic/FreeModule.jl
- src/generic/FunctionField.jl
- src/generic/LaurentSeries.jl
- src/generic/MPoly.jl
- src/generic/Misc/Localization.jl
- src/generic/PuiseuxSeries.jl
- src/generic/RationalFunctionField.jl
- src/generic/TotalFraction.jl
- src/generic/UnivPoly.jl
- src/julia/GF.jl
Of course some types may still wish to override this, but most `check_parent` implementations really followed the exact same pattern...
> Add and use generic `check_parent` method

- src/MPoly.jl
Analogue to PolyRing(), this one doesn't seem to be used at all
> Remove MPolyRing(R::Ring, n::Int)

- src/Matrix.jl
- test/generic/Matrix-test.jl
Not sure whether the implementation is okay, but it would be very useful if `matrix(_, _)` would accept a `MatSpaceElem` as second argument:
```
using AbstractAlgebra
R,_ = polynomial_ring(QQ,2)
M = [one(R) one(R); one(R) one(R)]
M = matrix(R,M)
M = matrix(R,M) # this currently does not work
```
I generally convert all matrices into `MatSpaceElem`s to avoid problems such as  https://github.com/Nemocas/AbstractAlgebra.jl/issues/1730,  and `matrix(_, _)` is my go-to method for doing so.
> new: matrix(::NCRing, ::MatSpaceElem)

- src/Map.jl
- src/Matrix.jl
- src/ModuleHomomorphism.jl
- src/generic/FactoredFraction.jl
- src/generic/Matrix.jl
- src/julia/Integer.jl
Some refactoring found using ExplicitImports.jl
In most cases, the removed qualification was used inconsistently in the surrounding code anyway.
> Remove self-qualified accesses

- src/MatrixNormalForms.jl
- src/Residue.jl
- src/exports.jl
- test/MatrixNormalForms-test.jl
I copied over the generic Howell form from Hecke.
This requires the operations 'ann', 'gcdex' and 'quo' as Storjohann calls them; I implemented these under the names `annihilator`, `gcdex` and `_div` for `ResElem.jl`. Better names are welcome.
I also added some lines that normalize the pivot elements with the `canonical_unit` to make the Howell form unique; is that correct?
> Howell form

- src/generic/UnivPoly.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/3921.
The problem here seems to be that https://github.com/Nemocas/AbstractAlgebra.jl/blob/d6cf779c45185cf354fd048210e87af41f05a460/src/generic/UnivPoly.jl#L903 uses `polynomial_ring` (and thus possibly creates some Nemo mpoly ring), but the rest of the implementation of `UniversalPolyRing` directly calls `Generic.MPoly`.
I verified manually that the problem described in https://github.com/oscar-system/Oscar.jl/issues/3921 no longer exists in a session with both AA and Oscar loaded. I cannot add tests here, as there is no issue with AA alone.
> Fix `change_base_ring` for `UnivPoly` when Nemo is loaded

- src/Fraction.jl
- src/generic/TotalFraction.jl
- delay computation of a gcd until it really is needed in `addeq!`
and `add!` methods for `FracElem` (thus matching what the `+` and `-`
methods already are doing)
- reorder some code in `*` and `mul!` methods for `TotFrac` (thus matching
the order in the `+`, `add!` etc. methods)
> Some trivial cleanup

- src/NCRings.jl
- src/fundamental_interface.jl
- src/generic/UnivPoly.jl
- src/julia/Float.jl
- src/julia/Integer.jl
Also replace three methods which are made redundant by this default method.
But with this patch, about 50 such methods can be deleted in Nemo, which is my main motivation for adding this here.
> Add default implementation for addeq! delegating to add!

- src/Residue.jl
- src/ResidueField.jl
Also remove check_parent_type.
Previously, we allowed binary operations involving two ResElem instances of *different type*, with the type of the result depending on the argument order. For example, this (requires https://github.com/Nemocas/Nemo.jl/pull/1819):
julia> using Nemo
julia> R = quo(ZZ, 2)[1]
Integers modulo 2
julia> S = Nemo.AbstractAlgebra.EuclideanRingResidueRing{UInt}(UInt(2))
Residue ring of integers modulo 2
julia> typeof(R)
zzModRing
julia> typeof(S)
EuclideanRingResidueRing{UInt64}
julia> S(1) + R(1)
0
julia> typeof(S(1) + R(1))
EuclideanRingResidueRingElem{UInt64}
julia> typeof(R(1) + S(1))
zzModRingElem
But this seems questionable at best. I think we are better of forbidding this -- which this PR effectively does.
However, I am sure people had a reason to add the code …
> Revise check_parent for ResElem and ResFieldElem

- docs/src/ring_interface.md
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1742.
There was an import missing, and `base_ring_type` should be implemented by parents and not elements.
> Fix example of Ring interface

- src/julia/Float.jl
- src/julia/Integer.jl
> Make global variables const

- src/Fraction.jl
- test/generic/Fraction-test.jl
... which MPolyRing and UniversalPolyRing use to allow specifying a list of variable indices followed by a list of values.
Requested by @SoongNoonien
> Enhance evaluate for FracElem to support 3-arg variants

- src/Solve.jl
- src/exports.jl
- test/Solve-test.jl
So far this does not change the functionality. I open this pull request already now to discuss names and the design.
I will add the new Howell form to the system and try to clean up more of the `_can_solve...` methods in `src/Matrix.jl` (no promises on this though).
Oh, and this will break Nemo in the current state.
> Use type traits in linear solving

- src/AbsSeries.jl
- src/RelSeries.jl
- src/generic/AbsSeries.jl
- src/generic/RelSeries.jl
- test/generic/AbsSeries-test.jl
- test/generic/RelSeries-test.jl
This is not correct:
```
julia> R, x = power_series_ring(GF(5), 10, "x");
julia> is_zero(R(5))
true
julia> valuation(R(5))
0
```
(I'm not sure I like `valuation(R(5)) == 10` either, but at least that appears to be the convention.)
> Fix a power series bug

- src/utils.jl
- test/utils/Banners/banners.jl
I compared the backtraces of the `__init__` call in the cases of `using OtherPackage` and `using Package` in 1.11.0-rc1, and the only difference is one single line number. So I added some code to the function that exploits this difference in the most robust way I can think of.
I think we should backport this change to AA 0.41.x afterwards, so that people using Oscar 1.1 with julia 1.11 in the near future (e.g. if julia 1.11 gets released before Oscar 1.2) don't get bloated with banners and instead use this updated code to suppress almost all of them (but one).
cc @benlorenz @lkastner
> Make `should_show_banner` work with julia 1.11 and nightly

- src/julia/Integer.jl
The prior code did not do any wrong computations, it just neglected to actually use the third set of moduli/residues tables for the prime 7 due to a typo, which this patch fixes.
This patch also cleans up the handling of even 'a' and adds a bunch of comments to explain what is going on.
Finally, it also extends the check mod 8 to even n. The prior check here was a bit hackish in that it hardcoded the assumption that `moduli5[1]` is 8.
The second commit also consolidates the code.
Some quick microbenchmarking suggests that the new code is actually a little bit more efficient than the old, but I don't think this will matter too much in practice. (Well, it is also a bit slower if the exponent is a multiple of 7 -- but that's due to the "bug" this PR fixed, where it doesn't actually use the …
> Fix and document `AbstractAlgebra.ispower_moduli`

- test/generic/MPoly-test.jl
- test/misc-test.jl
Previously, I tested the various options to `@varnames_interface` only implicitly. Here, I add some explicit tests, demonstrating all the options. A handful more lines can easily be added, if we accept proposal #1762.
> Cover `@varnames_interface` options with explicit tests

- docs/src/ring_interface.md
Hi!
I don't see any reason against using this helper function in the example.
> use `check_parent` helper in ring interface example

- src/RelSeries.jl
- src/generic/AbsSeries.jl
- src/generic/RelSeries.jl
- test/generic/AbsSeries-test.jl
- test/generic/RelSeries-test.jl
Goes with https://github.com/Nemocas/Nemo.jl/pull/1839.
It seems to me that `set_precision!` was intended as an internal setter method as part of the abstract interface to power series.
I now made `set_precision!` also truncate the underlying polynomial if necessary and renamed the internal setter to `_set_precision_raw!`. This method is use a lot in the code and probably should not always try to modify the polynomial.
There is a similar issue with `set_valuation!`, but I decided not to do anything about this. It's not clear to me what "setting the valuation" should mean mathematically.
> Make `set_precision` reduce the element

- src/misc/VarNames.jl
The two lines deleted here supported `VarName` being in `VarNames` and were overseen in #1513. I just noticed them due to being [the only lines of VarNames.jl not covered by tests](https://app.codecov.io/gh/Nemocas/AbstractAlgebra.jl/blob/master/src%2Fmisc%2FVarNames.jl).
> Remove stale code being dead since #1513

- Project.toml
- src/Deprecations.jl
In #1769, I removed `mulmod(::T, ::T, ::Vector{T}) where T <: MPolyRingElem`; apparently this is used in Hecke though. (I was certain I ran all the tests locally, but apparently I missed the "long" ones?)
I don't like the name of this function (`mod` in the context of several multivariate polynomials sounds like Gröbner stuff to me?) and in the end writing `divrem(a * b, m)[2]` is not much longer.
So, I would only want to introduce this as a deprecation. Is that fine?
Sorry for this.
NEW: I put `mulmod` in `Deprecations.jl` but only as a redirect. I also removed another deprecation introduced in #1769 which is actually used in Hecke.
> Clean up the mess I created when I cleaned up `NemoStuff.jl`

- src/Attributes.jl
- src/Deprecations.jl
- test/Attributes-test.jl
We have a lot of places in our codebases where people use `@attr` without specifying a return type, even though in many of these cases they are very easy too deduce (see e.g. all of the `dim` and `is_*` cases in https://github.com/oscar-system/Oscar.jl/pull/4059). I don't know if this is due to people not knowing about the possibility, forget it, or just don't care. But at least for me, it is usually the second one (see e.g. the Lie algebra changes in https://github.com/oscar-system/Oscar.jl/pull/4059).
Thus I propose to deprecate (in the next breaking release) the use of 1-arg `@attr` (with only a method expression) in favor of explicitly requiring people to write `@attr Any` if they don't want to think of the return type. I think this would be a good measure for enforcing better …
> Enforce `@attr` uses to always provide a return type

- Project.toml
- docs/src/matrix.md
- src/Matrix.jl
- src/exports.jl
- test/Matrix-test.jl
I need something for checking nilpotency of a matrix in OSCAR. If you have good ideas for speed improvements, please let me know. Otherwise, I would be happy to get this merged soonish, and performance things can be adapted later anyway.
> Add `is_nilpotent(::MatrixElem)`

- docs/make.jl
- docs/src/assertions.md
- src/AbstractAlgebra.jl
- src/Assertions.jl
- src/exports.jl
https://github.com/thofma/Hecke.jl/pull/1607 is the corresponding cleanup.
> Move `assertions.jl` from Hecke

- src/Deprecations.jl
- test/Attributes-test.jl
cc @joschmitt who introduced some of them
> Update deprecations for breaking release

- src/NCRings.jl
- src/fundamental_interface.jl
- src/generic/MPoly.jl
- src/generic/SparsePoly.jl
- src/generic/UnivPoly.jl
- src/julia/Float.jl
- src/julia/Integer.jl
- src/julia/Rational.jl
Now we can e.g. use addmul! on 3 or 4 ZZMatrix instances and get an efficient result.
Use this to get rid of some now redundant `addmul!` methods.
Also remove some redundant `add!` methods and add some `sub!` methods.
> Make addmul! fully generic, add docstrings

- test/AliasMacro-test.jl
- test/Attributes-test.jl
Adapts to https://github.com/JuliaLang/julia/pull/55465.
Please only merge this if all nightly jobs succeed.
> Adapt alias macro docstring test to nightly changes

- src/Matrix.jl
- src/julia/Matrix.jl
- test/generic/MatRing-test.jl
- test/generic/Matrix-test.jl
Also change the methods as well as that one for `is_zero_entry` to apply to Julia matrices, too.
> Avoid redundant bounds checks in `is_zero_row` and `is_zero_column`

- src/Aliases.jl
I now expected this to exist multiple times, we have similarly used aliases for `iszero` and `isone` already, so I see no reason to not add this.
> Add `is_nothing` alias

- docs/src/univpolynomial.md
- src/generic/UnivPoly.jl
It seems like the poor universal polynomials were overlooked again ;-) I tried to make this somehow in line with the `MPoly` implementation. In the documentation examples for the `MPoly`s we are testing `number_of_generators` for equality instead of simply printing the result like in the new examples for `UniversalPolyRing`. Is there a particular reason for this?
> add `number_of_generators` for `UniversalPolyRing`

- src/Matrix-Strassen.jl
Fixes Strassen, which I broke in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1784, and adds a corresponding "real" doctest.
This requires https://github.com/Nemocas/AbstractAlgebra.jl/pull/1801 to be merged first to work properly.
> Fix Strassen, add a test

- docs/src/ring.md
- docs/src/ring_interface.md
- src/Groups.jl
- src/exports.jl
- src/fundamental_interface.jl
Also refactor the code defining them to use macros to reduce
repetition substantially.
Finally merge and update the sections discussion unsafe operators
in the "rings" and "ring interface" chapters of the manual: the latter
now
> Add divexact!, lcm!, submul!

- src/Matrix.jl
- src/exports.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/4169.
This is an attempt to implement the suggestion from [Issue 4169 ](https://github.com/oscar-system/Oscar.jl/issues/4169) in the Oscarl.jl repo:
- A function `minors_iterator` has been introduced, that constructs an iterator that calculates all minors.
- The old function `minors` has been replaced by a function that collects the minors from `minors_iterator`.
The functions still relies on the internal function `combinations`. For further improvements in performance, one could consider turning `combinations` into a generator too.
> Iterator for minors of matrix

- src/Fields.jl
- src/Poly.jl
- src/fundamental_interface.jl
- src/generic/LaurentMPoly.jl
- src/generic/Misc/Localization.jl
`Base.inv` and `AbstractAlgebra.inv` differ in handling Integers. The base version returns floats, while the AA version errors if it doesn't get a unit.
Similarly, `Base.div` and `AbstractAlgebra.div` differ. For this function, we need to either change the fallback of `div!` from `AbstractAlgebra.div` to `Base.div`, or change the docstring in a similar way as for `inv!`. Which of the two do we want here?
(In the any case, https://github.com/Nemocas/AbstractAlgebra.jl/pull/1816 needs to be adjusted to be consistent.)
> Correct mutating op fallbacks

- src/Matrix.jl
- src/Module.jl
- src/Poly.jl
- src/generic/FreeAssociativeAlgebra.jl
- src/generic/MPoly.jl
- src/generic/PermGroups.jl
- src/generic/UnivPoly.jl
> However the form that accepts a type argument should be defined for
new types. (docstring of `eltype`)
this makes it possible to clean up some of the `eltype` methods.
furthermore remove some useless iterator getters that just reproduce julia defaults
> Change eltype defs to `Type{...}` and some iterator cleanup

- src/FreeAssociativeAlgebra.jl
- src/exports.jl
- src/generic/FreeAssociativeAlgebra.jl
- src/misc/VarNames.jl
- test/generic/FreeAssociativeAlgebra-test.jl
This is analogous to `dense_poly_ring_type` and friends, and can be used to assert concrete types in downstream code that currently uses the abstract type `FreeAssociativeAlgebra` (even though we currently only have one subtype, namely `Generic.FreeAssociativeAlgebra`).
> Add `free_associative_algebra_type`

- src/julia/Integer.jl
- test/julia/Integers-test.jl
Apparently, `__gmpz_divexact` crashes in case of a division by 0. I would say that we should throw an error even if `check = false`.
> Throw an error in case of division by zero instead of crashing hard

- test/WeakKeyIdDict-test.jl
This fails with Julia nightly (as it made BigFloat immutable) and we don't really need this as a feature either.
Resolves #1825
> Stop testing BigFloat keys in WeakKeyIdDict

- src/utils.jl
This should fix CI for nightly.
Line-diff of 73 should work for 1.11 and 1.12.
> banner-hide: update line-numbers for current nightly

- test/Rings-conformance-tests.jl
- test/conformance-tests.jl
- test/generic/AbsSeries-test.jl
- test/generic/PermGroupAPI-test.jl
- test/generic/RelSeries-test.jl
- test/generic/Residue-test.jl
- test/julia/Floats-test.jl
- test/julia/GFElem-test.jl
- test/julia/Rationals-test.jl
Also make sure other packages which only load Rings-conformance-tests.jl
get them.
Finally cleanup how we include Groups-conformance-tests.jl
Unfortunately this causes test failures and eventually a bus error crash (!). This is due to the `test_elem(Rx::AbstractAlgebra.SeriesRing)` method. The crash can be triggered with
```
R, x = power_series_ring(ZZ, 10, :x)
include("test/Rings-conformance-tests.jl");
test_Ring_interface(R)
```
Note that there are failures before that because the tests for the unsafe ops `add!` etc. don't take into account that the series rings are inexact. I hope #1816 will fix that part.
But even taking that into account, we really shouldn't get a hard crash here
> More generic test_elem methods

- src/Poly.jl
I don't know what this function is doing, so this is an educated guess. For polynomials over fields, another `gcd` is used. The function fixed here is only called if one specifies the `ignore_content = true`.
I found this by calling `is_squarefree` on a polynomial over a number field in Nemo.
> Fix a bug in gcd for polynomials

- src/Matrix.jl
- test/generic/Matrix-test.jl
Closes https://github.com/oscar-system/Oscar.jl/issues/4175 .
This needs some extra work because `Slices` only exists since Julia 1.9. Is it fine like this?
> Add `eachrow` and `eachcol`

- src/Residue.jl
- src/generic/Residue.jl
They rely on implementation details and thus are not truly generic.
In practice they cause problems for ResElem subtypes in Nemo.
> Restrict unsafe ops for ResElem to EuclideanRingResidueRingElem

- Project.toml
To be merged and released once 
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1827
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1831
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1811
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1836
are merged.
> Bump version to 0.43.4

- docs/src/univpolynomial.md
- src/generic/UnivPoly.jl
Also replacedocumentation for `universal_polynomial_ring` in
the manual by that docstring -- this also fixes a mistake in
it, as the manual mentioned a non-existing argument `S`.
> Add a docstring for universal_polynomial_ring

- src/Matrix.jl
Solves https://github.com/oscar-system/Oscar.jl/issues/4179
> Specify how to obtain all inverses

- src/Fields.jl
- src/NumFields.jl
- src/generic/FactoredFraction.jl
- src/generic/FunctionField.jl
- src/generic/RationalFunctionField.jl
Needed for some conformance tests of Nemo types
> Add generic is_unit(::FieldElem) method

- src/Matrix.jl
- src/generic/MatRing.jl
- src/generic/Matrix.jl
- test/Matrix-test.jl
As discussed on slack.
The added tests demonstrate all of the new conversions that are now possible.
> Add some more MatElem/MatRingElem conversions

- src/Rings.jl
- src/fundamental_interface.jl
Also remove some outdated or pointless TODO comments, and
add a docstring for is_perfect
> Add is_trivial(::NCRing)

- src/MatRing.jl
- src/generic/MatRing.jl
- test/generic/MatRing-test.jl
- Check `n` in the constructor to be non-negative. Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1851.
- Fix `characteristic(matrix_ring(R, 0))` to be `1`.
> Some MatrixRing fixes

- docs/src/matrix.md
- docs/src/matrix_interface.md
- docs/src/visualizing_types.md
- src/AbstractAlgebra.jl
- src/AbstractTypes.jl
- src/ConcreteTypes.jl
- src/Generic.jl
- src/Matrix.jl
- src/generic/GenericTypes.jl
- src/generic/Matrix.jl
- src/generic/imports.jl
- test/generic/Matrix-test.jl
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1840.
This should technically be non-breaking as `Generic.MatSpace === MatSpace` after these changes, and thus all references to `Generic.MatSpace` still point to the actual type used for matrix spaces. In the next breaking release, we can uncomment the deprecation to fade out the use of `Generic.MatSpace`.
I haven't tested this with Nemo yet, let's hope for the best.
> Merge MatSpace and Generic.MatSpace

- src/Rings.jl
Implement `isapprox` for ring elements via equality by default. On the one
hand, we need isapprox methods to be able to conformance test series rings.
On the other hand this is essentially the only sensible thing to do in
positive characteristic so we might as well do it in a generic method, so that
only rings for which we explicitly want different behavior need to provide their own methods.
> Provide a default isapprox method for ring elements

- src/generic/FreeAssociativeAlgebra.jl
- src/generic/MPoly.jl
- src/generic/Poly.jl
- src/generic/UnivPoly.jl
- src/generic/imports.jl
- test/Rings-conformance-tests.jl
- test/generic/FreeAssociativeAlgebra-test.jl
- test/generic/MPoly-test.jl
cc @fingolfin 
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1819
> Unsafe funcs for FreeAssAlgebra, Poly, MPoly

- docs/src/constructors.md
- src/LaurentPoly.jl
- src/LaurentSeries.jl
- src/PuiseuxSeries.jl
- src/generic/LaurentMPoly.jl
- src/generic/LaurentPoly.jl
Progress towards https://github.com/Nemocas/AbstractAlgebra.jl/issues/1856, split off from https://github.com/Nemocas/AbstractAlgebra.jl/pull/1857.
> Require non-zero coefficient ring in laurent/puiseux constructions

- src/RelSeries.jl
- src/generic/AbsMSeries.jl
- src/generic/RelSeries.jl
Progress towards https://github.com/Nemocas/AbstractAlgebra.jl/issues/1856, split off from https://github.com/Nemocas/AbstractAlgebra.jl/pull/1857.
> Require non-zero coefficient ring in power series ring

- src/FreeAssociativeAlgebra.jl
Progress towards https://github.com/Nemocas/AbstractAlgebra.jl/issues/1856, split off from https://github.com/Nemocas/AbstractAlgebra.jl/pull/1857.
> Require non-zero coefficient ring in free associative algebra

- src/generic/UnivPoly.jl
Progress towards https://github.com/Nemocas/AbstractAlgebra.jl/issues/1856, split off from https://github.com/Nemocas/AbstractAlgebra.jl/pull/1857.
> Require non-zero coefficient ring in universal polynomial ring

- src/generic/FreeAssociativeAlgebra.jl
- test/generic/FreeAssociativeAlgebra-test.jl
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1865
(tests copied from MPoly-test.jl, and added another few lines for QQ/Rational{Int} tests)
> Add adhoc arithmetics for FreeAssociativeAlgebraElem

- src/algorithms/GenericFunctions.jl
> algorithms/GenericFunctions: `x == 0` -> `iszero(x)`

- src/Matrix.jl
Closes https://github.com/oscar-system/Oscar.jl/issues/4222
> More helpful error for `diagonal_matrix`

- src/julia/Float.jl
> julia/Float: `x == 0` -> `iszero(x)`

- src/algorithms/GenericFunctions.jl
- src/generic/FactoredFraction.jl
- src/generic/LaurentPoly.jl
- test/algorithms/GenericFunctions-test.jl
> Replace some custom checks by check_parent

- src/Matrix.jl
there is too much code that directly accesses entries using numerical indices e.g. in `(::MatrixSpace)(::AbstractMatrix)`
> Require one-based indexing in `_check_dim`

- src/generic/UnivPoly.jl
- test/generic/UnivPoly-test.jl
This reduces the overhead for e.g. x+1 a bit -- at least in Nemo,
the mpoly type in AA is too inefficient to benefit from this.
> Improve adhoc arithmetic for UnivPoly

- src/utils.jl
- test/utils/Banners/ModA/src/ModA.jl
- test/utils/Banners/ModB/src/ModB.jl
- test/utils/Banners/banners.jl
> Some enhacements to `is_loaded_directly`

- src/generic/MPoly.jl
- test/Rings-conformance-tests.jl
Work in progress towards #1817...
> Add conformance tests for some adhoc operations

- Project.toml
once https://github.com/Nemocas/AbstractAlgebra.jl/pull/1867 is merged, to mitigate the chance of somehow breaking the compatibility with this change somewhere downstream
> Bump version to 0.43.9

- Project.toml
- src/imports.jl
- src/polysubst.jl
The calls to subtypes don't do anything here. They seem to be an artifact from the time before the split of Nemo and AA.
I am working on some further tweaking of the file, but I think this change here can easily be merged without waiting for further refactoring.
> Get rid of InteractiveUtils dependency

- src/Matrix.jl
E.g. it now works in some more cases with alternative matrix
implementations. E.g. this now works:
julia> using LinearAlgebra ; matrix(GF(5), I(2))
[1   0]
[0   1]
> Make `matrix(R::Ring, arr::AbstractMatrix)` more useful

- src/julia/Float.jl
- src/julia/Integer.jl
- src/julia/Rational.jl
So that e.g. `Integers{BigInt}` and `Integers{Int}` don't print
identically.
> Tweak printing of Julia parent types

- test/Rings-conformance-tests.jl
I now came across two places (namely https://github.com/thofma/Hecke.jl/pull/1659 for `SRow`s and https://github.com/oscar-system/Oscar.jl/pull/4271 for `RootSpaceElem`s) where we don't have a multiplication between objects, but only scalar multiplication (and corresponding `mul!` methods).
To make use of the `test_mutating_op_*` functions, we must have a way to disable multiplications between objects. I achieved this in this PR by adding two kwargs, that state if the left respective right factor of some multiplication is a scalar. If this is the case, we only run the tests where the output is aliased with a non-scalar input. This skips all tests where we would multiply two objects (which errors in the above cases) and the ones where we use a scalar type to save the output in (as these …
> Adapt `test_mutating_op_like_(add)mul` to work with scalar mul as well

- src/generic/GenericTypes.jl
- src/generic/Matrix.jl
Also add a UndefInitializer constructor for it.
> Improve copy & deepcopy for MatSpaceElem

- Project.toml
I suggest we quickly make this minor release now so that e.g. @lgoettgens can make use of `test_mutating_op_like_(add)mul` improvements, and before any potentially breaking changes to `similar`.
> Version 0.43.10

- test/generic/Matrix-test.jl
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1901.
This is fixing the error @thofma pointed out in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1900#issuecomment-2469971904.
> Adapt to `hvcat` error type in julia

- docs/src/matrix.md
- src/MatRing.jl
- src/Matrix.jl
- src/generic/Matrix.jl
- test/Rings-conformance-tests.jl
- test/generic/Matrix-test.jl
Remove the internal helper `_similar` which untangles the `MatElem` and `MatRingElem` code further and makes it easier to see what's going on.
Also change `similar` for `MatElem` to default to calling `zero_matrix`. With this `similar(::ZZMatrix)` in Nemo returns a new `ZZMatrix` instead of a `AbstractAlgebra.Generic.MatSpaceElem{ZZRingElem}`.
Resolves https://github.com/Nemocas/Nemo.jl/issues/1826
> Simplify and fix `similar` and `zero` for our matrix types

- src/Rings.jl
As suggested by @YueRen. All rings implement `one` and `is_zero`, but many don't or cannot implement `characteristic`.
Will make #1857 less breaking.
> feat: more generic `is_trivial`

- Project.toml
- src/Matrix.jl
- test/Matrix-test.jl
This is needed to e.g. do a `findall(f, ::MatElem)` in julia 1.10, and thus is needed for the 1.10 tests on https://github.com/oscar-system/Oscar.jl/pull/4322.
> Add `Base.keys(::MatElem)`

- src/exports.jl
- src/generic/PermGroups.jl
- src/generic/exports.jl
- test/generic/Perm-test.jl
This is not required to be implemented, but this serves as a parent function for all uses downstream.
> Add `is_abelian` for groups

- src/Rings.jl
This way e.g. 'is_trivial(ZZ)' is compiled into 'reutrn false'.
If we also add a few more dedicated `is_trivial` methods for e.g. some quotient ring implementations, we may even be able to get by without caching this value anywhere?
> Add implication: integral domains are not trivial

- docs/src/rand.md
- docs/src/ring_interface.md
- src/MPoly.jl
- src/MatRing.jl
- src/Matrix.jl
- src/Module.jl
- src/NCPoly.jl
- src/Poly.jl
- src/RelSeries.jl
- src/Residue.jl
- src/ResidueField.jl
- src/generic/FunctionField.jl
- src/generic/PuiseuxSeries.jl
- src/julia/Float.jl
- src/julia/Integer.jl
- src/julia/Rational.jl
Julia has this to say about `GLOBAL_RNG`:
> defined only for backward compatibility with pre-v1.3 code when
> `default_rng()` didn't exist; `GLOBAL_RNG` was never really
> documented, but was appearing in the docstring of `rand`
> Use Random.default_rng() instead of Random.GLOBAL_RNG

- src/Residue.jl
- test/generic/Residue-test.jl
Note that this does not render the new `is_trivial` methods for `ZZModRing` and `zzModRing` obsolete because they are not subtypes of `ResidueRing`, see https://github.com/Nemocas/Nemo.jl/pull/1819
> Add generic `is_trivial` method for `ResidueRing`

- docs/src/visualizing_types.md
This was renamed some time ago, I believe this spot was just overlooked?
> docs: Generic.ResidueRing -> Generic.EuclideanRingResidueRing

- src/Fields.jl
- src/generic/Misc/Poly.jl
- test/generic/Fraction-test.jl
Also enables `factor(ZZ, 28//15)` in Nemo, Hecke, Oscar. Alas, no tests for this here as we have no `factor` methods for any integer types here in AA.
Fixes https://github.com/thofma/Hecke.jl/issues/1110
> Enable `factor(::Rational)`

- src/Ideal.jl
- src/exports.jl
Probably breaking because Hecke already declares this.
There should be more code and docstrings added, but since we are close to a breaking release I thought it would be sensible to get this tiny breaking bit in now, and worry about the rest later.
> Add generic dispatch for `ideal_type`

- src/Matrix.jl
- src/generic/Matrix.jl
- test/generic/Matrix-test.jl
This is incompatible with older Nemo versions which did not provide `UndefInitializer` constructors for their matrices. Thus I've added the "breaking" label.
<s>Note quite done yet, I'd like to convert more places to use the `undef` constructors.</s> Should be OK to review now.
> Change `similar`, `zero_matrix`, `ones_matrix` to use `UndefInitializer` constructors

- src/Matrix.jl
- src/julia/Matrix.jl
- test/Rings-conformance-tests.jl
Also remove a bounds check in `swap_rows!` for MatrixElem, to match `swap_cols!`. This follows our general principle that `!` methods don't perform such tests, it is up to the caller to ensure such preconditions are satisfied.
Also test these functions as part of the ring conformance tests
Resolves #1730
> swap_cols and swap_rows for Julia matrices

- src/Matrix.jl
... and use it to optimize a few default methods for matrix types that are zero initialized.
Resolves #558 (where this approach was first suggested).
I am happy to discuss alternative approaches if someone has a good idea. One that comes to mind is to require all matrix types to also offer a constructor `MatrixType(parent, r, c)` (without the `undef`) which then is required to be zero initialized.
But doing that would require work for every matrix type, while with this `is_zero_initialized` trait is minimally intrusive.
> Add `is_zero_initialized` trait for matrix types

- test/generic/Residue-test.jl
> Re-enable conformance test for residue ring over Z[x]

- src/Rings.jl
For examples, this now works:
julia> is_domain_type(ZZ)
true
julia> is_domain_type(ZZ(2))
true
julia> is_domain_type(residue_ring(ZZ,6)[1])
false
> Make is_exact_type and is_domain_type more convenient

- test/Rings-conformance-tests.jl
Not all rings provide this, nor should they have to. But *if* a ring provides it, it should be compatible with `base_ring_type`.
Resolves #1944
> Don't require base_ring in ring conformance tests

- src/FreeAssociativeAlgebra.jl
- src/MPoly.jl
- src/generic/LaurentMPoly.jl
- src/generic/Poly.jl
... by equivalent compile-time constructs
> Replace uses of elem_type(coefficient_ring(R))

- src/Attributes.jl
- test/Attributes-test.jl
See https://github.com/oscar-system/Oscar.jl/issues/1255#issuecomment-2587556930 for the motivation and details.
Is that something that we want to have?
cc @HereAround
> Add `ignore_kwargs` to `@attr` macro

- src/Attributes.jl
- src/Deprecations.jl
- test/Attributes-test.jl
As discussed in https://github.com/oscar-system/Oscar.jl/pull/4476.
@fingolfin @simonbrandhorst @HereAround is this what you thought about?
Regarding breakiness of the removed option syntax: I propose to deprecate this right now, and remove with the next breaking AA release.
> Remove `ignore_kwargs`; instead always ignore all kwargs in `@attr`

- Project.toml
To release the following PRs for use downstream:
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1966
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1967
> Bump version to 0.44.4

- docs/src/polynomial.md
- src/Poly.jl
- rename `subst` to `evaluate_brent_kung` and add a hard alias
for backwards compatibility
- introduce `evaluate_horner`
- use in-place operations where possible
(Ideally we can phase out `subst`.)
> refactor: evaluate/subst for univariate polynomials

- src/algorithms/GenericFunctions.jl
As observed in https://github.com/oscar-system/Oscar.jl/pull/4497#discussion_r1928608529:
```
julia> divides(5, 2)
(false, 2)
```
CC: @joschmitt
> fix: docstring for divides promises too much

- src/MPoly.jl
It was already there, so we might as well use it. Cannot be tested, but enables things like this in Oscar:
```
julia> K = algebraic_closure(QQ)
Field of algebraic numbers
julia> Kx, (x, y) = K["x", "y"];
julia> factor(x^2*y^2 + 1)
1 * (x*y + Root -1.00000*im of x^2 + 1) * (x*y + Root 1.00000*im of x^2 + 1)
julia> factor_squarefree(x^2*y^2 + 1)
1 * (x^2*y^2 + 1)
```
> Enable multivariate factorization in characteristic 0 (at least over coefficient rings for which univariate factorization is implemented)

- src/Poly.jl
I have multiple issues with this method:
1. The zero polynomial is in all other cases in AA defined to have content 0. This method would set it to 1 instead.
2. We have fields, where the gcd is not defined as 1. E.g. for `QQFieldElem` in Nemo, see https://flintlib.org/doc/fmpq.html#c._fmpq_gcd
3. The same is true for the field `AbstractAlgebra.Rationals`, it also has a non-trivial gcd definition. (I did not check if it coincides with the one from fmpq, but that shouldn't be relevant here). But for technical reasons, polynomials over this field, don't even take this method but instead the generic one.
All in all, this seems to be more prone to confusion as it is useful. What are your opinions?
> Remove `content(::PolyRingElem{<:FieldElem})` method which always returns 1, as this disagrees with the definition of `content` over some fields

- src/Matrix.jl
- src/generic/MatRing.jl
Actually I wonder if we need the `charpoly_only` option at all.
Is anyone using this? I found nothing.
> Don't mention charpoly_only in docstrings

- src/AbsMSeries.jl
- src/AbstractAlgebra.jl
- src/FreeAssociativeAlgebra.jl
- src/LaurentMPoly.jl
- src/MPoly.jl
- src/RationalFunctionField.jl
- src/misc/VarNames.jl
Moves the `@varnames_interface` calls into the files of the type the call belongs to.
This loosens the restriction of inclusion order in `AbstractAlgebra.jl` as before it was not possible to use the macro inside of `Generic`.
This PR was extracted as part of https://github.com/Nemocas/AbstractAlgebra.jl/pull/1809.
> Restructure `@varnames_interface` calls

- docs/make.jl
- docs/src/matrix.md
- docs/src/matrix_implementation.md
- docs/src/matrix_spaces.md
Improved matrix documentation by splitting matrix.md into 3 disjoint files
Any suggestions on possible changes are welcome
This is addressing #1981
> Improved matrix documentation

- src/imports.jl
to silence the warnings introduced in https://github.com/JuliaLang/julia/pull/57311.
> Explicitely import `Base.Matrix`

- src/algorithms/MPolyFactor.jl
Also remove some diffs to the Hecke version of the code
> Import mulpow! into submodule MPolyFactor

- src/generic/Fraction.jl
- src/generic/RationalFunctionField.jl
- src/generic/imports.jl
- test/generic/RationalFunctionField-test.jl
- delegate factorization to `FracField` over polynomial rings
- make `rand` produce reduced fractions like `t//t` or `0//(t + 2)`
The `reduce` is kind of a hack, since the only official way to get reduced fractions is `//`, but this gives the wrong parent.
> feat: improvements for function fields

- src/AbstractAlgebra.jl
- src/UnivPoly.jl
Since `factor` is supported for `MPoly` it should also be possible to factor `UnivPoly`. This PR adds this feature. Unfortunately I can't add tests for this to AbsractAlgebra itself since the actual factorization is implemented in Nemo.
Note that the reordering in `AbstractAlgebra.jl` was necessary to make `Fac` available early enough.
> Wrap `MPoly` factorization for `UnivPoly`

- src/PrettyPrinting.jl
This is not useful in the manual, but certainly in the REPL.
> Add some refs between allow_unicode and friends

- src/generic/UnivPoly.jl
- test/generic/MPoly-test.jl
- test/generic/UnivPoly-test.jl
This fixes #2014. I'm not so sure about where to put this new method since there is no file for common `UnivPoly` and `MPoly` implementations.
```
julia> R,(x,y)=universal_polynomial_ring(QQ, [:x,:y])
(Universal Polynomial Ring over Rationals, AbstractAlgebra.Generic.UnivPoly{Rational{BigInt}}[x, y])
julia> S,(a,b)=QQ[:a,:b]
(Multivariate polynomial ring in 2 variables over rationals, AbstractAlgebra.Generic.MPoly{Rational{BigInt}}[a, b])
julia> f=3y^2-x*y+2x^3
2*x^3 - x*y + 3*y^2
julia> g=a^2-b
a^2 - b
julia> f(y=2)
2*x^3 - 2*x + 12
julia> f(y=2,x=3)
60
julia> g(a=2)
-b + 4
julia> f(x=3,y=2)
60
julia> f(x=y,y=x)
3*x^2 - x*y + 2*y^3
```
> More intuitive polynomial evaluation, e.g. `f(y=3)` to substitute 3 for the variable named `y` in the polynomial `f`

- src/algorithms/MPolyFactor.jl
- test/algorithms/MPolyFactor-test.jl
- keep the MPolyFactor module accepting arbitrary rings, but
make the implementation more robust to capture illegal operations
with non-invertible elements
Closes #1960 and closes #1961
(part of the work towards #1961 was #1973)
> fix: make MPolyFactor module more robust

- docs/src/linear_solving.md
- src/Solve.jl
that are wrong / pull in too many docstrings when viewing the page as part of the Oscar docs.
> Fix some references in the Linear Solving docs

- Project.toml
Things I would like to see included:
- `pow!` fallback https://github.com/Nemocas/AbstractAlgebra.jl/pull/2023
- `reverse!` fallback https://github.com/Nemocas/AbstractAlgebra.jl/pull/2023
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/2022 (not needed, just nice to have)
> chore: Bump to 0.44.9

- src/generic/MPoly.jl
Before:
julia> R, _ = polynomial_ring(QQ, 2);
julia> @b gen($R, 1)
79.036 ns (9 allocs: 304 bytes)
julia> R, _ = polynomial_ring(QQ, 10; internal_ordering=:degrevlex);
julia> @b gen($R, 1)
613.239 ns (21 allocs: 752 bytes)
After:
julia> R, _ = polynomial_ring(QQ, 2);
julia> @b gen($R, 1)
71.306 ns (9 allocs: 304 bytes)
julia> R, _ = polynomial_ring(QQ, 10; internal_ordering=:degrevlex);
julia> @b gen($R, 1)
75.127 ns (9 allocs: 368 bytes)
> Optimize `gen(::MPolyRing, ::Int)` for :deglex and :degrevlex

- docs/src/ncpolynomial.md
- src/MPoly.jl
- src/NCPoly.jl
- src/Poly.jl
- test/generic/NCPoly-test.jl
The fix is just to disable `is_nilpotent` and `is_unit` for polynomials over non-commutative rings.
I believe the algorithms are correct for non-commutative local rings (since sums of nilpotents are nilpotent in such rings).
> Remove broken `is_unit` and `is_nilpotent` for `NCPolyRingElem`

- src/Groups.jl
- src/exports.jl
This is the AA part of https://github.com/oscar-system/Oscar.jl/pull/4616.
For the time being, this PR only exists to run changes in Oscar, Hecke, and AA in one CI; and to demonstrate the proof-of-concept.
> Add stub for isomorphism(::Type{<:Group}, ::Group)

- Project.toml
To release the following PRs:
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/2042
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/2043
> chore: Bump version to 0.44.11

- docs/src/ring.md
- src/exports.jl
- src/generic/Misc/Rings.jl
- src/generic/exports.jl
While playing around with modular polynomial interpolation I noticed that we don't have a `falling_factorial` method.
> Add `falling_factorial`

- ext/TestExt/Rings-conformance-tests.jl
- src/Poly.jl
- src/exports.jl
... and also fixes a bug in the current `shift_left` and `shift_right`.
> Add generic `shift_left!` and `shift_right!` for univariate polynomials

- src/Matrix.jl
This changes the stackoverflow observed e.g. in https://github.com/Nemocas/AbstractAlgebra.jl/issues/1718 to a MethodError.
This stackoverflow currently happens for all sensible inputs to `view` that are not implemented, in particular
- point views of AA's `Generic.MatSpaceElem` (x-ref https://github.com/Nemocas/AbstractAlgebra.jl/pull/2048)
- point views of Nemo mats
- views of Nemo mats where any arg is a `AbstractVector{Int}` that is not a `AbstractUnitRange{Int}`
I implemented this via a method indirection to not create any ambiguities with existing `view` methods that handle `::Colon` args themselves.
> Fix stack overflow when constructing non-implemented views

- src/misc/ProductIterator.jl
Resolves the following issue reported by JET:
```julia
julia> @report_opt collect(AbstractAlgebra.ProductIterator([1:2, 1:3]))
═════ 2 possible errors found ═════
┌ collect(itr::AbstractAlgebra.ProductIterator{UnitRange{Int64}, 1}) @ Base ./array.jl:716
│┌ _collect(cont::UnitRange{…}, itr::AbstractAlgebra.ProductIterator{…}, ::Base.HasEltype, isz::Base.HasLength) @ Base ./array.jl:722
││┌ copyto!(dest::Vector{Vector{Int64}}, src::AbstractAlgebra.ProductIterator{UnitRange{Int64}, 1}) @ Base ./abstractarray.jl:939
│││┌ iterate(p::AbstractAlgebra.ProductIterator{UnitRange{Int64}, 1}, ::Tuple{Vector{Int64}, Vector{Int64}}) @ AbstractAlgebra /home/lgoe/code/julia/AbstractAlgebra.jl/src/misc/ProductIterator.jl:92
││││┌ indexed_iterate(I::Nothing, i::Int64) @ Base ./tuple.jl:162
│││││ runtime …
```
> Fix a JET issue in `iterate(::ProductIterator)`

- src/MPoly.jl
- src/exports.jl
- src/generic/UnivPoly.jl
- src/generic/imports.jl
- test/generic/MPoly-test.jl
- test/generic/UnivPoly-test.jl
Currently, `is_univariate` already computes the index of the variable involved in the respective polynomial. It can be useful to obtain this information to create a fitting univariate polynomial ring where the symbol of the variable matches the variable symbol of the original multivariate polynomial. In fact this could be combined with `to_univariate`.
> Improve univariate conversion

- src/julia/Matrix.jl
This is also in PR #2051 (where we discovered the issue) but as that seems stalled let's apply this fix right now.
> Fix `swap_cols!` for `Matrix{T}`

- src/Rings.jl
Method dispatch does not take keyword arguments into account. Therefore the kind of dispatch used by this method is risky and can result in an infinite recursion.
Discovered while looking at test failures in PR #2051
> Remove bad generic sqrt method

- src/generic/MPoly.jl
- test/generic/MPoly-test.jl
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1219.
That issue talks about *the new evaluate code*, but since that hasn't happened in 2+ years, maybe we can just add this bandaid for the meantime
> Fix weird return type in evaluate via call syntax

- src/Matrix.jl
- src/exports.jl
- src/generic/LaurentPoly.jl
- src/generic/RationalFunctionField.jl
- test/generic/Matrix-test.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/4867.
This is not breaking for any users of AbstractAlgebra.jl, just for Oscar.jl itself (due to the existence of multiple methods with exact signature). Users of Oscar.jl should experience no difference.
> Move parts of Oscar's `MoveToAbstractAlgebra.jl` over

- .github/workflows/CI.yml
- docs/documenter_helpers.jl
- src/Matrix-Strassen.jl
see https://github.com/Nemocas/AbstractAlgebra.jl/issues/2083 for details
cc: @lgoettgens
I can remove the documenter helper again if requested but it makes it a lot easier to debug such issues.
> doctests: add verbose output, disable Matrix-Strassen doctest

- src/Aliases.jl
- src/julia/Float.jl
We just ran into this in https://github.com/oscar-system/Oscar.jl/pull/4908#discussion_r2097393871 (on nightly), so better to just alias them on available julia versions.
> Alias `ispositive`/`isnegative` in recent enough julia versions

- src/Fraction.jl
- src/generic/FactoredFraction.jl
- src/generic/RationalFunctionField.jl
- test/generic/FactoredFraction-test.jl
- test/generic/Fraction-test.jl
- test/generic/RationalFunctionField-test.jl
Now rational function fields, fraction fields and factored fraction fields allow using "function call syntax" as a shorthand for `evaluate`.
This also resolves an issue in the RationalFunctionField tests for `evaluate` which did not actually work as intended, as the elements being evaluated action ended up being of type `FracElem`.
> Support function call syntax for evaluate for more rings

- src/NCPoly.jl
- src/Poly.jl
- test/generic/NCPoly-test.jl
- test/generic/Poly-test.jl
- allow mapping `PolyRingElem` to `NCPolyRingElem` and vice versa
> feat: relax signature for map_coefficients

- ext/TestExt/Rings-conformance-tests.jl
We can't expect general rings to support inv, not even for the ring's one element. These tests may be reactivated in a future version, e.g. if we add an `implements` trait.
Alternative to @HechtiDerLachs's PR #2077. May fix this "properly" in PR #1957 or a follow-up, but for now this is the obvious change to make.
@HechtiDerLachs of course you might run in further issues, let me know if that's the case.
> Don't use `inv` and `inv!` in ring conformance tests

- src/generic/DirectSum.jl
- src/generic/QuotientModule.jl
- test/generic/DirectSum-test.jl
- test/generic/QuotientModule-test.jl
When computing the total complex of a tensor product of chain complexes in `Oscar.jl`, it called `rank(M)` where M was a `DirectSumModule`. However, no method for `rank` was defined for this type, causing the following MRE
MRE: 
```
julia> L = 2;
julia> F = GF(2);
julia> H = matrix(F, 1, L, ones(Int, L));
julia> V1 = free_module(F, L-1);
julia> V0 = free_module(F, L);
julia> ∂C = hom(V1, V0, H);
julia> C = chain_complex([∂C]);
julia> ∂D = hom(V0, V1, transpose(H));
julia> D = chain_complex([∂D]);
julia> dc = tensor_product(C, D);
julia> E = total_complex(dc);
julia> dc_2d = tensor_product(C, D);
julia> E_2d = total_complex(dc_2d);
julia> dc_3d = tensor_product(E_2d, D);
julia> F_3d = total_complex(dc_3d)
ERROR: MethodError: no method matching …
```
> Add `rank` method for `DirectSumModule`

- src/algorithms/GenericFunctions.jl
To prevent problems like this:
julia> is_irreducible([])
false
CC @simonbrandhorst
> Add some missing type qualifiers

- src/Map.jl
- currently not optimal for maps that use `@show_name` (and thus have terse printing)
> fix: printing of M::Map

- src/Fraction.jl
- src/exports.jl
- src/generic/FunctionField.jl
- src/generic/RationalFunctionField.jl
Seems natural and I see no harm in it?
> Add `fraction_field_type` and define `fraction_field` method for fields

- src/Deprecations.jl
- src/algorithms/MPolyFactor.jl
- src/generic/UnivPoly.jl
- src/julia/Matrix.jl
- test/Solve-test.jl
Resolves https://github.com/oscar-system/Oscar.jl/issues/2231 by deprecating the already existing functionality.
The consensus of https://github.com/oscar-system/Oscar.jl/issues/2231 seems to be that it is better to not have these methods at all than to add more of them for a full feature parity.
Closes https://github.com/Nemocas/AbstractAlgebra.jl/pull/1886.
> Prepare deprecations of some mixed methods of julia/oscar matrices and entries

- src/Matrix.jl
- test/generic/Matrix-test.jl
This would help for passing e.g. `Vector{PointVector{ZZRingElem}}` or similar types. Or is there any reason not to allow this?
This came up in slack when filtering lattice points and with this change works fine:
```julia
julia> matrix(ZZ, filter(v->v[1]==1, lattice_points(cube(2))))
[1   -1]
[1    0]
[1    1]
```
> Allow `AbstractVector`s for more `matrix` and `diagonal_matrix` constructions

- src/AbstractAlgebra.jl
- src/error.jl
- src/exports.jl
Add `InfiniteDimensionError` exception for vector spaces with an optional argument `check_available` to check if the method `is_finite_dimensional_vector_space` is available in the current context, in which case it will be suggested in the error message. This is rounding out oscar-system/Oscar.jl#5056 .
cc @fingolfin
> Add `InfiniteDimensionError` exception for vector spaces

- src/Module.jl
- test/generic/Module-test.jl
There is a `==` method for two `FPModule`s that compares w.r.t. equality as sets.
The default `hash` method compares the `objectid`s.
In order to satisfy the general rule that `isequal(x, y)` implies `hash(x) == hash(y)`, we need a special `hash` method.
> Equal `FPModule`s must have the same `hash` value

- src/utils.jl
Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/2140.
We used to use the internal function `Base.process_backtrace()` that was changed in https://github.com/JuliaLang/julia/pull/55841. This PR updates the code to instead use `Base.stacktrace` (which is `public` aka guaranteed to stay), but we now need to take care of kwcall ourselves.
> Fix `is_loaded_directly` on nightly

- Project.toml
to make https://github.com/Nemocas/AbstractAlgebra.jl/pull/2139 available in Oscar.
> chore: bump to 0.46.2

- src/Factor.jl
- test/Factor-test.jl
This adds a small hook to back the `Fac` object with an array instead of a dictionary. This does not change the current interface. There might be a small runtime penalty in the iteration, since the state of the iterator is not type stable anymore (the element type still is). But I don't expect this to be noticeable (compared to the time it takes to factor things).
> feat: store (additional) array in Fac

- src/MatrixNormalForms.jl
- test/MatrixNormalForms-test.jl
`echelon_form_with_transformation` would sometimes change the input:
```
julia> K, a = cyclotomic_field(4, :a);
julia> M = K[-a - 1 -a - 1; a + 1 2a - 2]
[-a - 1    -a - 1]
[ a + 1   2*a - 2]
julia> echelon_form_with_transformation(M);
julia> M
[-a - 1   -a - 1]
[ a + 1    a - 3]
```
~I don't know of an example in AbstractAlgebra for the tests.~
I added an AbstractAlgebra-only test.
(Apparently I assumed that `hcat` would copy when I wrote this.)
> Fix a missing deepcopy in `echelon_form_with_transformation`

- src/AbstractAlgebra.jl
This PR adds `identity_map` to `import_exclude` as part of consolidating `identity_map` and `id_hom` across packages (see https://github.com/oscar-system/Oscar.jl/issues/5188).
> Add `identity_map` to excluded imports

- src/Factor.jl
With Nemo:
```
julia> factor(ZZ(6))
2 * 3
```
instead of
```
julia> factor(ZZ(6))
1 * 2 * 3
```
Will be breaking I suppose.
> feat: do not print `1` in factorizations
