Nemocas/AbstractAlgebra.jl

src/generic/Matrix.jl

Should fix the one bug found by Claus.

Fix matrix construction via matrix(::Ring,...)

---

src/generic/MPoly.jl
test/generic/MPoly-test.jl

Now I know why the tests were sometimes hanging.

Relax signature and fix test

---

src/generic/GenericTypes.jl
src/generic/Map.jl

Also, do you mind if I add accessor functions a la:
```
first(f::CompositeMap) = f.map1
second(f::CompositeMap) = f.map2
```

Fix the composition

---

src/generic/Matrix.jl
src/generic/Poly.jl

The type instability in `minpoly` is https://github.com/JuliaLang/julia/issues/15276.

Fix two issues

---

src/generic/Residue.jl
test/generic/Residue-test.jl

Also adds some tests for Z/nZ and allows divides(0, 0) to work mod 1.

Improve algorithm for divexact for residue rings, based on work done in Nemo.

---

src/generic/MPoly.jl

compare parent when comparing polynomials

---

docs/src/mpolynomial_rings.md
src/generic/MPoly.jl
test/generic/MPoly-test.jl

Closes https://github.com/Nemocas/AbstractAlgebra.jl/issues/49

Define nvars for MPolyRing instead of MPoly

---

docs/src/mpolynomial_rings.md
src/AbstractAlgebra.jl
src/generic/MPoly.jl
test/generic/MPoly-test.jl

This adds the `total_degree` function for MPoly.

add total_degree for MPoly

---

docs/src/mpolynomial_rings.md
docs/src/polynomial_rings.md
src/AbstractAlgebra.jl
src/generic/MPoly.jl
src/generic/Poly.jl
test/generic/MPoly-test.jl

Rename vars to symbols

---

src/generic/Matrix.jl

sub(M::AbstractAlgebra.MatElem, rows::Array{Int,1}, cols::Array{Int,1})

add a new function to construct submatrices

---

src/generic/SparsePoly.jl
test/generic/MPoly-test.jl

all instances matching regex Array{[^}]+}([^u ] and Vector{[^}]+}([^u ]
I'm working on batterie, so rely on CI for testing

fix undef Array initialization

---

src/AbstractAlgebra.jl
src/generic/MPoly.jl
test/generic/MPoly-test.jl

Probably not the best, but it works. Also cleaned up MPoly.jl a bit.
Fixes #111.

Fix hashing of MPoly

---

src/generic/Matrix.jl

This will also address https://github.com/Nemocas/Nemo.jl/issues/460 once we apply the changes in Nemo.

Relax signature of matrix constructors (Fix #148)

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

Somehow forgot about this one.

Relax matrix constructors some more

---

src/generic/GenericTypes.jl

Sorry, my pushurl seems to have reverted itself again.

Disable interaction with cache entirely if cached=false.

---

src/generic/MPoly.jl
test/generic/MPoly-test.jl

It did not return a multivariate polynomial in case of the zero polynomial as an input.

fix change_base_ring

---

src/generic/MPoly.jl
test/generic/MPoly-test.jl

* construct new polynomial more efficiently
* make sure that the ordering of the polynomial ring is preserved
* add test to check whether change_base_ring respects the ordering
I think this fixes #168.

improve change_base_ring

---

src/generic/Fraction.jl

Speeds up addition, subtraction and multiplication of generic fractions (a lot).

Fraction field optimisation

---

test/generic/MPoly-test.jl

by creating polynomial rings in several variables

improve test_gen_mpoly_to_univariate()

---

src/generic/Fraction.jl
test/generic/Fraction-test.jl

* Speeds up divexact for generic fractions
* Adds better test code for +, -, *, divexact of generic fractions

Frac divexact speedup

---

src/generic/Fraction.jl

* Speeds up ad hoc addition and subtraction of fractions
* Speeds up unsafe operators for fractions
* Fixes some aliasing bugs introduced in the last PR

More frac speedups

---

src/Fields.jl
src/generic/Poly.jl

This removes two cases where I had implemented delayed reduction in Poly. One where it makes no sense (delayed reduction of polynomial types) and the other where it is incorrect.
The PR also adds some missing fallback routines for Field so that the new number field delayed reduction test code in Nemo will pass.

Delayed reduction fixes

---

docs/src/mpolynomial.md
docs/src/mpolynomial_rings.md
src/generic/MPoly.jl
src/generic/NCPoly.jl

Documents new MPoly interface, as it currently stands and fixes some bugs, whilst making other functions more general.

New mpoly docs

---

docs/src/mpolynomial.md
docs/src/mpolynomial_rings.md
src/generic/MPoly.jl
src/generic/Poly.jl
test/generic/MPoly-test.jl

Adds a wild variety of evaluation functions for MPoly, lots of test cases and examples in the docs.

Mpoly evaluate general

---

docs/src/mpolynomial_rings.md
src/generic/GenericTypes.jl
src/generic/MPoly.jl

* Adds iterators
* Fixes exponent overflow checking

Mpoly iterators

---

src/generic/MPoly.jl

It otherwise does not work for fmpq_mpoly.

use ordering fct in mpoly change_base_ring

---

docs/src/mpolynomial.md
docs/src/mpolynomial_rings.md
src/generic/MPoly.jl

This PR:
* makes some MPoly functions more general (e.g. apply to Singular polys)
* uses iterators instead of random access in some functions
* rearranges the doc to reflect the above
* speeds up some functions by not reading the data multiple times

General mpoly

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

Alex reminded me that they were missing.

Add nrows and ncols for matrix spaces

---

docs/src/mpolynomial_rings.md
src/generic/MPoly.jl

* Makes a number of functions use iterators/build context
* Makes evaluation fully optional in interface

Mpoly use iter buildctx

---

src/generic/AbsSeries.jl
src/generic/Fraction.jl
src/generic/MPoly.jl
src/generic/Matrix.jl
src/generic/MatrixAlgebra.jl
src/generic/Poly.jl
src/generic/SparsePoly.jl

- Fix iszero for SparsePolynomial

- Change == 0 to iszero and == 1 to isone

---

src/AbstractAlgebra.jl

using try ... catch to check is difficult to use as one cannot export data from within this block

allow to test for accessors to be set

---

src/generic/AbsSeries.jl
src/generic/LaurentSeries.jl
src/generic/RelSeries.jl
test/generic/LaurentSeries-test.jl

This will sort out Peter Luschny's ticket 7^3 in Nemo, for AbstractAlgebra only. We have to fix Flint to fix it in Nemo itself.

Series divexact

---

test/generic/Matrix-test.jl

Add test for inversion of MatSpaceElems over ZZ

---

src/generic/MPoly.jl

Fix printing of MPoly

---

docs/src/module.md
docs/src/module_homomorphism.md
src/generic/GenericTypes.jl
src/generic/Matrix.jl
src/generic/Module.jl
src/generic/ModuleHomomorphism.jl
src/generic/QuotientModule.jl
src/generic/Submodule.jl
test/generic/ModuleHomomorphism-test.jl
test/generic/QuotientModule-test.jl

* Fix bug which caused the canonical projection to be computed incorrectly
* Remove premature optimisation which was buggy
* Use zero_matrix where possible
* Implement kernel of module homomorphisms

Modules kernel

---

docs/src/module.md
src/AbstractAlgebra.jl
src/AbstractTypes.jl
src/generic/GenericTypes.jl
src/generic/InvariantFactorDecomposition.jl
src/generic/Module.jl
test/generic/InvariantFactorDecomposition-test.jl

* InvariantFactorDecomposition -> snf
* invariant_factors now returns a vector instead of a matrix
* Fix issue with promote_rules mentioned by @kalmarek

Module cleanup

---

docs/src/finfield.md
docs/src/fraction.md
docs/src/fraction_fields.md
docs/src/free_module.md
docs/src/functional_map.md
docs/src/integer.md
docs/src/map_cache.md
docs/src/map_with_inverse.md
docs/src/matrix.md
docs/src/matrix_algebras.md
docs/src/matrix_spaces.md
docs/src/module.md
docs/src/module_homomorphism.md
docs/src/mpolynomial.md
docs/src/mpolynomial_rings.md
docs/src/ncpolynomial.md
docs/src/numberfield.md
docs/src/perm.md
docs/src/polynomial.md
docs/src/polynomial_rings.md
docs/src/puiseux.md
docs/src/quotient_module.md
docs/src/rational.md
docs/src/real.md
docs/src/residue.md
docs/src/residue_rings.md
docs/src/series.md
docs/src/series_rings.md
docs/src/submodule.md
src/generic/Fraction.jl

There is still an error building the manual, I remove the WIP once I resolved this.

WIP: Change more manual examples to use @repl

---

src/generic/MPoly.jl
test/generic/MPoly-test.jl

I had to disable some tests, because they are really failing. But I prefer first push this here.

Fix for #334

---

src/generic/SparsePoly.jl
test/generic/MPoly-test.jl

Fixes #357. I guess this was an oversight.
I know there used to be some ambiguities, but the tests pass (also for Nemo, Hecke).

Relax signature to fix #357

---

test/generic/ModuleHomomorphism-test.jl

Revert some workarounds that we introduced due to hangs in Julia that are now fixed in all versions of Julia.

Revert workarounds

---

docs/src/module.md
docs/src/module_homomorphism.md
src/AbstractAlgebra.jl
src/generic/ModuleHomomorphism.jl

The commits below explain what is being added here. Just some minor usability things.

Module extras

---

src/generic/Matrix.jl

This fix e.g.:
```julia
julia>  m = matrix(ZZ, 2, 0, [])
2 by 0 matrix[]
[]
```

fix show for some empty matrices

---

src/generic/MPoly.jl

Just because it's a shame to keep #358 open any longer.
Closes #358.

docs: replace some Array{T,1} by Vector{T}

---

src/generic/MPoly.jl

Fix bug in div when using immutable coefficient types.

---

src/generic/MPoly.jl

Closes https://github.com/Nemocas/Nemo.jl/issues/623.

Add hashing for abstract MPolys

---

src/generic/Module.jl

Fix the error observed in https://github.com/Nemocas/AbstractAlgebra.jl/pull/404.

Help inference in some list comprehensions

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

Closes https://github.com/Nemocas/Nemo.jl/issues/620

Add generalized matrix concatenation

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

One of the issues mentioned in @kirtsar's ticket.

Fix a bug in matrix coercion.

---

test/generic/Matrix-test.jl

cf. https://github.com/Nemocas/AbstractAlgebra.jl/pull/414#issuecomment-534977986

test result type for change_base_ring on matrices

---

test/generic/Matrix-test.jl

tentatively fix a test failure with map

---

src/generic/RelSeries.jl

Fix issue with printing of polynomials over power series over GF2.

---

src/generic/LaurentSeries.jl
test/generic/PuiseuxSeries-test.jl

Fix issue with inflate modifying input.

---

docs/src/matrix_spaces.md
src/generic/Matrix.jl

This will be useful to optimize `zero` for nemo matrices.

clarify how to extend similar and zero

---

.travis.yml
src/generic/Matrix.jl
test/generic/Matrix-test.jl

allow passing dimensions in matrix(ring, r, c, mat)

---

docs/src/mpolynomial.md
src/generic/MPoly.jl
test/generic/MPoly-test.jl

Remove evaluate with function argument

---

src/AbstractAlgebra.jl

`AbstractAlgebra.RR` is not a thing.

remove :RR from import_exclude

---

src/AbstractAlgebra.jl
test/generic/NCPoly-test.jl
test/generic/Poly-test.jl

By the way, this is not documented. Is someone using this syntax?

test R['x']['y'] syntax

---

src/generic/MPoly.jl
src/generic/Matrix.jl

Whilst there is no hard rule about where things should go in our generic files, there are some obvious patterns. I tried to make some of the patterns a little more consistent.
closes #468

Rearrange files

---

src/Rings.jl
src/generic/Poly.jl

Move change_base_ring and map to Poly.jl.

---

src/AbstractAlgebra.jl
src/Rings.jl
test/AbstractAlgebra-test.jl
test/NCRings-test.jl
test/Rings-test.jl
test/generic/MPoly-test.jl
test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl
test/generic/Poly-test.jl

Just a clean up of our testset output.

Rearrange tests

---

src/generic/MPoly.jl
src/generic/Poly.jl

Found by @raulepure when working on https://github.com/oscar-system/Singular.jl/pull/140
I will tag a patch release once this here is merged.

Fix bug in change_base_ring/map_coeffs

---

src/generic/AbsSeries.jl
src/generic/LaurentSeries.jl
src/generic/RelSeries.jl
test/generic/LaurentSeries-test.jl

Fixes https://github.com/Nemocas/AbstractAlgebra.jl/issues/484

Fix laurent add sub

---

test/AbstractAlgebra-test.jl
test/generic/Matrix-test.jl

For these simple functions, it doesn't seem to be needed to test multiple rings. Nonetheless, we don't have to test always the same ring, so we choose one randomly (among a set a predefined ones).

Matrix test: unary - and sub

---

docs/src/matrix.md
src/NCRings.jl
src/generic/Matrix.jl
test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl
test/generic/NCPoly-test.jl

require square matrices for one(::MatSpace), and add tests for #514

---

docs/src/matrix.md
src/AbstractAlgebra.jl
test/generic/Matrix-test.jl

And simplify the implementation of typed_hcat and typed_hvcat.

enable direct creation of literal column vectors

---

docs/src/mpolynomial.md

I would appreciate if this could be given priority and merged as soon as the lights are green, as a collaborator is waiting to be able to use the relevant documentation.

Fix a typo and a rendering error.

---

src/julia/Integer.jl
test/julia/Integers-test.jl

It was not throwing on inexact division.

fix divexact on integers

---

src/generic/Matrix.jl
src/generic/MatrixAlgebra.jl

Make aliasing rules same for MatrixAlgebras and MatrixSpaces.

Fix aliasing bug in MatrixAlgebra mutating operators.

---

docs/src/direct_sum.md
docs/src/free_module.md
docs/src/module_homomorphism.md
src/AbstractAlgebra.jl
src/generic/DirectSum.jl
src/generic/FreeModule.jl
src/generic/ModuleHomomorphism.jl
test/generic/DirectSum-test.jl

- fix inj/proj to support DirectSum(N, N)
- add hom()
- add basis
- add fancy creation of morphisms in this case

direct sum modules

---

src/generic/Poly.jl

change poly over Q -> poly over nf fails as the poly constructor does not accept Any[]

create list with proper type

---

src/AbstractAlgebra.jl

to be filled with life in Hecke/Oscar
currently not used at all in AA/Nemo to be minimally invasive

Force coerce

---

docs/src/index.md

doc: fix link to documentation

---

src/generic/Fraction.jl
test/generic/Fraction-test.jl

Fix ambiguity

---

src/generic/PermGroups.jl

fix #245, regression in hash(::Perm)

---

src/generic/MPoly.jl
test/generic/MPoly-test.jl

Fix evaluation/powering of MPoly and 0

---

src/generic/MPoly.jl

That addition in the old code was a showstopper. Not sure what this will break or what type instabilities this will introduce. Was the old code stable?

split the additions in evaluate

---

src/AbstractAlgebra.jl
src/Rings.jl

Closes https://github.com/Nemocas/AbstractAlgebra.jl/issues/607 and makes Simon happy. We cannot test it here, but it works locally and I will add a test in Nemo.

Implement sqrt fallback based on factor

---

docs/src/series_rings.md
src/AbstractAlgebra.jl
src/Deprecations.jl
src/generic/AbsSeries.jl
src/generic/LaurentSeries.jl
src/generic/PuiseuxSeries.jl
src/generic/RelSeries.jl
test/generic/AbsSeries-test.jl
test/generic/RelSeries-test.jl

AA changes for #615. Includes proper deprecations.

set_prec! -> set_precision!

---

src/generic/Poly.jl
test/generic/Poly-test.jl

The function looped forever if one tried to remove zero or a unit.
Also the tests were broken.

Fix remove (and its tests)

---

docs/src/matrix.md
src/generic/Matrix.jl

Fixes #70  (hopefully)
Also attempts to fix missing inv docstring for generic matrices.

Fix some docstrings.

---

docs/src/matrix.md
src/generic/Matrix.jl

Add example of hnf and docstrings/examples of snf.

---

docs/src/matrix.md

There was no corresponding ticket.

Add documentation examples for weak popov form.

---

src/generic/Residue.jl
test/generic/Residue-test.jl

Definititely do not support Z/0.

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

This takes care of #640 .
I added tests for popov and popov_with_transform (basically the same as for weak_popov), so #30 should also be fine now.

Fix popov form and add tests

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

This should fix the reduction issue in popov and popov_with_transform, which I mentioned in #640 .
Sorry for my faulty pull request from yesterday.

Fix reduction in Popov form

---

src/generic/FreeModule.jl
src/generic/Matrix.jl
test/generic/Matrix-test.jl

Suggested by Simon Brandhorst.

Add firstindex and lastindex (support A[1:end,2:3])

---

.travis.yml

Travis: test also on Julia 1.4 and 1.5

---

src/julia/GF.jl
test/julia/GFElem-test.jl

Fix + and - for GFElem{::Unsigned}

---

src/Rings.jl
test/generic/Poly-test.jl

Fix stack overflow in divexact_left/right.

---

test/generic/MatrixAlgebra-test.jl

Remove tests that have nothing to do with MatrixAlgebras.

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

Fix overdetermined LU and add tests.

---

docs/src/fields.md
docs/src/ncrings.md
docs/src/rings.md

Add documentation of NCRingElement, RingElement and FieldElement types.

---

test/generic/Matrix-test.jl

Improve rref tests.

---

src/generic/Matrix.jl
src/generic/MatrixAlgebra.jl
test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl

This changes solve_lu to can_solve_with_solution_lu.
The function now handles non-square and singular matrices.
Again, this is an internal function which does not appear in the documentation and is only used by inv over a field currently.

Solve_lu -> can_solve_with_solution_lu + non-square and singular cases.

---

src/generic/ResidueField.jl
test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl

@rfourquet Could you check I have done this correctly. The objective was to remove the unnecessary second argument which Nemo doesn't use in rand for its NumberField type. However I am unsure what the first "if" case of the rand function is for, so didn't change that. The code seems to work, but I'd prefer to know I did it correctly.

Make rand for NumberField behave as for Nemo.

---

test/generic/Fraction-test.jl
test/generic/LaurentPoly-test.jl
test/generic/LaurentSeries-test.jl
test/generic/MPoly-test.jl
test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl
test/generic/Module-test.jl
test/generic/NCPoly-test.jl
test/generic/Poly-test.jl
test/generic/PuiseuxSeries-test.jl
test/generic/RelSeries-test.jl
test/generic/Residue-test.jl
test/generic/ResidueField-test.jl
test/julia/Floats-test.jl
test/julia/GFElem-test.jl
test/julia/Integers-test.jl
test/julia/Rationals-test.jl
test/runtests.jl

This tests more systematically the random API for each case. This is similar to a recent change in Nemo.

factor out rand testing code

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

* Fix major bug in can_solve_with_solution_fflu
* improve test code for same
* Fix major bug in can_solve_with_solution_lu
* improve test code for same
* make solve_interpolation handle non-square/singular matrices
* solve_with_det -> can_solve_with_solution_with_det
* solve_interpolation -> can_solve_with_solution_interpolation
* test code for latter
* make solve_rational handle non-square/singular matrices
* improve test code for same

Solve interpolation

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

* Handle bad evaluation points in can_solve_with_solution_interpolation (bug fix)
* Hook can_solve_with_solution_interpolation up to can_solve_with_solution for matrices over fraction fields of polynomial rings
* More tests
* Deal with some incorrect return values (bug fix)

Solve interp

---

src/generic/Matrix.jl

I found the LU and FFLU algorithms I used in the literature. This PR adds comments with a reference and some notes on the choices I made for future reference.

Lu fflu references

---

src/generic/MPoly.jl

A long running job was crashing my computer because of this. I refactored it a bit so that the evaluate function creates the SparsePolyRing only once.

Don't cache the SparsePolyRing when evaluating MPoly

---

docs/src/constructors.md
src/generic/AbsSeries.jl
src/generic/LaurentSeries.jl
src/generic/Matrix.jl
src/generic/PuiseuxSeries.jl
src/generic/RelSeries.jl

Avoid \mbox, as MathJax does not like it

---

.github/workflows/CI.yml
docs/src/residue.md

Also fix Codecov coverage tracking for outside PRs

Track doctest code coverage

---

Project.toml

So we can remove the stuff in Hecke that was moved.

Prepare for new version

---

src/Generic.jl

Import factor into Generic (so that we extend it)

---

src/PrettyPrinting.jl
test/PrettyPrinting-test.jl

simple explanation is Base.operator_precedence(://) > Base.operator_precedence(:/)

increase precedence of //

---

src/generic/RelSeries.jl
test/generic/RelSeries-test.jl

Fix addeq! for relative series to not read past end of output.

---

docs/src/matrix.md
src/generic/Matrix.jl

Fixed minor things in the documentation.

Matrix documentation fix

---

src/generic/Fraction.jl
src/generic/Misc/Frac.jl
test/generic/Fraction-test.jl

Docstrings would essentially duplicate those in MPoly, so I decided to add comments only, not actual docstrings. Let me know if this is not what you prefer and I can change it.
The current MPoly docstrings do essentially apply to these methods unchanged, I think.

Move derivative methods from Misc to Fraction.jl and add tests.

---

src/AbstractAlgebra.jl

There are some problems and we want to do a release, so lets disable it for now.

Disable WeakValueDict

---

src/generic/RelSeries.jl

Fix some doctest things

---

docs/make.jl
docs/src/laurent_polynomial.md
src/generic/LaurentPoly.jl

add docs for Laurent polynomials

---

src/AbstractAlgebra.jl

Harmless issue, but may as well fix.

Remove duplicate import/export of coefficients.

---

docs/src/matrix.md
docs/src/series.md
src/generic/Matrix.jl

Documenter.jl was complaining about these docs being missing.

Fix some missing docs.

---

src/generic/Matrix.jl

Fixes #788 
I ran the test for 10,000 iterations. Definitely fixed.

Fix bug in can_solve_with_solution_interpolation.

---

docs/src/mpolynomial.md
docs/src/polynomial.md
src/generic/MPoly.jl
src/generic/Misc/Poly.jl
src/generic/Poly.jl
test/generic/MPoly-test.jl
test/generic/Poly-test.jl

* Move inflate/deflate from Misc to Poly.jl
* Implement deflation for Poly
* Implement inflate/deflate as per MPoly for Poly
* Implement inflate/deflate as per Poly for MPoly
* Add docs and tests

Move inflate/deflate from Misc to Poly.jl

---

src/generic/Misc/Poly.jl
src/generic/Poly.jl
test/generic/Poly-test.jl

I assume everyone is happy with the fact that it doesn't necessarily return a poly of the given degree, but up to that degree (depending on how many zero coefficients are randomly generated). The existing rand function also has this property.

Move rand from Misc to Poly.jl.

---

src/generic/MPoly.jl

I am just fixing one instance: there are lots more mistakes of this kind
https://github.com/Nemocas/AbstractAlgebra.jl/issues/833

fix to_univariate

---

docs/src/series.md
src/generic/LaurentSeries.jl
src/generic/RelSeries.jl
test/generic/LaurentSeries-test.jl

* Fixes bug in mul! for LaurentSeries (found by test code for exp/log)
* Implement log for LaurentSeries over field
* Implement exp for LaurentSeries over field
* Implement derivative for LaurentSeries
* Implement integral for LaurentSeries
* Add test code
* Minor formatting fix for docs

Implement exp/log/derivative/integral for LaurentSeries

---

src/generic/AbsSeries.jl
src/generic/RelSeries.jl
test/generic/AbsSeries-test.jl
test/generic/RelSeries-test.jl

* Fixes aliasing bug in mul! for AbsSeries and RelSeries
* Fixes access bug in add! for RelSeries
* Adds missing function add!
* Adds test code for AbsSeries and RelSeries unsafe operators
Fixes #777

Fix aliasing bug in mul! and add add!.

---

docs/src/puiseux.md
src/generic/PuiseuxSeries.jl
test/generic/PuiseuxSeries-test.jl

* Add derivative and integral for PuiseuxSeries
* Add log for Puiseux series
* Add better tests for exp/log
* Add set_valuation!/set_precision! for PuiseuxSeries
Fixes #787

Puiseux derivative, integral, log, set_valuation/precision

---

src/generic/AbsSeries.jl
src/generic/RelSeries.jl

Assign the return value of set_precision!/_valuation!/_length!/coeff!.

---

src/generic/Matrix.jl
test/generic/Matrix-test.jl

Don't mutate matrix entries in add_row/column! and multiply_row/column!.

---

src/generic/MPoly.jl
src/generic/Poly.jl
test/generic/AbsMSeries-test.jl
test/generic/AbsSeries-test.jl
test/generic/Fraction-test.jl
test/generic/FreeModule-test.jl
test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl
test/generic/NCPoly-test.jl
test/generic/Poly-test.jl
test/generic/Residue-test.jl

@thofma and I modified all the existing tests for this change.
In theory this is breaking for other repos (Nemo, Hecke particularly). We have not addressed any breakage there yet.
Fixes #839

Make rand for PolyElem return random elements in the exact range given

---

docs/src/series.md
docs/src/series_rings.md
src/generic/AbsSeries.jl
src/generic/RelSeries.jl
test/generic/AbsSeries-test.jl
test/generic/RelSeries-test.jl

Fixes #15 
Do I get a prize for fixing one of the earliest tickets?

Series map_coefficients and change_base_ring

---

docs/src/ncrings.md

Deduplicate NCRing interface documentation.

---

docs/src/rings.md

Clarify coercion/promotion system.

---

src/generic/Misc/Poly.jl

Fixes https://github.com/Nemocas/Nemo.jl/issues/1068

Fix roots function

---

docs/src/mpolynomial_rings.md
docs/src/residue_rings.md
src/generic/AbsSeries.jl
src/generic/Poly.jl
src/generic/RelSeries.jl
src/generic/Residue.jl
test/generic/Residue-test.jl

Degree doc fix

---

src/generic/FunctionField.jl
src/generic/RationalFunctionField.jl

These are the promised improvements for how rationalisation (and equality checking) are handled for function fields, to bring it into line with FractionField.
Technically there as a bug fixed, albeit by removing the broken code.
I also slightly improved the performance of norm by doing a less expensive rationalisation before the full one, if this doesn't lead to duplication of the computation.

Function field rationalisation improvements

---

docs/src/polynomial.md
src/generic/Misc/Poly.jl
test/generic/Poly-test.jl

Probably still completely broken (see [1]), but at least it's broken much better now.
[1] https://github.com/Nemocas/AbstractAlgebra.jl/issues/883

Clean up poly_to_power_sums and power_sums_to_poly a little.

---

src/NCRings.jl
test/julia/Integers-test.jl

Fixes https://github.com/Nemocas/Nemo.jl/issues/1080

check_parent fallback

---

docs/src/finfield.md
docs/src/residue_rings.md
src/Residue.jl
src/julia/GF.jl
test/generic/Residue-test.jl
test/julia/GFElem-test.jl

This is the abstract algebra complement to https://github.com/Nemocas/Nemo.jl/pull/1089 and documents the lift function defined therein.

Define lift for residues and document.

---

src/MPoly.jl

This actually works with singular now.

Fix to univariate

---

src/PrettyPrinting.jl
test/PrettyPrinting-test.jl

always canonicalize recursively

---

docs/Project.toml
docs/create_type_diagramms.jl
docs/make.jl
docs/src/assets/elements_diagram.svg
docs/src/assets/parents_diagram.svg
docs/src/misc.md
docs/src/visualizing_types.md

Closes #922.
CC: @albinahlback

Remove Kroki as a runtime dependency of documentation

---

src/Generic.jl
src/Poly.jl
src/generic/Poly.jl

This contributes to the karatsuba part of #761.

Make use of karatsuba where practical.

---

src/generic/AbsSeries.jl

If this works out ok I'll also make use of it in mul! and repeat the whole exercise for RelSeries (in later PRs).

Make use of DensePoly.mullow_fast! in AbsSeries multiplication.

---

src/AbsSeries.jl
src/RelSeries.jl
test/generic/AbsSeries-test.jl
test/generic/RelSeries-test.jl

This is the steal parent concept that we already introduced for polynomials, rolled out for series.
There will be an accompanying Nemo version, and this should be considered breaking until that is merged (after this).

Series steal parent

---

src/generic/AbsSeries.jl
test/generic/RelSeries-test.jl

Abs series use mullow_fast! in mul!

---

src/generic/RelSeries.jl

See https://github.com/Nemocas/AbstractAlgebra.jl/issues/914

Use mullow_fast! in rel series * and mul!

---

src/generic/Fraction.jl

Currently polynomials over Q and elements of Q are canonicalised. But fraction fields of polynomials over Q can end up with horrendous coefficients due to lack of canonicalisation. We attempt to canonicalise a little more aggressively.

Attempt to canonicalise more in fraction fields

---

src/ResidueField.jl

version. The complex one actually does not work in all cases...
The problem was a weired ring where the base ring was not a field, but
did not have a base_ring anymore...

fix the doc string and provide a clean, recursive

---

docs/src/fraction.md
docs/src/fraction_interface.md
docs/src/matrix.md
docs/src/matrix_interface.md
docs/src/module.md
docs/src/module_interface.md
docs/src/mpoly_interface.md
docs/src/mpolynomial.md
docs/src/poly_interface.md
docs/src/polynomial.md
docs/src/residue.md
docs/src/residue_interface.md
docs/src/series.md
docs/src/series_interface.md

Move interface examples to user docs and deduplicate

---

docs/src/field_interface.md
docs/src/fraction.md
docs/src/map.md
docs/src/map_cache.md
docs/src/map_interface.md
docs/src/matrix_interface.md
docs/src/module.md
docs/src/module_interface.md
docs/src/mpoly_interface.md
docs/src/mpolynomial.md
docs/src/mseries.md
docs/src/ncpolynomial.md
docs/src/poly_interface.md
docs/src/polynomial.md
docs/src/residue.md
docs/src/ring_interface.md
docs/src/series_interface.md

Use Documenter notes for important points.

---

docs/src/ring_interface.md

Add minimal Ring Interface example

---

docs/make.jl
docs/src/rand.md

Add rand interface documentation

---

docs/src/integer.md
docs/src/mpoly_interface.md
docs/src/polynomial.md
docs/src/ring_interface.md
src/AbsSeries.jl
src/Fraction.jl
src/Matrix.jl
src/MatrixAlgebra.jl
src/NCPoly.jl
src/NCRings.jl
src/Poly.jl
src/RelSeries.jl
src/Residue.jl
src/ResidueField.jl
src/Rings.jl
src/algorithms/MPolyFactor.jl
src/generic/AbsMSeries.jl
src/generic/FunctionField.jl
src/generic/LaurentSeries.jl
src/generic/MPoly.jl
src/generic/Misc/Localization.jl
src/generic/PuiseuxSeries.jl
src/generic/RationalFunctionField.jl
src/generic/SparsePoly.jl
src/julia/Float.jl
src/julia/GF.jl
src/julia/Integer.jl
src/julia/Rational.jl
test/generic/Poly-test.jl
test/julia/Integers-test.jl

This adds isdivisible_by for integers and adds the check=true keyword arg for divexact everywhere (and makes the tests pass).

Divides functions

---

src/AbsSeries.jl
src/RelSeries.jl
test/generic/AbsSeries-test.jl
test/generic/RelSeries-test.jl

Add asymptotically fast series divexact (using inv)

---

src/julia/Integer.jl
test/julia/GFElem-test.jl

See https://github.com/Nemocas/Nemo.jl/issues/1038 for details.

Export isprobable_prime

---

test/Rings-conformance-tests.jl

Also put the euclidean ring interface tests into a testset of their
own.

Print type being tested in conformance tests

---

test/Rings-conformance-tests.jl

Whatever equality means, I hope we can agree that these should be true.

forgot powering in Ring interface

---

docs/src/ring_interface.md

add expressify example and how to test

---

docs/src/euclidean_interface.md
docs/src/ring_interface.md
src/Rings.jl
src/algorithms/GenericFunctions.jl
test/Rings-conformance-tests.jl
test/Rings-test.jl
test/algorithms/GenericFunctions-test.jl
test/julia/Integers-test.jl

provide some generic functions to reduce required ring interface

---

Project.toml

I need some of the recent changes downstream.

Bump version to 0.22.2

---

docs/src/euclidean_interface.md

clarify mod function

---

src/AbstractAlgebra.jl
test/AbstractAlgebra-test.jl
test/Special-test.jl

CC @fieker @thofma 
See also https://github.com/oscar-system/Oscar.jl/issues/843

Add `get_special!` and some tests

---

.github/workflows/CI.yml
Project.toml
appveyor.yml
docs/src/index.md
src/AbstractAlgebra.jl
src/WeakValueDict.jl
test/WeakValueDict-test.jl
test/generic/Matrix-test.jl
test/generic/Perm-test.jl
test/rand.jl

Note that Julia 1.6 is the new LTS release for Julia.
Resolves #1062

Require Julia >= 1.6

---

src/AbsSeries.jl
src/RelSeries.jl
src/julia/Float.jl
test/generic/AbsSeries-test.jl
test/generic/RelSeries-test.jl
test/julia/Floats-test.jl

* Add issquare, issquare_with_sqrt for Abs/RelSeries
* Add sqrt_classical_char2 for Abs/RelSeries
* Add issquare, issquare_with_sqrt for Float64
* Add test code for mod p series sqrt (incl. p = 2)

Sqrt series functions

---

src/generic/LaurentSeries.jl
test/generic/LaurentSeries-test.jl

I will add characteristic 2 code and PuiseuxSeries code in later PRs.

Add issquare and issquare_with_sqrt functions for LaurentSeries

---

src/AbstractAlgebra.jl
src/Attributes.jl

Remove get_special/set_special compatibility

---

src/Fraction.jl
src/FreeAssAlgebra.jl
src/generic/FunctionField.jl
src/generic/PuiseuxSeries.jl
src/generic/RationalFunctionField.jl

expressify: always pass context to recursive calls

---

docs/src/ring_interface.md

See issue #1099
CC @HechtiDerLachs﻿

Improve expressify docs a bit

---

docs/src/ring_interface.md
src/AbstractAlgebra.jl
src/PrettyPrinting.jl
src/generic/Misc/Localization.jl

Also remove displayed_with_minus_in_front, show_minus_one

Breaking: remove needs_parentheses

---

Project.toml

What needs to be merged:
What shall we do about

Bump version to 0.24.0

---

docs/src/free_module.md

Add documentation for the type of elements of a free module

---

docs/src/mpolynomial.md
src/generic/MPoly.jl
test/generic/MPoly-test.jl

Fixes #1043 
Nothing seems to break in AA. Let's see what CI says about everything else.

Reset build context after finish

---

src/AbstractAlgebra.jl

Nothing will be using these anymore once https://github.com/Nemocas/Nemo.jl/pull/1268 is merged.
Contains PR #1129 for simplicity (the changes overlap).

BREAKING: Remove create_accessors & get_handle

---

docs/src/mpolynomial.md
src/MPoly.jl
src/generic/MPoly.jl

Also adds some other docstrings (some of which are necessarily unused, as per the comments on #1045).

Add some docstrings to fix the original issue reported in #1045

---

src/NCPoly.jl

Nothing uses it or references it

Remove ismonomial_monomial

---

src/AbstractAlgebra.jl
src/AliasMacro.jl
test/AliasMacro-test.jl

Extracted from PR #1145, under the theory that this can be merged immediately.

Add macro @alias

---

docs/src/matrix.md
src/Matrix.jl
test/generic/Matrix-test.jl

- also fix it in characteristic 2
- add tests
- document it

Rename isskew_symmetric to is_skew_symmetric

---

test/generic/Matrix-test.jl

Fixes #1158 
The test couldn't be expected to pass all the time, so I changed it by adding a rank check.

Fix a failing test in Matrix module

---

.github/workflows/CI.yml
docs/Project.toml
docs/make.jl
docs/src/matrix.md
src/AbstractAlgebra.jl
src/Generic.jl
src/Matrix.jl
src/NCRings.jl
src/generic/Matrix.jl
src/generic/MatrixAlgebra.jl

- docs: ensure AbstractAlgebra is available in jldoctests
- docs: upgrade to latest Documenter.jl
- Move a bunch of examples into docstrings
- docs: add a missing space

Some doc tweaks

---

src/generic/Ideal.jl

resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1171

remove errant alligator

---

src/generic/LaurentPoly.jl
test/generic/LaurentPoly-test.jl

fixes https://github.com/Nemocas/AbstractAlgebra.jl/issues/1182

fix is_unit for LaurentPolyWrap

---

src/Fraction.jl
src/generic/FactoredFraction.jl
src/generic/Fraction.jl
test/generic/FactoredFraction-test.jl
test/generic/Fraction-test.jl

Fix Fraction to accept rational as operand to adhoc +, -, *, ==.

---

docs/src/euclidean_interface.md
src/AbstractAlgebra.jl
src/algorithms/GenericFunctions.jl
test/julia/Integers-test.jl

I don't care about the arrangement of the args in crt(r1, m1, r2, m2)

add generic crt

---

src/PrettyPrinting.jl
test/PrettyPrinting-test.jl

pretty print comparison operators

---

src/algorithms/MPolyEvaluate.jl
test/algorithms/MPolyEvaluate-test.jl

The first of @hechtiderlachs evaluation, cleanedup a bit and made slightly more friendly on the GC

add HechtiDerLachs' log_evaluate

---

Project.toml

Bump to 0.27.7

---

src/generic/UnivPoly.jl
test/generic/UnivPoly-test.jl

This fixes #1245. I hope I didn't miss anything.

fix evaluate of UnivPoly

---

src/generic/FreeAssAlgebra.jl
test/generic/FreeAssAlgebra-test.jl
test/generic/MPoly-test.jl

pretty self-explanatory, implemented analogously to MPoly and Poly

add `canonical_unit` and `change_base_ring` for `FreeAssAlgebra`

---

README.md
docs/src/index.md

The domain lapsed and is now owned by spammers

Replace links to nemocas.org

---

src/Aliases.jl

Add @alias UnivPolyRing UniversalPolyRing for backwards compatibility

---

src/AbstractAlgebra.jl
src/Generic.jl

I would also consider aggregating all (top-level) import & export statements into a single file if nobody objects? (esp. @thofma @fieker)

Change many import/export statements to be on a single line

---

src/AliasMacro.jl
src/generic/YoungTabs.jl

x-ref: https://github.com/oscar-system/Oscar.jl/pull/2083

jldoctest: add missing end markers

---

test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl

Resolves #1158
Same fix as in d595c41d814789b110a28db07b8df504609d44da from PR #1161

Fix spurious test failure in pseudo_inv

---

src/AbstractAlgebra.jl

export Ring

---

Project.toml
src/algorithms/MPolyFactor.jl

Introduced in #1322 (cc: @fingolfin). I will add an upstream test once it is merged.

Fix bug in mpoly factorization

---

Project.toml
src/AbstractAlgebra.jl
src/PrettyPrinting.jl

Add the unicode printing option

---

src/AbsSeries.jl
src/MPoly.jl
src/Matrix.jl
src/MatrixAlgebra.jl
src/NCPoly.jl
src/NCRings.jl
src/Poly.jl
src/RelSeries.jl
src/algorithms/MPolyFactor.jl
src/generic/AbsSeries.jl
src/generic/GenericTypes.jl
src/generic/LaurentSeries.jl
src/generic/MPoly.jl
src/generic/Matrix.jl
src/generic/MatrixAlgebra.jl
src/generic/NCPoly.jl
src/generic/Poly.jl
src/generic/PuiseuxSeries.jl
src/generic/RelSeries.jl
src/generic/SparsePoly.jl
test/generic/MPoly-test.jl
test/generic/Matrix-test.jl

In some cases this changes from an abstract to a concrete type, and thus
improves type stability

Change Array to Vector or Matrix

---

docs/src/matrix_interface.md
src/AbstractAlgebra.jl
src/Matrix.jl
test/generic/Matrix-test.jl

Resolves #1266.
Specialized methods will be introduced in nemocas/Nemo.jl#1455.

Add `is_zero_entry` for matrices

---

src/Matrix.jl

Also tweak the kernel docstring

Fix a typo in the right_kernel doc string

---

src/Matrix.jl

Resolves https://github.com/oscar-system/Oscar.jl/issues/1669.

Add parent check to matrix constructor

---

src/MPoly.jl
test/generic/MPoly-test.jl

Resolves https://github.com/oscar-system/Oscar.jl/issues/2331.

Add adhoc dispatch for `evaluate(::MPolyElem, vals)`

---

Project.toml
src/generic/GenericTypes.jl

Also bump version to get a release before we do the breaking one.

Add attribute to Laurent multivariate polynomials

---

docs/src/polynomial.md
src/Deprecations.jl
src/generic/Misc/Poly.jl

Resolves parts of https://github.com/thofma/Hecke.jl/issues/641.
Must be merged together with https://github.com/thofma/Hecke.jl/pull/1094, https://github.com/Nemocas/Nemo.jl/pull/1486 and https://github.com/oscar-system/Oscar.jl/pull/2433.

Change argument order in `factor` and `roots`

---

docs/src/laurent_mpolynomial.md
docs/src/mpolynomial.md
docs/src/polynomial.md
docs/src/rand.md
docs/src/ring_interface.md
docs/src/series.md
src/AbsMSeries.jl
src/FreeAssAlgebra.jl
src/LaurentMPoly.jl
src/MPoly.jl
src/NCPoly.jl
src/Poly.jl
src/RelSeries.jl
src/generic/LaurentSeries.jl
src/generic/Matrix.jl
src/generic/PuiseuxSeries.jl
src/generic/UnivPoly.jl
src/julia/Float.jl
test/algorithms/GenericFunctions-test.jl

Solve the AbstractAlgebra part of [Oscar.jl#2447](https://github.com/oscar-system/Oscar.jl/issues/2447).

Allow `AbstractUnitRange`

---

test/Rings-test.jl

The same include is in the first line of `test/Rings-test.jl`.

Remove duplicate include

---

src/WeakValueDict.jl

Also part of PR #1419 but I think we can merge this right away, while that PR may need some more baking

Fix some import issues in WeakValueDict

---

docs/src/direct_sum.md
docs/src/map_with_inverse.md
docs/src/module.md
docs/src/module_homomorphism.md
docs/src/quotient_module.md
docs/src/submodule.md
src/Map.jl
src/ModuleHomomorphism.jl
src/generic/Map.jl
src/generic/MapWithInverse.jl
src/generic/ModuleHomomorphism.jl
test/generic/Map-test.jl
test/generic/MapWithInverse-test.jl
test/generic/ModuleHomomorphism-test.jl

Also extract some common patterns in the printing. It seems most detailed map printing functions could share code...
Finally add tests for all these show methods. This uncovered a few more minor issues that were fixed.
CC @simonbrandhorst

Unify map printing

---

src/julia/Matrix.jl

... for convenience of some users.
Resolves https://github.com/Nemocas/Nemo.jl/issues/1286

Add `Matrix{U}(A::MatrixElem{T})` conversion method

---

docs/src/ring_interface.md

@thofma said on slack that this is wrong in the docs.

Fix typo in ring interface docs

---

Project.toml
docs/Project.toml
test/Project.toml

Adapt for upcoming changes in julia nightly, see:
https://discourse.julialang.org/t/psa-compat-requirements-in-the-general-registry-are-changing/104958

Add compat entries for all deps (even stdlibs)

---

src/generic/LaurentSeries.jl
test/generic/FreeAssAlgebraGroebner-test.jl

- FreeAssociativeAlgebra -> free_associative_algebra
- LaurentSeriesRing -> laurent_series_ring

Use current names for two functions

---

docs/src/mpolynomial.md
docs/src/mseries.md
src/AbsMSeries.jl
src/FreeAssAlgebra.jl
src/LaurentMPoly.jl
src/MPoly.jl

The line above will only join `", "` in between each symbol, not after the last one.

Fix printing multivariate polynomial ring with many variables

---

src/generic/AhoCorasick.jl

Resolve some cases were the Julia compiler may not be able to fully
deduce the type of certain variables

AhoCorasickAutomaton: resolve JET issues

---

src/AbstractAlgebra.jl
src/LaurentSeries.jl
src/NCPoly.jl
src/generic/FunctionField.jl
src/generic/GenericTypes.jl
src/generic/NumberField.jl

Taken from #1360 as this is now totally orthogonal to the remaining code there.

Clean up some univariate constructors

---

docs/src/mpolynomial.md
docs/src/mseries.md
src/AbsMSeries.jl
src/FreeAssAlgebra.jl
src/LaurentMPoly.jl
src/MPoly.jl

Just so that we have a working downstream CI.

Revert "Fix printing multivariate polynomial ring with many variables (#1476)"

---

Project.toml

To be merged with (resp. before) the other breaking changes, once they are ready

Version 0.34.0-DEV

---

src/generic/MatrixAlgebra.jl
test/generic/MatrixAlgebra-test.jl

Also add a test for it and `charpoly(::MatAlgElem)`.
Resolves #1504

Implement `minpoly(::MatAlgElem)`

---

docs/src/polynomial.md

docs: remove duplicate entry for evaluate

---

src/NemoStuff.jl
src/generic/LaurentSeries.jl
src/generic/PuiseuxSeries.jl

The reduction of one type parameter should make the code a slither faster to compile.

Optimize some dispatches of `*_type`

---

src/generic/Ideal.jl

Fixes #1530
No test added, if someone wants it, please add one yourself.

Fix show(Union{}[])

---

docs/src/integer.md
docs/src/rational.md
src/AbstractAlgebra.jl
src/Aliases.jl
src/julia/Integer.jl
src/julia/Rational.jl
test/julia/Integers-test.jl
test/julia/Rationals-test.jl

Reverts Nemocas/AbstractAlgebra.jl#1529 until the next breaking release.

Revert "Streamline `is_power` for julia and AA types..."

---

src/AbstractAlgebra.jl
src/Matrix.jl

Resolves #1531
CC @fieker @thofma

Improve docs for is_lower_triangular and more

---

src/generic/AbsMSeries.jl
src/generic/Fraction.jl
src/generic/LaurentMPoly.jl
src/generic/MPoly.jl
src/generic/RationalFunctionField.jl
test/generic/Fraction-test.jl
test/generic/RationalFunctionField-test.jl

Also a few gens and gen methods
Those for `FracField` are moved here from Oscar.jl

Add a bunch of missing ngens method

---

docs/src/matrix.md
src/AbstractAlgebra.jl
src/broadcasting.jl
test/Rings-test.jl
test/broadcasting-test.jl

Probably still a bit rough around the edges. Let's see how it fares in practice.

feat: add broadcasting for MatElem

---

Project.toml

chore: set version to `0.36.0-DEV`

---

Project.toml
docs/src/perm.md
src/AbstractAlgebra.jl
src/AbstractTypes.jl
src/Aliases.jl
src/Generic.jl
src/Groups.jl
src/generic/PermGroups.jl
test/Groups-conformance-tests.jl
test/Project.toml
test/generic/PermGroupAPI-test.jl

This is work in progress. Among other things, we need to add a few
of generic fallbacks that were provided previously by GroupsCore.
Closes #1525

Excise GroupsCore dependency

---

Project.toml

once everything else is merged

chore: update to 0.36.0

---

Project.toml
src/Groups.jl
test/Groups-conformance-tests.jl

Very stupid mistake in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1567 to be fixed asap

Fixup `div_left` and `div_right` for groups

---

Project.toml
src/Groups.jl

See https://github.com/Nemocas/Nemo.jl/pull/1637#issuecomment-1910810349

Rewrite `order(::Group)` to allow for piracy by Nemo

---

src/Solve.jl
test/Solve-test.jl

Some adjustments to the new linear solving, now that I'm using it in Nemo. (Probably more to come.)

Adjustments to the new linear solving

---

docs/create_type_diagramms.jl
docs/make.jl
docs/src/assets/elements_diagram.svg
docs/src/assets/parents_diagram.svg
docs/src/matrix.md
docs/src/matrix_algebras.md
docs/src/matrix_interface.md
docs/src/mpolynomial.md
docs/src/ncpolynomial.md
src/AbstractAlgebra.jl
src/AbstractTypes.jl
src/FreeAssAlgebra.jl
src/Matrix.jl
src/MatrixAlgebra.jl
src/fundamental_interface.jl
src/generic/GenericTypes.jl
src/generic/Matrix.jl
src/generic/MatrixAlgebra.jl
test/NCRings-test.jl
test/Rings-conformance-tests.jl
test/generic/MPoly-test.jl
test/generic/Matrix-test.jl
test/generic/MatrixAlgebra-test.jl
test/generic/NCPoly-test.jl

- MatAlg -> MatRing
- MatAlgElem -> MatRingElem
- MatrixAlgebra -> matrix_ring

feat: rename MatrixAlgebra to MatrixRing

---

src/AbstractAlgebra.jl
src/NemoStuff.jl
src/generic/Misc/Localization.jl

See https://hackmd.io/nRnyfrSxTVe5CzXidB1cBQ?both#Nemo. I just noticed this actually has to be changed in AA instead of Nemo.

feat: rename localizations

---

src/Solve.jl

I was confused about what `:left` and `:right` mean again.
(And I'm really struggling with the wording of these error messages; maybe somebody has a better idea?)

Adjust error messages

---

Project.toml
src/MPoly.jl

Currently not tested. I'll mark as ready to review once tested against Oscar locally.

Update Mpoly printing

---

Project.toml
src/MPoly.jl

Reverts Nemocas/AbstractAlgebra.jl#1589
as discussed with @thofma and @joschmitt

Revert "Update Mpoly printing"

---

docs/src/misc.md
src/AbstractAlgebra.jl
src/PrettyPrinting.jl

No code changes, just moving it.
In the next step (follow-up PR based on this), I want to tackle some parts of https://github.com/oscar-system/Oscar.jl/pull/3288#issuecomment-1921290702

Move special printing macros to `PrettyPrinting`

---

test/AliasMacro-test.jl
test/Project.toml

Resolves #1608 with the workaround proposed in https://github.com/JuliaLang/julia/issues/53349#issuecomment-1946962233.

Fix `@alias` test on nightly

---

docs/src/univpolynomial.md
src/AbstractAlgebra.jl
src/Aliases.jl
src/Deprecations.jl
src/UnivPoly.jl
src/generic/UnivPoly.jl
test/generic/UnivPoly-test.jl

Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/1624

Rename `UniversalPolynomialRing` to `universal_polynomial_ring`

---

Project.toml
src/Map.jl
test/generic/Map-test.jl

Resolves https://github.com/oscar-system/Oscar.jl/issues/3528

Make Map broadcastable

---

Project.toml
src/Matrix.jl

- remove the zero argument versions of vcat and hcat

fix: make compiler happier

---

LICENSE.md
src/Groups.jl
test/Groups-conformance-tests.jl

This is a first draft. I may have overlooked files, and I am sure the message could be better.
Also I am not 100% sure how to correctly state the licensing situation. I think our existing LICENSE.md file may need a change, too (e.g. the fixed list of authors there...)
@kalmarek please let me know what you think about this, what you'd like to have changed (and sorry for the long delay)

Credit GroupsCore.jl for origin of groups interface

---

.JuliaFormatter.toml
.editorconfig

https://github.com/Nemocas/Nemo.jl/pull/1698 for AA

Copy the formatting configs from Oscar.jl

---

src/generic/GenericTypes.jl
src/julia/JuliaTypes.jl

For now I excluded modules and ideals from this.

Make more parent types attribute storing

---

src/PrettyPrinting.jl

... so it doesn't look weird in the generated docs

doc: fix get_name indentation

---

src/Attributes.jl
test/Attributes-test.jl

Not sure if this had user facing effects.

Fix `_is_attribute_storing_type`

---

src/PrettyPrinting.jl
test/PrettyPrinting-test.jl

Nothing other than the test being updated here sets this anyway

expressify: rename :terse -> :terse_level

---

src/Solve.jl

Removes some workarounds to the linear solving that were introduced to stay compatible with OSCAR 1.0.
This will first of all break Nemo. ~Until I have a working branch there, I leave this here as draft. Maybe I need to change something again.~

Breaking changes for linear solving

---

src/generic/Misc/Localization.jl

Turns out we have zero tests for that in AA... but Nemo does have some

Fix base_ring_type for LocalizedEuclideanRing

---

src/AbstractAlgebra.jl
src/Aliases.jl

As explained in the respective comments.

Change things that waited for a breaking release

---

Project.toml

Still waiting for the following PRs to be merged before:
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1692

chore: Bump version to 0.41.0

---

Project.toml
src/generic/DirectSum.jl
src/generic/imports.jl

This was missed in https://github.com/Nemocas/AbstractAlgebra.jl/pull/1675.

Merge hom and Generic.hom

---

Project.toml
src/Generic.jl
src/exports.jl
src/generic/DirectSum.jl
src/generic/exports.jl

cf. https://github.com/oscar-system/Oscar.jl/pull/3667#issuecomment-2091079080

Try to sort out the homs

---

docs/src/direct_sum.md
src/Map.jl
src/ModuleHomomorphism.jl
src/generic/FreeModule.jl
src/generic/Map.jl
src/generic/MapWithInverse.jl
src/generic/ModuleHomomorphism.jl
src/generic/Submodule.jl

- **Print (co)domain terse when oneline printing maps**
- **Use @show_name/_special for Submodule printing**

More printing tweaks

---

Project.toml

Needed for https://github.com/thofma/Hecke.jl/pull/1514/files#r1603436406

chore: Bump to 0.41.5

---

docs/src/polynomial.md

Resolves https://github.com/oscar-system/Oscar.jl/issues/3843

Remove `PolyRing(::Ring)` from docs

---

src/misc/VarNames.jl
test/generic/MPoly-test.jl

Support `@polynomial_ring(QQ, 2)` discussed in #1762

---

src/Poly.jl

Related to https://github.com/thofma/Hecke.jl/pull/1567

Small optimization

---

Project.toml

So that we can use #1731 in Oscar.

chore: tag 0.42.1

---

src/Ideal.jl

- pass on keyword arguments
- generalize to NCRingElement

feat: generalize ideal(...) fallbacks

---

.github/workflows/CI.yml
.github/workflows/hecke.yml
.github/workflows/nemo.yml
.github/workflows/oscar.yml
.github/workflows/singular.yml

Cf. https://github.com/oscar-system/Oscar.jl/issues/4072

Add daily jobs 

---

Project.toml

We already have some changes lined up since the last release.

Bump version to 0.43.2

---

src/julia/Integer.jl

julia/Integer: `x == 0` -> `iszero(x)`

---

Project.toml

There already were a lot of changes/fixes since the last release. I would suggest we do another release once the following are merged:
- https://github.com/Nemocas/AbstractAlgebra.jl/pull/1881

Bump version to 0.43.8

---

src/PrettyPrinting.jl

See https://github.com/Nemocas/AbstractAlgebra.jl/pull/1885#issuecomment-2449308636

Make `@show_special` a noop if no attribute storage available

---

src/generic/PolyRingHom.jl

Before:
julia> R = @polynomial_ring(QQ, :x); hom(R, R, x)
Ring homomorphism
from univariate polynomial ring in x over rationals
to univariate polynomial ring in x over rationalsHom: R -> R
defined by
x -> x
After:
julia> R = @polynomial_ring(QQ, :x); hom(R, R, x)
Ring homomorphism
from univariate polynomial ring in x over rationals
to univariate polynomial ring in x over rationals
defined by
x -> x

Fix show for PolyRingAnyMap

---

src/generic/Misc/Localization.jl

Some progress towards https://github.com/oscar-system/Oscar.jl/issues/2222

Add `hash(::LocalizedEuclideanRingElem)`

---

Project.toml

Things I'd like to see merged:
- #1910
- #1908
- #1924
Maybe also these *if/when they are ready*
- #1889
- #1857
Anything else? Oh I might have one adding `ideal_type` and a few more...

Set version to 0.44.0-DEV

---

src/Assertions.jl
src/PrettyPrinting.jl

Remove redundant global keyword usage

---

Project.toml

x-ref https://github.com/Nemocas/Nemo.jl/pull/1975#issuecomment-2548577952

Bump version to 0.44.1

---

src/MPoly.jl
src/Matrix.jl
src/Poly.jl
src/UnivPoly.jl
test/generic/UnivPoly-test.jl

and improve already existing `content` methods by using mutating `gcd!` ~~and adding an early exit (as already present in the dispatch for matrices)~~.

Add `content(::UnivPoly)`, fix potentially wrong result in `content(::MatrixElem)`, optimize a few other `content` methods

---

docs/src/assertions.md
src/Assertions.jl

Following from a suggestion on Slack on 2025-01-28 (thread started by @YueRen around 12:26 on 2025-01-27)

Improve documentation of `add_verbosity_scope`

---

src/generic/UnivPoly.jl

This should fix #1980. The new `_ensure_variables` function is due to @fingolfin.

Optimize `gens` for universal polynomials

---

ext/TestExt/Groups-conformance-tests.jl
ext/TestExt/Mutating-ops.jl
ext/TestExt/Rings-conformance-tests.jl
ext/TestExt/TestExt.jl

My main motivation is that this makes it way easier to rebase my
various existing conformance test branches.

Import more ConformanceTests stuff into TestExt

---

OscarCI.toml

@benlorenz could you please verify that this is basically the same as https://github.com/Nemocas/Nemo.jl/pull/2028?

OscarCI: try testing oscar master with released Nemo+Hecke+Singular

---

src/Rings.jl

Added new method for rings 'is_zero' for convenience that is a copy of 'is_trivial'
This resolves oscar-system/Oscar.jl#4574

Add `is_zero(::NCRing)` as an alias of `is_trivial`

---

src/RationalFunctionField.jl
src/generic/RationalFunctionField.jl
test/generic/RationalFunctionField-test.jl

- add a default variable (`t`)
- add `is_finite` and `characteristic`
CC: @fieker

feat: add some missing rational function field functionality

---

src/MPoly.jl
src/generic/MPoly.jl

This method is used for e.g. Nemo polynomials.

Simplify and slightly optimize vars(::MPolyRingElem)

---

Project.toml

Waiting for #1995 (maybe also #1994)

chore: bump to 0.44.6

---

src/generic/RationalFunctionField.jl
test/generic/RationalFunctionField-test.jl

- they are actually of degree >= 0 and can be finite

fix: is_finite for rational function fields

---

ext/TestExt/Mutating-ops.jl
ext/TestExt/Rings-conformance-tests.jl
src/ConformanceTests.jl
src/exports.jl
src/fundamental_interface.jl

Taking from https://github.com/Nemocas/Nemo.jl/pull/2037/, so that we have less friction down the road.
Do we usually add tests for these things? @lgoettgens?
CC: @fieker

feat: add `divides!`

---

test/generic/UnivPoly-test.jl

Apparently by some copy and paste mistakes some deterministic tests were run multiple times for no reason.

Remove redundant tests

---

src/generic/MPoly.jl
test/generic/MPoly-test.jl

Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/2010.

Add some missing `check_parent` in MPoly arithmetics

---

src/Matrix.jl
src/exports.jl

https://github.com/Nemocas/Nemo.jl/pull/2041 adds more specialized implementations

Add `is_(positive/negative)_entry` fallbacks

---

src/AbsSeries.jl
src/MPoly.jl
src/Poly.jl
src/RelSeries.jl
src/generic/AbsMSeries.jl
src/generic/GenericTypes.jl
src/generic/LaurentSeries.jl
src/generic/MPoly.jl
src/generic/UnivPoly.jl
test/generic/MPoly-test.jl

- compare types via === not ==
- optimize access to dictionaries via get!
- fix an infinite recursion
- improve some errors, use `@req`
- fix a type stability issue

Some tweaks to evaluate methods

---

src/Deprecations.jl
src/generic/MPoly.jl

Resolves https://github.com/Nemocas/AbstractAlgebra.jl/issues/2021.

Replace Val-dispatch by if-else in Generic.MPoly

---

src/MPoly.jl
src/generic/MPoly.jl
src/generic/UnivPoly.jl
test/generic/UnivPoly-test.jl

- add `_is_gen_with_index` with fallback to `is_gen(x, i)` and native implemenation for MPoly
- improve comparison of universal polynomials
CC: @karlwessel

Improvements for multivariate and universal polynomials

---

src/Map.jl

Following this morning's discussion on a PR to Oscar.jl.

Introduce stub for `is_equal_as_morphism`

---

Project.toml

to release https://github.com/Nemocas/AbstractAlgebra.jl/pull/2036

chore: Bump version to 0.44.10

---

src/generic/GenericTypes.jl
src/generic/Matrix.jl
test/generic/Matrix-test.jl

Enable point views of matrices

---

docs/src/linear_solving.md
docs/src/matrix.md
src/Solve.jl

- Added a clarifying comment about julia matrices vs AbstractAlgebra matrices
- Added more examples/doctests for some solving methods
This is rounding out oscar-system/Oscar.jl#2078. @HereAround @lgoettgens

Add useful comments and more solving examples

---

Project.toml

chore: bump version to 0.44.12

---

src/Rings.jl
src/generic/FunctionField.jl
src/generic/RationalFunctionField.jl
src/generic/imports.jl
test/generic/Fraction-test.jl
test/generic/FunctionField-test.jl
test/generic/RationalFunctionField-test.jl

- expand the docstring to include the definition

feat: more `is_perfect` methods and tests

---

src/FreeAssociativeAlgebra.jl
src/MPoly.jl
src/NCPoly.jl
src/Poly.jl
src/exports.jl
src/fundamental_interface.jl
src/generic/LaurentMPoly.jl
src/generic/LaurentPoly.jl
src/generic/UnivPoly.jl
src/generic/imports.jl
test/generic/FreeAssociativeAlgebra-test.jl
test/generic/LaurentMPoly-test.jl
test/generic/LaurentPoly-test.jl
test/generic/MPoly-test.jl
test/generic/NCPoly-test.jl
test/generic/Poly-test.jl
test/generic/UnivPoly-test.jl

Add `coefficient_ring_type`

---

.github/workflows/hecke.yml
.github/workflows/oscar.yml

Same as https://github.com/Nemocas/Nemo.jl/pull/2088

Add workaround for GLIBCXX issue with julia 1.6

---

src/NCRings.jl

https://nemocas.github.io/Nemo.jl/stable/developer/topics/#Aliasing-rules

make unary plus, mul obey aliasing rules

---

src/FreeModule.jl

Add vector_space_dim documentation

---

.github/workflows/singular.yml

Same as https://github.com/Nemocas/AbstractAlgebra.jl/pull/2094, but now also for Singular

Fix Singular downstream tests

---

src/generic/FreeAssociativeAlgebraGroebner.jl
test/generic/FreeAssociativeAlgebraGroebner-test.jl

Simplify obstructions handling

---

src/Rings.jl

Add stub for locality check.

---

Project.toml

... please hold off with merging until we've made a decision on PR #2115 resp. [this discussion](https://github.com/oscar-system/Oscar.jl/pull/5057#discussion_r2182310932) (should be today).

Version 0.45.2

---

src/Attributes.jl
src/Matrix.jl
test/Attributes-test.jl
test/generic/MPoly-test.jl
test/generic/Matrix-test.jl
test/misc-test.jl
test/runtests.jl

needs a bump of the julia compat to 1.10 before merge

Clean up obsolete `VERSION` checks

---

src/CommonTypes.jl
src/Factor.jl
src/MPoly.jl
src/Map.jl
src/MatRing.jl
src/Poly.jl
src/PrettyPrinting.jl
src/algorithms/FinField.jl
src/generic/Map.jl
src/generic/SparsePoly.jl
src/misc/VarNames.jl
test/generic/MatRing-test.jl
test/generic/SparsePoly-test.jl

This includes several genuine errors and performance improvements.

Resolve a bunch of JET warnings

---

src/broadcasting.jl
test/broadcasting-test.jl

fix: broadcasting with views of MatElem

---

Project.toml

Last tag before I bump the version to 0.47

chore: tag 0.46.5

---

docs/src/misc.md
src/Attributes.jl
src/KnownProperties.jl
src/PrettyPrinting.jl
src/exports.jl
test/Attributes-test.jl

This wraps the internal function `_is_attribute_storing_type`.
For potential use by @fieker.

Add is_attribute_storing and is_attribute_storing_type
